### ISSUE TITLE
[Federation] Enum Type resolvers are not working

### ISSUE THREAD

**Issue by Pruxis** [apollographql/apollo-server#2790] opened 2019-06-07 08:23 UTC
When defining enum resolvers they are not executed like they would with a regular schema.

This sandbox shares a bugreport of interfaces / unions, but the point is clear. Query animals with a type and you'll see that we never hit the resolver.

https://codesandbox.io/s/apollo-server-z8vml?fontsize=14

**Comment by trevor-scheer** [comment] 2019-06-07 22:37
Thanks for this one as well, @Pruxis!

I've made a couple small changes in a fork, the most noteworthy change being that I had to pass a literal value instead of a function for the enum resolver. I was able to reproduce this.
Related docs: https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values

1) Toggle between federated and non-federated schema
2) Note difference in log (federated ignores the `DOG: "dog"` mapping and just logs "DOG"

https://codesandbox.io/s/apollo-server-m30d7

**Comment by Pruxis** [comment] 2019-06-09 08:52
Hey @trevor-scheer thanks for taking the time to check this, I can use __isTypeOf for now as in the end it covers the same functionality only difference is that the code is more spread out over different types.

**Comment by hannesj** [comment] 2019-06-12 12:52
I think the root cause is the same as in https://github.com/apollographql/apollo-server/issues/2832

**Comment by JacksonKearl** [comment] 2019-07-01 23:24
Closed in #1345.

**Closed by JacksonKearl** 2019-07-01 23:24 UTC
Labels: 👩‍🚀 federation

**Comment by ahouzzer** [comment] 2019-10-30 00:12
If I use `graphql` function from `graphql.js` directly like this
```js
graphql(
            federatedSchema,
            query,
            {},                 // root value
            context,
            variables,
            null                // operation name
        )
```
Enum resolvers won't work either.

How can I apply middlewares as https://github.com/apollographql/apollo-server/pull/1345/files#diff-c635668124bc43d28885aa7d04c99342R96 did?

My use case does not use Apollo Server.

**Comment by krvajal** [comment] 2021-01-04 15:15
@Pruxis did you get it working?
