### ISSUE TITLE
Server 2.0: Error: Cannot read property 'setCacheHint' of undefined

### ISSUE THREAD

**Issue by ovaris** [apollographql/apollo-server#1201] opened 2018-06-20 11:17 UTC
Hi,

trying to set cache programatically in my resolver, using latest apollo-server-express rc.0, the info parameter doesn't contain cacheControl:
`Error: Cannot read property 'setCacheHint' of undefined`

https://www.apollographql.com/docs/engine/caching.html#resolver-hints

```
items: (parent: any, args: any, context: any, { cacheControl }: any) => {
        cacheControl.setCacheHint({ maxAge: 60000 });
    },
```

**Comment by evans** [comment] 2018-06-20 18:19
Ah yes! Thank you for opening the issue. Under the hood we are using `mergeSchema` to support file uploads. Currently it breaks cache-control, so we'll be removing it with #1204 and releasing another rc later today or tomorrow.

**Comment by evans** [comment] 2018-06-21 22:50
We've released RC.1, which solves the issue of cacheControl being undefined. Definitely caused by `mergeSchemas`. I've tested locally, so I feel comfortable closing. Thank you @ovaris for opening the original issue!

**Closed by evans** 2018-06-21 22:50 UTC

**Comment by eberhara** [comment] 2018-09-19 20:51
@evans how are you doing?
Is this fix on `apollo-express-server@2.1.0`?

I am using this version +  `mergeSchemas` to merge remote and local schemas. The problem is that `cacheControl` is still undefined for me.

When I remove the `mergeSchemas`, it works fine.

**Comment by schettino** [comment] 2019-06-23 22:04
I was also facing this.  Turns out that it's the `transformSchema`  that is currently breaking the cache-control.

**Comment by Aviral-swa** [comment] 2021-05-18 06:48
Hi,
is this still not fixed?
getting the same error as @ovaris

**Comment by glasser** [comment] 2021-05-18 23:01
@Aviral-swa Is it possible that this is the same as the issue described at https://github.com/apollographql/apollo-server/issues/4810#issuecomment-791788071 ?

**Comment by ashakhray2** [comment] 2022-05-20 07:55
I had the same issue. The `mergeSchemas` doesn't work correctly.
The fix is use the `mergeSchemas` from @graphql-tools/schema (tested on 8.3.11)
`const { mergeSchemas } = require('@graphql-tools/schema')`
Works.
