### ISSUE TITLE
How to set up response charset with ApolloServer2

### ISSUE THREAD

**Issue by Tonyce** [apollographql/apollo-server#2133] opened 2018-12-24 08:50 UTC
I love use ApolloGraphQL，It brings me a lot of convenience，but how do i set the charset with appollo， express method not work

**Comment by Tonyce** [comment] 2018-12-25 02:35
```js
if (responseInit.headers) {
   for (const [name, value] of Object.entries(responseInit.headers)) {
       res.setHeader(name, value);
   }
 }
```
this code reset the Content-Type, and the initHeaders without charset set. 
```ts
const responseInit: ApolloServerHttpResponse = {
    headers: {
      'Content-Type': 'application/json',
    },
  };
...
responseInit.headers!['Content-Length'] = Buffer.byteLength(
    body,
    'utf8',
  ).toString();
```
please add charset in initHeaders, or expose the config maybe better

**Comment by abernix** [comment] 2019-09-03 12:58
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.  (I can't quite tell by the issue itself).

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.

If this turns out to be a bug or a feature request, please open an new issue with a runnable reproduction or a proposal for a solution.

Thanks for your understanding!

**Closed by abernix** 2019-09-03 12:58 UTC
