### ISSUE TITLE
Typescript error in apollo-server-lambda dependency

### ISSUE THREAD

**Issue by tomyitav** [apollographql/apollo-server#1525] opened 2018-08-12 21:09 UTC
Hi, I'm getting the following error when trying to use apollo-server-lambda package:

![error-on-cache-control](https://user-images.githubusercontent.com/16193919/44006361-02d99556-9e8c-11e8-8d11-c91f31057bf7.PNG)

I try to create a simple lambda handler the following way:

![handler-definition](https://user-images.githubusercontent.com/16193919/44006427-eac2c626-9e8c-11e8-84a4-f557012fec1d.PNG)

My dependencies are:
"dependencies": {
    "apollo-server-core": "^2.0.0",
    "apollo-server-lambda": "^2.0.0",
    "aws-lambda": "^0.1.2",
    "aws-serverless-express": "^3.2.0",
    "body-parser": "^1.15.2",
    "core-js": "^2.5.1",
    "cors": "^2.8.0",
    "express": "4.14.0",
    "graphql": "^0.13.0",
    "graphql-code-generator": "^0.8.13",
    "graphql-server-express": "^1.4.0",
    "graphql-subscriptions": "^0.5.6",
    "graphql-tools": "^2.18.0",
    "injection-js": "^2.2.1",
    "lodash": "^4.15.0",
    "merge-graphql-schemas": "^1.4.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.5.2",
    "subscriptions-transport-ws": "^0.9.5",
    "winston": "^2.3.1",
    "winston-daily-rotate-file": "^1.4.6",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "nodemon": "1.11.0",
    "@types/graphql": "0.11.7",
    "@types/mocha": "2.2.41",
    "@types/node": "7.0.22",
    "@types/winston": "^2.3.7",
    "@types/lodash": "^4.14.100",
    "@types/express": "^4.0.38",
    "typescript": "^3.0.1",
    "eslint": "4.0.0",
    "eslint-config-airbnb-base": "11.2.0",
    "eslint-plugin-import": "2.3.0",
    "eslint-plugin-promise": "3.5.0",
    "mocha": "3.4.2",
    "react-dom": "^15.6.0",
    "supertest": "3.0.0",
    "tsc": "1.20150623.0",
    "typescript-eslint-parser": "3.0.0"
  }

Is there a problem with the apollo-cache-control dependency of apollo-server-lambda?

**Comment by abernix** [comment] 2019-07-03 19:04
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-07-03 19:04 UTC
Labels: :hand: blocking, :rose: has-reproduction, tag: typings

**Comment by maslennikov** [comment] 2020-01-04 16:06
as annoying as it may be, I had nothing better to do than to enable in my `.tsconfig` the flag with `compilerOptions.skipLibCheck = true`
