### ISSUE TITLE
Playground config requires all properties in TypeScript

### ISSUE THREAD

**Issue by kallaspriit** [apollographql/apollo-server#1713] opened 2018-09-24 08:41 UTC
ApolloServer constructor accepts parameter `playground?: PlaygroundConfig` where

```typescript
export type PlaygroundConfig =
  | RecursivePartial<PlaygroundRenderPageOptions>
  | boolean;
```

where

```typescript
type RecursivePartial<T> = {
  [P in keyof T]?: T[P] extends (infer U)[]
    ? RecursivePartial<U>[]
    : T[P] extends object ? RecursivePartial<T[P]> : T[P]
};
```

This results in TypeScript requiring one to define all playground options not just the ones that you want to override from defaults.

To reproduce just attempt to create an instance of ApolloServer with playground options not setting all available options:

```typescript
const server = new ApolloServer({
    playground: {
        settings: {
            "request.credentials": "include",
        },
    }
});
```

Failure to provide all options results in:
```
Types of property 'settings' are incompatible.
Argument of type '{ playground: { settings: { "request.credentials": string; }; }; }' is not assignable to parameter of type 'Config'.
  Types of property 'playground' are incompatible.
    Type '{ settings: { "request.credentials": string; }; }' is not assignable to type 'boolean | RecursivePartial<RenderPageOptions> | undefined'.
      Type '{ settings: { "request.credentials": string; }; }' is not assignable to type 'RecursivePartial<RenderPageOptions>'.
        Types of property 'settings' are incompatible.
          Type '{ "request.credentials": string; }' is not assignable to type 'ISettings'.
            Property ''general.betaUpdates'' is missing in type '{ "request.credentials": string; }'.
```

TypeScript version: `3.0.3`.

**Comment by inakianduaga** [comment] 2018-11-14 23:03
from a quick look the `RecursivePartial` seems incorrect, should work with 

```ts
type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]>; };
```  

at least on the latest TS 3.1

**Comment by Mando75** [comment] 2019-01-12 23:01
Having the same issue. Is there currently a work around available for this besides just marking it to ignore?

**Comment by chenglabs** [comment] 2019-01-13 08:56
Something like this...

`
return new ApolloServer({
    playground: {...defaultPlaygroundOptions,
      settings: {
        ...defaultPlaygroundOptions.settings,
        "request.credentials": "include",
      }
    },
`

**Comment by marcospgp** [comment] 2019-04-17 14:01
`RecursivePartial` looks so obscure and complex that I can't help but feel there is a simpler alternative. This fail sure demonstrates that 😄

**Comment by marcospgp** [comment] 2019-04-17 14:01
RecursivePartial looks so obscure and complex that I can't help but feel there is a simpler alternative. This problem surely demonstrates that 😄

**Comment by marcospgp** [comment] 2019-04-17 14:01
`RecursivePartial` looks so obscure and complex that I can't help but feel there is a simpler alternative. This problem surely demonstrates that 😄

**Comment by JacksonKearl** [comment] 2019-07-02 00:36
Is anyone still experiencing this? Fix is:
```
type RecursivePartial<T> = {
  [P in keyof T]?: T[P] extends (infer U)[]
    ? RecursivePartial<U>[]
    : T[P] extends (object | undefined) ? RecursivePartial<T[P]> : T[P]
};
```

Where `T[P] extends (object | undefined)` is in place of `T[P] extends object` above. But it seems to only affect older versions of AS.

**Comment by JacksonKearl** [comment] 2019-07-02 23:13
Closing this for now. If someone is still experincing issues we can apply that patch, but as I said earlier it *seems* not to affect recent versions of AS.

**Comment by strefethen** [comment] 2019-07-03 04:35
@JacksonKearl  FWIW, I'm using apollo-server-express 2.6.5 and TypeScript 3.4.3 and I'm seeing this problem.

**Comment by JacksonKearl** [comment] 2019-07-03 04:59
Inter

**Comment by strefethen** [comment] 2019-07-08 16:12
@JacksonKearl what's the proper way to rebuild the apollo-server-core package after making the above change? I created a tsconfig.json file in node_modules/apollo-core-server and run tsc which gave me a "cannot find module "mock-req" so I just moved that folder and tried to rebuild but I'm getting:
```
➜  apollo-server-core git:(master) ✗ tsc
src/playground.ts:73:9 - error TS2322: Type '{ settings: { 'general.betaUpdates': boolean; 'editor.theme': Theme; 'editor.cursorShape': CursorShape; 'editor.reuseHeaders': boolean; 'tracing.hideTracingResponse': boolean; 'queryPlan.hideQueryPlanResponse': boolean; 'editor.fontSize': number; 'editor.fontFamily': string; 'request.credentials': string; } | { ...;...' is not assignable to type 'RenderPageOptions'.
  Type '{ settings: { 'general.betaUpdates': boolean; 'editor.theme': Theme; 'editor.cursorShape': CursorShape; 'editor.reuseHeaders': boolean; 'tracing.hideTracingResponse': boolean; 'queryPlan.hideQueryPlanResponse': boolean; 'editor.fontSize': number; 'editor.fontFamily': string; 'request.credentials': string; } | { ...;...' is not assignable to type 'RenderPageOptions'.
    Types of property 'schema' are incompatible.
      Type 'RecursivePartial<IntrospectionResult> | undefined' is not assignable to type 'IntrospectionResult | undefined'.
        Type 'RecursivePartial<IntrospectionResult>' is not assignable to type 'IntrospectionResult'.
          Property '__schema' is optional in type 'RecursivePartial<IntrospectionResult>' but required in type 'IntrospectionResult'.

73   const playgroundOptions: PlaygroundRenderPageOptions = {
```
Thanks,
-Steve

**Comment by JacksonKearl** [comment] 2019-07-08 18:00
Ah! Do you have `strictNullChecks` enabled? That seems to be the culprit here, as with that enabled an `object | undefined` will no longer `extends` `object`.  Demo [playground]( https://www.typescriptlang.org/play/#code/DYUwLgBADsCGCeBzATgewK4DsAmAuCASiAMbrIDOAlgG4gAKsyYlswAPETiMg4iAPJRmqTOQB8EALwQA3gCgIEcuGaZE5fPMWKA5CGyUwqZADowACxABbEDvw7glRObA6ANAogBfD14DccnKgkDAIKBg4AEz4RKQUNPSMzKyRHCBcPLB8gsKiEtJaSiqUahqynrr6hsZmljZ2EA5OLu6ePnL+gQD0XRAuYFAaPeRgsMQA1qi0yABmwKgA7ibEqFZdsF0ArACMAMwAbJsADLsA7HJg8FAghCRkVLQMTCzsACr55YoA2nQQJRDjEDwVAzCCvAC6AH58K8fuCICAAB5gdLYcgQAAUJRm3AgAFUAJRfcEVCCQ25xB6JZ6sNh4sTE0kwuEI5Go9EY1AAIwAViRIASIKTybF7gknsk3nCxEywXCAp0LlcbqL4o8ki9Uu8pJ8ID8-pgAUCQWCocy6PCkSicBzsbjCYztGSKWL1TT2PTHdpzZa2TbMdy+cRIAAfCBYbAgGYlfSC4UutXUyVsWEWmVOn0KgJCxRIqDGSAlFGzMYq1HcXgCISUEToq3siAAWUo2GwoAWjCruXRhUU0yoImhSjAyBKiGz2mI2EweOQwCHI1Hagnucw1CHsEw8BXEGYYFAC5HY53M1g1EoKxnc8PS8QEDDmHQwGAE68gSdeYLBuLp+IN2brbtp2OQ1qIuqrtg+ZFjex6kuQ6BcuQxCjtWIgAKI4FBmBgDBy6kgsxjjOQUClgAcrANi4eOpLpOu+CbtupKXtGiAbluO7KGAqjqEOACSADKxSlDub40Yi+ZMBAkbEHAyA3Jc1wQAAwvcxj8eYsCKdITSYLY96NFy8wTDo+k6BG3COLpOgBJ+knSbJ8nKmCdQ3Np2CMOMJlhk0ziuDZ4lfkW3C-jcAlCeo4GNHwunIKwJhcuAsB4lA7kouQDRcqgqCgJuO56AYRimJSakadcDQqRQJWaSAeVVIVtTWLYMIubVBU1HJ6DKAAEiAsCRhQGVZTlmB5SOYxjiY5gtiAryxcQY5EMRtZNRAmXZb1I2kjoACO6DcPAdBwJgk3TQAintyAHUdi35qIthDmtw2tdUpgzCIYD8ZQABeK2PlYCXIM99VvdhABiFGUMA8ANIusFOjocm7SAIzLHJkbYS86X4LDeFeEAA). You can flip `strictNullChecks` in the options and the first config will flip between valid and invalid.

**Comment by strefethen** [comment] 2019-07-08 21:00
@JacksonKearl ok I got it to build. Here's my playground config:
```
    playground: {
      settings: {
        "editor.theme": "light"
      }
    },
```
Which is now causing this error:
```
Type '{ settings: { "editor.theme": string; }; }' is not assignable to type 'boolean | RecursivePartial<RenderPageOptions> | undefined'.
  Type '{ settings: { "editor.theme": string; }; }' is not assignable to type 'RecursivePartial<RenderPageOptions>'.
    Types of property 'settings' are incompatible.
      Type '{ "editor.theme": string; }' is missing the following properties from type 'ISettings': 'general.betaUpdates', 'editor.cursorShape', 'editor.reuseHeaders', 'tracing.hideTracingResponse', and 3 more.
```

**Comment by JacksonKearl** [comment] 2019-07-08 21:30
If you check #3010, there are two changes that need to be made: first the type definition needs to be changed to the `extends (object | undefined)`, and second `playgroundOptions` needs to be coerced to `any`, as the types aren't actually quite accurate right now. So the first error you got regarding `__schema` being optional is actually a correct error.

**Closed** 2019-07-09 04:31 UTC
Labels: 🛹 playground, 🧬 typings

**Comment by brianwachira** [comment] 2021-08-05 07:20
> Is anyone still experiencing this? Fix is:
> 
> ```
> type RecursivePartial<T> = {
>   [P in keyof T]?: T[P] extends (infer U)[]
>     ? RecursivePartial<U>[]
>     : T[P] extends (object | undefined) ? RecursivePartial<T[P]> : T[P]
> };
> ```
> 
> Where `T[P] extends (object | undefined)` is in place of `T[P] extends object` above. But it seems to only affect older versions of AS, no clue why as the types haven't really changed.
> 
> In the [playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBAShDGBXATgZwJYDcIAUCGyw6eANgDwAqAfFALxQDeAUFFANo5ToB2UA1hBAB7AGZQKAXQD8ALnEcJUCAA9gEbgBNUUABQ8REZFACqASjYSWrKFNgIUGbPkLFyxqhaus5FBUtXqWlBCAEYAVgjANnZIaFi4BESklAo0PgpMAL4A3ExMoJAxDvHOSSQATJQ09MysHFy8AsJikrLyOIoqapraetwGRmae1tFwsY4JLsnuw9bpHf7dQTqhEfBRAD5QiJoQIjwQGqaj9nFOia4pHWntljl5TCpgQoRQBdAAyhDARNwA5toalY8HJUMBkDw-rlWCFQeDIblMlA8k8XlF3lAAPJgIhCbiAxhWVDfX4AtpfH6Q1CIvIkb5QMAkPAgP7IIQ7DRyMbFc5TcjY3H46qE1jEyn-VByWrWEFQADkeDlABorJkVfcmHSoozmaz2ZpylzThNSq5KgL0HjUMLpWLSZKRTK5Arlar1dkgA)

how does this fix? could you show me an example?
I am currently experiencing this issue.

**Comment by glasser** [comment] 2021-08-17 05:28
If you can share a minimal reproduction of the issue you're seeing, that would help with diagnosing.

**Comment by brianwachira** [comment] 2021-08-17 05:55
I was using Apollo Server 3 & I wanted to enable playground on production.  I went to apollo server  [docs](https://www.apollographql.com/docs/apollo-server/migration/#graphql-playground)
It says : 

> If your code passed new ApolloServer({playground: true}), you can keep the previous behavior with:
> 
```
> import { ApolloServerPluginLandingPageGraphQLPlayground } from 'apollo-server-core';
> new ApolloServer({
>   plugins: [
>     ApolloServerPluginLandingPageGraphQLPlayground(),
>   ],
> });
```
Hence I added that on my code and playground now worked on production.

**Comment by glasser** [comment] 2021-08-17 22:09
Er, so are you still experiencing an issue?

**Comment by tvelich** [comment] 2022-04-28 22:54
> Er, so are you still experiencing an issue?

These options are still erroring as required for me when I include one even though I'm seeing them all as optional:
typescript 4.2.4
apollo-server-core 3.6.7
