### ISSUE TITLE
ForbiddenError does not return 403 status code

### ISSUE THREAD

**Issue by curry684** [apollographql/apollo-server#1512] opened 2018-08-09 13:14 UTC
Simplified code:
```
const {ApolloServer, ForbiddenError} = require('apollo-server-koa');

new ApolloServer({
          typeDefs,
          resolvers,
          context: async ({ctx, connection}) => {
              const user = connection ? connection.context.user : ctx.state.user;
              if (!user.scopes || !user.scopes.includes('api:read')) {
                  throw new ForbiddenError('Your token does not have required scope "api:read"');
              }
              return {user};
          },
});
```
This correctly fails the request:
```
{
  "error": {
    "errors": [
      {
        "message": "Context creation failed: Your token does not have required scope \"api:read\"",
        "extensions": {
          "code": "FORBIDDEN",
          "exception": {
            "stacktrace": [
              "ForbiddenError: Context creation failed: Your token does not have required scope \"api:read\"",
              "    at ApolloServer.context (...)",
....
```
However it does so with HTTP response code 400, instead of the 403 I was expecting. Now in other threads I've seen the argument that "this is not the GraphQL way to rely on HTTP response codes". However, I'm failing at the context creation level, not the resolver level. So it is a total request failure, otherwise it would also give a 200 with an errors array. 

The information is also important to me on the client side. When parsing the JWT in Passport before the request is handed to Apollo, I throw a 401 if the JWT is expired, as that is correct HTTP semantic for *"your request failed now, but you may retry it with a fresh token"*. While a missing OAuth scope simply means *"your request will never work until you change something elsewhere"*. So I should be able to differentiate between those response codes on the server so I can act correctly on them elsewhere.

**Comment by trevorblades** [comment] 2019-07-08 21:01
This is by design, as noted by this comment: https://github.com/apollographql/apollo-server/blob/2d1544d049429f979cfcb28c9b83589e23873885/packages/apollo-server-core/src/runHttpQuery.ts#L139

Currently we return a `500` for internal server errors, and `400` for everything else. Given the code in this function, it would be possible to account for other GraphQL error codes (`FORBIDDEN` for example), and return a specific status code for each.

I'm going to close this issue now, but feel free to submit a PR with this change if you still need it!

**Closed by trevorblades** 2019-07-08 21:01 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by hwillson** [comment] 2019-07-08 21:13
Just to add to the above, please also see https://github.com/apollographql/apollo-server/issues/1709#issuecomment-495793375 for an example that shows how you can use `didEncounterErrors` to customize the response HTTP status code.

**Comment by willrust** [comment] 2020-02-17 22:06
What would be the best approach on the client side for differentiating between what would have been a 403 or 401, if it's all a 400?
