### ISSUE TITLE
Allow throwing HttpQueryError in options function

### ISSUE THREAD

**Issue by aldeed** [apollographql/apollo-server#756] opened 2018-01-11 21:38 UTC
Using: `apollo-server-express`
But the code that would need to be changed is in `apollo-server-core`

Proposal: If an `HttpQueryError` is thrown from an options function, return that rather than hiding it.

Use case:

```js
graphqlExpress(async (request) => {
      const { token } = request;
      let context;
      try {
        context = token ? await addUserToContext({ token }) : {};
      } catch (error) {
        throw new HttpQueryError(401, error.message);
      }
      return {
        context,
        schema,
      };
    });
```

Currently this gets changed to a 500 error.

It requires only two lines added.

Add `if (e.name === 'HttpQueryError') throw e;` before throwing in these two catches:

- https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/runHttpQuery.ts#L61
- https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/graphqlOptions.ts#L49

Do people agree that this is the correct approach?

**Comment by BrendanBall** [comment] 2018-05-04 09:55
I want to be able to log these kinds of errors because currently you can see the status was 500 from express but you don't know why. apollo-server-express catches HttpQueryErrors and silently returns a 500 without any logging at https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/src/expressApollo.ts#L58. 

Do you think this is part of this issue?

**Comment by abernix** [comment] 2019-07-02 13:30
👋 I'll close this since it's pretty old, but I'm happy to re-open this persists as a problem with more recent versions of Apollo Server.  There hasn't been any recent activity on it though, so I'm going to assume this changed with v2. :smile:

**Closed by abernix** 2019-07-02 13:30 UTC

**Comment by ramirost** [comment] 2020-01-08 16:45
Hi,

this issue is still present in master and can cause problems to determine the cause of an error, let me explain...

In our case we were getting invalid requests from a client and the server was returning 500 errors, (it was fine in our case to be a 500 error as it was not hiding a different error like other use case above), the problem is that we were confident that any error produced in the server was being logged, but was not the case with this error, and seems to be imposible at all to log these HttpQueryErrors with the current code of apollo-server-express, which causes problems to determine the cause of a client error.

It would be nice to be able to log these errors or to be thrown as any other error (although I don't know if the later may be problematic)
