### ISSUE TITLE
Subscriptions using built-in SubscriptionServer error: client gets "Cannot read property 'headers' of undefined"

### ISSUE THREAD

**Issue by tab00** [apollographql/apollo-server#1537] opened 2018-08-15 14:51 UTC
The server sees client connecting successfully, but the client gets the error, even if nothing is published from server.

Meteor's WebApp is the HTTP server.

```javascript
  import { ApolloServer } from 'apollo-server-express'
  import { typeDefs } from './schema.js'
  import { resolvers } from './resolvers.js'
  import { DSBooks } from "./DSBooks.js"
  import { getUser } from 'meteor/apollo'

  const server = new ApolloServer({
    typeDefs,
    resolvers,
    dataSources: () => ({
      dsBooks: new DSBooks()
    }),
    context: async ({ req }) => ({ user: await getUser(req.headers.authorization) }),
    uploads: false,
    subscriptions: {
      path: "/subscriptions",
      onConnect: async (connectionParams, webSocket, context) => {
        console.log(`Subscription client connected using Apollo server's built-in SubscriptionServer.`)
      },
      onDisconnect: async (webSocket, context) => {
        console.log(`Subscription client disconnected.`)
      }
     }
  })


  import { WebApp } from 'meteor/webapp'
  server.applyMiddleware({ app: WebApp.connectHandlers }) //path option defaults to /graphql
  WebApp.connectHandlers.use('/graphql', (req, res) => { if (req.method === 'GET') res.end() }) // To prevent server-side exception "Can't set headers after they are sent" because GraphQL Playground (accessible in browser via /graphql) sets headers and WebApp also sets headers

  server.installSubscriptionHandlers(WebApp.httpServer)
```

If I start a new `SubscriptionServer ` instead, there's no problem, and the client receives subscription data.
```javascript
  import { ApolloServer } from 'apollo-server-express'
  import { typeDefs } from './schema.js'
  import { resolvers } from './resolvers.js'
  import { DSBooks } from "./DSBooks.js"
  import { getUser } from 'meteor/apollo'

  const server = new ApolloServer({
    typeDefs,
    resolvers,
    dataSources: () => ({
      dsBooks: new DSBooks()
    }),
    context: async ({ req }) => ({ user: await getUser(req.headers.authorization) }),
    uploads: false,
  })


  import { WebApp } from 'meteor/webapp'
  server.applyMiddleware({ app: WebApp.connectHandlers }) //path option defaults to /graphql
  WebApp.connectHandlers.use('/graphql', (req, res) => { if (req.method === 'GET') res.end() }) // To prevent server-side exception "Can't set headers after they are sent" because GraphQL Playground (accessible in browser via /graphql) sets headers and WebApp also sets headers


  import { SubscriptionServer } from 'subscriptions-transport-ws'
  import { execute, subscribe } from 'graphql'
  import { makeExecutableSchema } from 'graphql-tools'

  SubscriptionServer.create(
    {
      schema: makeExecutableSchema({ typeDefs, resolvers }),
      execute,
      subscribe,
      onConnect: async (connectionParams, webSocket) => {
        console.log(`Subscription client connected using new SubscriptionServer.`)
      },
      onDisconnect: async (webSocket, context) => {
        console.log(`Subscription client disconnected.`)
      }
  },
    {
      server: WebApp.httpServer,
      path: "/subscriptions",
    },
  )
```

**Comment by tab00** [comment] 2018-08-15 15:01
Code showing `ApolloClient` creation:
```javascript
    import ApolloClient from 'apollo-client'
    import { ApolloLink } from 'apollo-link'
    import { MeteorAccountsLink } from 'meteor/apollo'
    import { HttpLink } from 'apollo-link-http'
    import { WebSocketLink } from 'apollo-link-ws'
    import { InMemoryCache } from 'apollo-cache-inmemory'
    import { Meteor } from "meteor/meteor"

    const apolloClient = new ApolloClient({
      link: ApolloLink.split( // split based on operation type
        ({ query }) => {
          import { getMainDefinition } from 'apollo-utilities'
          const { kind, operation } = getMainDefinition(query)
          return kind === 'OperationDefinition' && operation === 'subscription'
        },
        new WebSocketLink({
          uri: `${Meteor.absoluteUrl("/subscriptions").replace("http", "ws")}`,
          options: { reconnect: true }
        }),
        ApolloLink.from([
          new MeteorAccountsLink(),
          new HttpLink({ uri: '/graphql' })
        ]),
      ),
      cache: new InMemoryCache()
    })
```

**Comment by tab00** [comment] 2018-08-15 15:28
Both `apolloClient.subscribe()` and the `Subscription` React component produce the same error.

**Comment by dnalborczyk** [comment] 2018-08-16 12:27
hey @tab00 had the same exception, you could start looking here. I didn't have any headers on the websockets (subscriptions):

```javascript
context: async ({ req }) => ({ user: await getUser(req.headers.authorization) })
```

```javascript
async context(val) {
  console.log(val && val.req)
}
```

**Comment by tab00** [comment] 2018-09-18 11:01
This problem still exists. Please fix it.

**Comment by almostprogrammer** [comment] 2018-09-19 11:08
Should you use req when using subscriptions? Docs point out that you should use `connection` to create context from a subscription https://www.apollographql.com/docs/apollo-server/v2/features/subscriptions.html#Context-with-Subscriptions

**Comment by tab00** [comment] 2019-01-18 14:55
I still get this problem. Has anyone tried to fix this?

**Comment by myhendry** [comment] 2019-02-04 04:48
@almostprogrammer is correct. I structured my ApolloServer code below and it works. for subscription, you don't use req. u need to use connection
details https://github.com/apollographql/graphql-subscriptions/blob/master/.designs/authorization.md

```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: async ({ req, connection }) => {
    if (connection) {
      return {
        ...connection.context,
        pubsub
      };
    } else {
      const token = req.headers["authorization"] || "";
      return {
        User,
        Tweet,
        Comment,
        pubsub,
        userId: await getUser(token)
      };
    }
  }
});
```

**Comment by tab00** [comment] 2019-02-08 06:12
@myhendry, why isn't there `subscriptions` in the argument list of your `ApolloServer` instantiation?

**Comment by myhendry** [comment] 2019-02-08 07:02
They are all in my resolvers file

https://github.com/myhendry/template/blob/master/server/graphql/resolvers.js

**Comment by tab00** [comment] 2019-02-09 12:59
@myhendry, are you using Meteor and the built-in `SubscriptionServer`?

Does your code have `server.installSubscriptionHandlers(WebApp.httpServer)`?

Can you provide minimal working code of a Meteor app that uses the built-in `SubscriptionServer`?

**Comment by tab00** [comment] 2019-02-09 13:07
I've just made package updates and tried my original code, and have found it's now working as expected without the error. I'll check further to confirm that there is no longer a problem and then close this issue.

**Comment by myhendry** [comment] 2019-02-09 14:55
I am not using meteor. I am using node js. I haven't tried using meteor
with graphql

**Comment by jedwards1211** [comment] 2019-02-13 23:02
@helfer the problem here is that [SubscriptionServer calls `this.context({ connection, payload: message.payload })`](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/ApolloServer.ts#L471), hence `req` is undefined in OP's `context` function.  The only documentation on the website for `context` shows it being called with the `(req, res)` from an HTTP request; I can't find any documentation of it being called by SubscriptionServer.  Seems like this is either a mistake or the documentation needs to be fixed?

**Comment by jedwards1211** [comment] 2019-02-13 23:07
@helfer to make matters worse, https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/ApolloServer.ts#L480 overwrites the context created by `subscriptions: { onConnect: async (connectionParams: any) => { ... } }` that is recommended in the docs on the website.

It seems like the developers working on the ApolloServer 2 refactor weren't all on the same page?

**Comment by ozanmanav** [comment] 2019-02-16 14:43
same here its overwrites context with null. I set subscribed user on Connect. When i try in resolvers, its seems undefined.

**Comment by ozanmanav** [comment] 2019-02-17 08:48
I found a solution Context must be used with connection.context check here.

![image](https://user-images.githubusercontent.com/19241756/52910547-f9018900-32a9-11e9-82fe-37319620aece.png)

https://github.com/apollographql/apollo-server/issues/1796#issuecomment-429237068

**Comment by jedwards1211** [comment] 2019-02-18 06:07
@tab00 I documented in #2315 how I think the way both HTTP and Websockets call the `context` function causes more confusion than it's worth

**Comment by jbaxleyiii** [comment] 2019-07-08 21:55
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Comment by StefanFeederle** [comment] 2019-07-11 11:33
This is still an issue for most people who setup auth with subscriptions.
It's possible to get it working but really not as easy as it should be.
Please see #2351 for proposed api change.

This is a running sandbox showing the problem: https://codesandbox.io/s/apollo-server-qthfh?fontsize=14

**Comment by jedwards1211** [comment] 2019-07-11 14:10
@StefanFeederle that seems like the wrong issue number, mind checking it?

**Comment by StefanFeederle** [comment] 2019-07-11 14:28
@jedwards1211 Thanks, fixed it

**Comment by Landoooooo** [comment] 2020-01-25 06:56
Is this dead? I'm having issues with receiving the connection param from context. I'm using websockets for auth If that's relevent.

**Comment by glasser** [comment] 2022-03-04 17:46
Apollo Server no longer has a built-in SubscriptionServer.

**Closed by glasser** 2022-03-04 17:46 UTC
Labels: :beetle: bug, :rose: has-reproduction, 🧬 subscriptions
