### ISSUE TITLE
This version is not support node 8.11.4

### ISSUE THREAD

**Issue by loveyoubaby5120** [apollographql/apollo-server#1584] opened 2018-08-27 08:10 UTC

**Comment by loveyoubaby5120** [comment] 2018-08-27 08:10
![image](https://user-images.githubusercontent.com/11256291/44648464-b73b0880-aa13-11e8-9b6d-8cadea260b97.png)

**Comment by maxnachlinger** [comment] 2018-08-27 21:26
I can't reproduce this, here's my output.
```
node -v; npm -v
> v8.11.4
> 6.4.0
npm i apollo-server graphql
> protobufjs@6.8.8 postinstall /Users/m0n0096/sandbox/fun/node_modules/protobufjs
> node scripts/postinstall

+ apollo-server@2.0.5
+ graphql@0.13.2
added 150 packages from 176 contributors in 46.871s

**Comment by loveyoubaby5120** [comment] 2018-09-03 06:16
@maxnachlinger no,thx.

**Comment by maxnachlinger** [comment] 2018-09-04 17:50
@loveyoubaby5120 could you please close this issue? Think of all the issues the maintainers - who are not paid - have to deal with :)

**Closed** 2018-09-07 06:42 UTC
