### ISSUE TITLE
is it possible to allow extra fields in custom input?

### ISSUE THREAD

**Issue by kdong007** [apollographql/apollo-server#1101] opened 2018-05-28 03:15 UTC
this is my input type
```
input LocationInput{
    latitude: Float
    longitude: Float
}
```

my front end is built using RN+react apollo. sometime the apollo cache adds extra data in my location object and it gets sent to server, so this happened:
`HTTP status code 400: Variable "$from" got invalid value {"@@id":"$Community:5a6a1e7cb416a95c8328f9bd.location","latitude":39.906331947912626,"longitude":116.35254808644798}; Field "@@id" is not defined by type LocationInput.`

is it possible to ignore extra field?

**Comment by hwillson** [comment] 2019-07-08 20:28
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by hwillson** 2019-07-08 20:28 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by lensbart** [comment] 2022-11-05 18:59
I’m interested in this as well. My use case is as follows: I’d like to pass one or more URL `params` (from e.g. React Router’s `useParams()`) as a query variable. The only thing I’m interested in is if some value e.g. `invoice` is present in the URL, so that `params.invoice` is available.

It would be easier to reuse query logic if I could just pass `params`, without having to care about whether the URL has _other_ params as well (that is, if there are other properties in the `params` object).

**Comment by glasser** [comment] 2022-11-07 19:16
@lensbart Getting variable values from URL params is definitely an extension over the standard "GraphQL over HTTP/JSON" protocol and will lead to interop issues (other tooling won't know about this and will think you're missing variable values) but if you're up for that you can make it work.

One option is to define your `$params` variable to be of a scalar type. Scalar types can have any valid JSON object structure so you don't need to pre-declare your fields.

If you really only care about a specific `invoice` parameter then you could do something hacky like this:

```
const app = express();
app.use(cors(), bodyParser.json());
app.use((req, res, next) => {
  if (req.query.invoice) {
    if (!req.body.variables) {
      req.body.variables = {};
    }
    req.body.variables.invoice = req.query.invoice;
  }
  next();
});
app.use(expressMiddleware(server));
```

Not sure I'd really recommend this though!

**Comment by lensbart** [comment] 2022-11-07 19:19
Hi @glasser, thanks for your informative response. I think it’s better to stick to predictable/standard behaviour and I’m just omitting the properties I don’t need at the front end. Works well enough!
