### ISSUE TITLE
Better error message when schema reporting is enabled with an invalid API key

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/apollo-server#4797] opened 2020-12-18 18:05 UTC
When the `APOLLO_KEY` environment variable is set to a user scoped token (not a graph scoped token) and Apollo Server is started, it gives the following error message:

```
Error: You've enabled usage reporting via ApolloServerPluginUsageReporting, but you also need to provide your Apollo API key, via the APOLLO_KEY environment variable or via `new ApolloServer({apollo: {key})
```

In this case, I have not explicitly enabled `ApolloServerPluginUsageReporting`, it has been automatically enabled by the existence of the `APOLLO_KEY` environment variable. The real issue here is that I'm using an invalid token. The error message should inform you that you can either disable `ApolloServerPluginUsageReporting` _or_ you can use a valid, graph scoped token.

**Comment by glasser** [comment] 2020-12-18 18:14
haha I told you to file this but, closed as duplicate of #4640

**Closed by glasser** 2020-12-18 18:14 UTC
Labels: :pear: error-handling, ⛲️ feature, 📡 schema-reporting
