### ISSUE TITLE
I cannot get the new data by graphql

### ISSUE THREAD

**Issue by fakership** [apollographql/apollo-server#2338] opened 2019-02-19 07:32 UTC
apollo-server, database: mysql,
when i update a row, then select, i cannot get the new data;
but, if i use rest api, i can get it

**Comment by marcellobarile** [comment] 2019-02-19 07:36
hi @fakership, is actually hard to help you without further details nor a snippet of code that reproduces the issue you are experiencing.

**Comment by fakership** [comment] 2019-02-19 07:41
`
User.update({ deleted: 1 }, { where: { id: 123 } });   // deleted: 0 -> 1
`
`
User.findById(123)  // { deleted: 0 }   !!! error
`

**Comment by fakership** [comment] 2019-02-19 08:28
I don't konw the ID cache whether affect the result or not

**Comment by marcellobarile** [comment] 2019-02-19 08:52
as far as I know, that's not something out of the box on Apollo Server. If you think to experience issues with cache, that would involve the client rather than the server.

**Comment by borisowsky** [comment] 2019-03-04 17:40
Functions calls might be asynchronous in this situation, try to use it synchronous way, for example:
```js
(async function() {
  await User.update({ deleted: 1 }, { where: { id: 123 } });
  await User.findById(123);
})()
```

**Comment by martijnwalraven** [comment] 2019-07-08 20:59
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!

**Closed by martijnwalraven** 2019-07-08 20:59 UTC
