### ISSUE TITLE
Variables in nested Queries are dropped

### ISSUE THREAD

**Issue by tspecht** [apollographql/apollo-server#712] opened 2017-12-13 17:43 UTC
Hey!

I recently started using `apollo-server` and am running into an issue where variables sent with a query that are supposed to be used in a nested object are dropped / changed to `undefined`. The issue looks quite similar to https://github.com/apollographql/apollo-client/issues/620 actually!

My object:
```
export const MyObjectType = new GraphQLObjectType({
  name: "MyObject",
  fields: () => ({
    uuid: {
      type: new GraphQLNonNull(GraphQLString),
      description: "The UUID of the Object"
    },
    nestedField: {
      type: SomeOtherType,
      args: {
        page_size: {
          type: GraphQLInt,
          description: "How many nested objects should be fetched."
        },
        page: {
          type: GraphQLInt,
          description: "The page of objects to fetch."
        }
      }
    }
  })
});
```

I'm trying to send the following query:
```
query MyQuery($objectId: String!, $page: Int!) {
   object(uuid: $objectId) {
      nestedField(page_size: 50, page: $page {
         ... something
      }
   }
}
```

I'm now executing the following query (taken from the `Network` tab in Chrome to make sure I'm not messing anything up!):
```
{query
:
"query MyQuery($objectId: String!, $page: Int!) {↵  object(uuid: $objectId) {↵    nestedField(page_size: 50, page: $page) {↵      ...some stuff in here      }  }}",
variables
:
{objectId: "9e8285f0e2d945808e11d56a9aeaa853", page: 1}
}
```

The response now however looks like this:
```
{"data":{"object":null},"errors":[{"error":{"message":"Argument \"page\" has invalid value undefined.\nExpected type \"Int\", found undefined.","locations":[{"line":2,"column":3}],"path":["object"]}}]}
```

Any idea how I could resolve this?

Using `apollo-server-express` 1.2.0

**Comment by tspecht** [comment] 2018-01-08 16:07
Any idea on this one?

**Comment by abernix** [comment] 2019-02-19 14:03
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved by the major changes in Apollo Server 2.x.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-02-19 14:03 UTC
