### ISSUE TITLE
GraphQL Input Object parsed differently when Query Variable is used

### ISSUE THREAD

**Issue by arizonatribe** [apollographql/apollo-server#3803] opened 2020-02-17 23:04 UTC
Hi there.

My team and I have been scratching our heads on this one for awhile and (mostly) blaming Firebase (hard not to sometimes). But today we observed something that shows a clear difference in how GraphQL Input Objects are parsed in an Apollo GraphQL resolver depending on whether Query Variables are used or not.

I put a full description and screenshots with an easy app to clone and run at the [github URL](https://github.com/arizonatribe/apollo-graphql-input-object-bug) below.

Thanks.

---

__package__: It's hard to tell which package is responsible, but searching through the Apollo code packages for instances of `Object.create(null)` shows most all of the hits in `apollo-server`. It's possible the underlying cause is in one of the core or utils packages though.

__expected behavior__: Setting an Input Object via Query Variables behaves the _same_ as if are manually entering all those fields in the Input Object portion of the GraphQL query/mutation (without query variable interpolation).

__actual behavior__: Manually setting the fields in an Input Object (without using a query variable) causes the Input Object to be treated like a dictionary (ie `Object.create(null)`) where _all_ Object prototype methods used on it throw an error

__reproduction__: https://github.com/arizonatribe/apollo-graphql-input-object-bug

---

Works when you build the query's Input Object by using a query variable:

![Works when using Query variables](https://raw.githubusercontent.com/arizonatribe/apollo-graphql-input-object-bug/master/query-variable.png)

Does _not_ work when you build the query's Input Object is without using any query variables:

![Does NOT work when Input Object is built without Query variables](https://raw.githubusercontent.com/arizonatribe/apollo-graphql-input-object-bug/master/manually-typed-in.png)

**Comment by arizonatribe** [comment] 2020-04-09 23:29
Any ❤️ on this? How about a label 🥺

**Comment by arizonatribe** [comment] 2020-04-09 23:43
That linked issue isn't related. The temporary solution would work for clients making requests to the GraphQL server _if_ the Apollo code wasn't reconverting it into a hashmap (ie something that results from `Object.create(null)` ). Anyway, we already have a temporary solution of using query variables.

The issue is that _somewhere_ in the absolutely enormous apollo server codebase GraphQL input objects are being treated differently if they come through query variables than if they are baked into the mutation (in-line).

**Comment by goloroden** [comment] 2020-07-08 05:31
We have the very same problem in the GraphQL API of our backend framework [wolkenkit](https://www.github.com/thenativeweb/wolkenkit). 
What makes me wonder is that this issue is pretty obvious as you stumble upon this behavior by just playing around and trying things out in the integrated playground - but it gers very little attention, at least it seems so.

**Comment by goloroden** [comment] 2020-07-08 05:34
PS: A simple workaround is to JSON.stringify and JSON.parse the questionable object in the resolver function.

**Comment by robross0606** [comment] 2022-06-23 14:22
We just hit this problem as well.  It is really insidious because it creates a whole new dimension to test variability and coverage.  Input objects not being of `object` prototype can cause all sorts of ripple effects since it won't even convert to string automatically.

**Comment by robross0606** [comment] 2022-06-23 14:24
> PS: A simple workaround is to JSON.stringify and JSON.parse the questionable object in the resolver function.

This is not at all a "simple workaround".  For starters, one may have hundreds of mutations in a microservices environment.  That is also potentially a pretty decent performance hit.

**Comment by goloroden** [comment] 2022-06-23 14:26
> This is not at all a "simple workaround".  […] That is also potentially a pretty decent performance hit.

That's why I wrote "simple", not "perfect" or "performant" or "efficient" or anything like that.

It's a *workaround* (which, by definition, means that it's deficient).

**Comment by robross0606** [comment] 2022-06-23 14:28
It is definitely "a" workaround. But I wonder if there's at least a more easily applicable way to handle this like with a custom Apollo plugin.

**Comment by goloroden** [comment] 2022-06-23 14:30
> This is not at all a "simple workaround".
> […]
> It is definitely "a" workaround.

However 😉

I'd also like to see a better solution, but IMHO this is something which is already broken by design.

**Comment by robross0606** [comment] 2022-06-23 15:06
This is also extra nasty because input can be on any field at all anywhere in the schema.  Not just in mutations and not just at the top level.  That means you need to protect against it on resolution of any field input where you're accepting an object.  😫

**Comment by robross0606** [comment] 2022-06-26 18:00
I _was_ able to create an Apollo plugin that handles this.  However, we do have some performance concerns.

**Comment by glasser** [comment] 2022-07-08 05:47
I believe this is part of the underlying graphql-js library rather than Apollo Server. [Here](https://github.com/graphql/graphql-js/blob/ffe37cb7f501e65e445c30764a1b34f659562756/src/utilities/valueFromAST.ts#L110) is where the AST representation of an input object is converted into a value, and you can see that it does indeed start with `Object.create(null)`.  On the other hand, variable values come through [this function](https://github.com/graphql/graphql-js/blob/ffe37cb7f501e65e445c30764a1b34f659562756/src/utilities/coerceInputValue.ts#L98) instead, which starts with `{}`.  I'm not sure which is better but it is strange that they are different.  But the fix for this definitely belongs in https://github.com/graphql/graphql-js not this repo.

**Closed by glasser** 2022-07-08 05:47 UTC

**Comment by robross0606** [comment] 2022-07-08 09:39
Wouldn’t you open a ticket with them if this is impacting your project instead of just closing and making someone else do it?  This is sorta just an “NMFP” response.

**Comment by glasser** [comment] 2022-07-08 17:45
I mean, yes, it it literally is not our problem.  I think folks who have run into this problem and are finding it a direct challenge to their work are best equipped to file an issue explaining why it is a problem, rather than us as a third party.

**Comment by robross0606** [comment] 2022-07-08 17:56
This appears to be referenced by `graphql-js` already: https://github.com/graphql/graphql-js/pull/2994#issuecomment-809360023

**Comment by glasser** [comment] 2022-07-08 18:35
I'm sorry that putting time into tracking down the precise source of an issue in code I've never read in a project I don't maintain does not make you happy. Good luck!

**Comment by robross0606** [comment] 2022-07-08 18:54
@glasser, I appreciate you adding info on the other ticket as putting some Apollo weight behind the issue may help.  However, the general attitude isn't appreciated much.  Sarcasm doesn't help and Apollo _would_ need to accept and integrate the fix from `graphql-js` if they supply one.  I'm not sure how you can escape at least that level of ownership on the problem here.  Therefore, I don't see how you can justify simply closing this issue.  It may be "unplanned" but it is still a known issue.

**Comment by glasser** [comment] 2022-07-08 19:20
We would not need to integrate any fix. You would merely need to upgrade the version of graphql-js that you install yourself (it's a peer dependency).

I suppose we could make a copy of every single issue in https://github.com/nodejs/node in this repository as well, since all of them may affect people who run Apollo Server on Node, but I don't think that would help.

**Comment by robross0606** [comment] 2022-07-08 19:23
Okay, now I'm baffled.  We've been using `apollo-server` for _years_ without installing `graphql-js`.  Turns out this isn't installed at all in our project as reported by `npm ls` and yet our project works fine.  `graphql-js` is also not reported as a missing peer dependency.  Where is this listed as a dependency (in any way) of `apollo-server`?

**Comment by robross0606** [comment] 2022-07-08 19:26
> I suppose we could make a copy of every single issue in https://github.com/nodejs/node in this repository as well, since all of them may affect people who run Apollo Server on Node, but I don't think that would help.

@glasser, again, the sarcasm is 100% unhelpful and counter-productive.  If you can't have a civilized disagreement with someone, then please stop replying.

**Comment by glasser** [comment] 2022-07-08 19:26
Well, it's a bit confusing: the npm package is actually confusingly called `graphql` although its GitHub repository is `graphql-js`. I usually refer to it as graphql-js to avoid ambiguity (vs, say, the overall concept of GraphQL).

**Comment by robross0606** [comment] 2022-07-08 19:28
> Well, it's a bit confusing: the npm package is actually confusingly called `graphql` although its GitHub repository is `graphql-js`. I usually refer to it as graphql-js to avoid ambiguity (vs, say, the overall concept of GraphQL).

Ahhh... that would explain it.  We certainly have _that_ package.  I didn't realize those were the same thing.

**Comment by robross0606** [comment] 2022-07-08 19:31
In case someone comes here wondering, the actual fix for this is being tracked under: https://github.com/graphql/graphql-js/issues/2664

**Comment by arizonatribe** [comment] 2022-07-08 22:33
Wow. What an ass. But at least we finally have a reply, lol

**Comment by TheBryceIsRight** [comment] 2022-11-09 21:32
This is what one of the rudest customer support exchanges I've ever seen on GitHub. @glasser Maybe consider how you talk to people
