### ISSUE TITLE
throwing custom error inside a callback method doesn't get passed to the client instead nodejs crashes

### ISSUE THREAD

**Issue by shreyansh-zazz** [apollographql/apollo-server#4315] opened 2020-06-26 10:53 UTC
The below code is inside a resolver. In the following code, I am trying to find an entry in database and if it exists I have to throw an error.

![image](https://user-images.githubusercontent.com/21006490/85849498-af437f80-b7c8-11ea-8239-fce38d258f33.png)

The `HandleError` method is as following

![image](https://user-images.githubusercontent.com/21006490/85849628-eb76e000-b7c8-11ea-9497-1a880ea9bf08.png)

## CURRENT BEHAVIOR
The nodejs runtime app is crashing due to `throw new ApolloError(...)`

## EXPECTED BEHAVIOR: 
Here the expected behavior  should be that the client receives the error in the graphql response like below

![image](https://user-images.githubusercontent.com/21006490/85849760-3133a880-b7c9-11ea-8269-3048d35908e8.png)

**Comment by xanderdeseyn** [comment] 2022-02-07 17:55
2 years later and I'm still running into this issue. Did you find a solution?

**Comment by shreyansh-zazz** [comment] 2022-02-07 18:48
Nope

**Comment by glasser** [comment] 2022-02-07 20:07
This does seem like a problem and I'd love to help with it @xanderdeseyn. (It was filed during an unfortunate period where Apollo Server wasn't being actively maintained.) However, there's not nearly enough detail here to help figure out what's going on. For example, it doesn't show what the crash actually looks like, and it's just a few code snippets rather than a full reproducible app.

I'm going to close this because it doesn't have enough detail, but I'd be happy to reopen it if a full reproduction is provided. Useful reproductions require the core team to do nothing creative to see the problem; typically they start with `git clone` or a reference to a codesandbox.io sandbox.

**Closed by glasser** 2022-02-07 20:07 UTC
Labels: :pear: error-handling
