### ISSUE TITLE
mutations are not working when put through Geteway

### ISSUE THREAD

**Issue by squarewave24** [apollographql/apollo-server#4199] opened 2020-06-03 13:45 UTC
I am using Apollo Geteway with my react app connecting to python api's using graphene. 

all queries work fine, but when trying to use a mutation i get this generic error 

the query works when  i paste it into the endpoint graphql playground, but not from apollo geteway playground :( 

query:
```
mutation review{
  review(my_date:"2020-06-02")
  {
    success
  }
}
```

error: 
```

"error": {
    "errors": [
      {
        "message": "Schema is not configured for mutations.",
        "locations": [
          {
            "line": 1,
            "column": 1
          }
        ],
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "GraphQLError: Schema is not configured for mutations.",
              "    at Object.getOperationRootType (/Users/rafal.buch/dev/ground-control/node_modules/graphql/utilities/getOperationRootType.js:28:13)",
              "    at Object.buildQueryPlan (/Users/rafal.buch/dev/ground-control/node_modules/@apollo/gateway/src/buildQueryPlan.ts:80:20)",
              "    at Object.ApolloGateway.executor (/Users/rafal.buch/dev/ground-control/node_modules/@apollo/gateway/src/index.ts:659:19)",
              "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
            ]

```

versions: 
```
"@apollo/gateway": "^0.16.2",
"apollo-server": "^2.14.1",
"apollo-server-express": "^2.14.1",

graphene==2.1.8
graphene-federation==0.1.0
```

i also tried simplified queries that just return True on server. again work in regular endpoint playground, but not in apollo server geteway 

```
mutation {
  testMutation {
    success
  }
}

mutation testMutation {
  testMutation {
    success
  }
}
```

**Comment by jhampton** [comment] 2020-06-11 20:23
@squarewave24 Can you share a minimal reproduction with a schema please?  I have only found examples of this error when there are mistyped schema entries or queries.

**Comment by glasser** [comment] 2022-10-21 04:40
Going to close this because it doesn't have a reproduction (and also transfer it to the repository where Gateway now lives).

**Closed by glasser** 2022-10-21 04:40 UTC
Labels: ⁉️ question
