### ISSUE TITLE
apollo-server-koa is broken

### ISSUE THREAD

**Issue by droganov** [apollographql/apollo-server#2265] opened 2019-02-02 17:30 UTC
`const { ApolloServer } = require('apollo-server-koa');`

results in. same code and npm config worked a couple of days ago

```
> node lib/koa/server.js

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/se/www/gerlent/gerlent-webpapp/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by mikeshultz** [comment] 2019-02-02 21:52
Related: https://github.com/apollographql/apollo-tooling/issues/962

**Comment by mikeshultz** [comment] 2019-02-03 04:57
@droganov They fixed this, btw.

**Comment by abernix** [comment] 2019-02-04 09:43
Thanks.  Duplicate of #2263.

**Closed by abernix** 2019-02-04 09:43 UTC
