### ISSUE TITLE
willResolveField plugin hook is not triggered (in gateway mode)

### ISSUE THREAD

**Issue by tot-ra** [apollographql/apollo-server#6401] opened 2022-05-06 16:23 UTC
Hey. I'm following [plugin reference](https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference/#willresolvefield) and running a **gateway** from `"apollo-server-core": "3.6.7"`

But when I execute a query, the `willResolveField` hook is never triggered.
<img width="1222" alt="Screenshot 2022-05-06 at 19 03 09" src="https://user-images.githubusercontent.com/445122/167170340-fe25a346-ed1d-4db3-96d2-7c0d823e1f0f.png">

I pretty much copy pasted the use case from the docs, I can see other hooks firing but not this particular one. I'm not sure, 
is it supported to run in gateway mode? Then docs need to say if not.

```javascript
			async executionDidStart() {
				return {
					willResolveField({ source, args, context, info }) {
						const start = process.hrtime.bigint();

						console.log('XXXXXX');
						return (error, result) => {
							const end = process.hrtime.bigint();
							console.log(`Field ${info.parentType.name}.${info.fieldName} took ${end - start}ns`);
							if (error) {
								console.log(`It failed with ${error}`);
							} else {
								console.log(`It returned ${result}`);
							}
						};
					},
				};
			},
```

### Debugging
I did some debugging, at seems to me that 
- `willResolveField` is undefined, so it never gets called
- its undefined because request context is also undefined
- request context is undefined because `executeQueryPlan` never passes context to `execute`

<img width="808" alt="Screenshot 2022-05-06 at 19 13 27" src="https://user-images.githubusercontent.com/445122/167172370-e0ce9e3d-df3b-4983-8464-8db1caead1f9.png">
<img width="899" alt="Screenshot 2022-05-06 at 19 16 23" src="https://user-images.githubusercontent.com/445122/167172377-eae3c6d5-aa1c-4dec-950b-8c26f0920420.png">
<img width="662" alt="Screenshot 2022-05-06 at 19 16 43" src="https://user-images.githubusercontent.com/445122/167172387-8d009360-635c-474d-b9c4-5f36ff14d0fa.png">

**Comment by glasser** [comment] 2022-05-06 16:28
No fields are resolved inside your gateway server, so this instrumentation is not executed.  (If you need to learn things about field execution in your gateway, you need your subgraphs to do that instrumentation and send it back to gateway somehow, like how the inline trace plugin works.)

This works as intended, but I'd be happy to review a doc improvement; docs are found in `docs/source` in this repository.

**Closed by glasser** 2022-05-06 16:28 UTC

**Comment by tot-ra** [comment] 2022-05-07 09:51
@glasser ⬆️ check the new pr :)
