### ISSUE TITLE
Serve GraphiQL without remote assets

### ISSUE THREAD

**Issue by coffeedoughnuts** [apollographql/apollo-server#505] opened 2017-08-14 12:24 UTC
Would it be possible to bundle GraphiQL with the package rather than using remote assets from a CDN? Developers don't always have a network connection, or work behind a restrictive corporate firewall

**Comment by madelinecameron** [comment] 2017-08-15 22:19
Or switch to one that doesn't drop packages. :( 

Currently, graphql.css@0.11.2 has vanished from unpkg

**Comment by stubailo** [comment] 2017-08-16 00:05
Yep, definitely - would love to accept a PR to improve this!

**Comment by luchillo17** [comment] 2017-08-16 04:44
I have an issue with the CDN for `react.min.js`, however if i change the js string to `react.js` it works ok:
![image](https://user-images.githubusercontent.com/9698639/29347652-b5f41a8a-8213-11e7-8b89-7ea330920fd4.png)

**Comment by stubailo** [comment] 2017-08-16 05:01
Ah looks like this is a duplicate of https://github.com/apollographql/apollo-server/issues/295

**Closed by stubailo** 2017-08-16 05:01 UTC
