### ISSUE TITLE
[apollo-gateway] Question about nullability and cross-service joins

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/apollo-server#3839] opened 2020-02-28 19:55 UTC
Hi @trevor-scheer, @jhampton and friends,

Any time the query planner calls another service, there's an additional chance of failure. Consider the following two-service federated graph:

```graphql
type User @key(fields: "id") {
  id: ID!
  name: String!
}
```
```graphql
extend type User @key(fields: "id") {
  id: ID! @external
  reviews: ReviewConnection!
}

type ReviewConnection {
  edges: [ReviewEdge!]!
  nodes: [Review!]!
  pageInfo: PageInfo!
}
```

Because `User.reviews` is a non-nullable ReviewConnection, if the request to the Reviews service fails (due to a network partition or service downtime) the response will fail validation and we won't get any data at all.

```graphql
query UserReviews($id: ID!) {
  user(id: $id) {
    id
    name
    reviews { # returning null here means we won't get `user.id` or `user.name`
      nodes {
        id
        content
      }
   }
}
```

What are your thoughts on making `User.reviews` nullable to better support partial data? It's kind of a shame to leak implementation details into the schema. Are y'all documenting best practices like this anywhere?

Would we possibly want a schema linter that enforces that cross-service data is nullable to allow partial data?

Alternatively, would it be possible to handle failures like this?

```json
{
  "data": {
    "user": {
      "id": "1",
      "name": "Lenny",
      "reviews": {
        "nodes": [],
      }
    }
  },
  "errors": [
    {
      "message": "Error fetching User.reviews: Service is down",
      "path": ["user", "reviews"]
    }
  ]
}
```

I have no idea how you'd do this generically, but maintaining the contract by returning empty data plus an error would be very cool.

**Comment by jodosha** [comment] 2020-04-09 15:53
👍 On this request.

Here's an example of this problem based on https://github.com/apollographql/federation-demo

Steps to reproduce:

  1. Instead of starting the services with `npm run start-services`, open 4 different shell tabs and cd into each of them to manually start each service with `npm start`.
  1. Start the gateway with `npm run start-gateway`
  1. Run a query like the one listed below 👇 
  1. Stop the `inventory` service
  1. Run again the query, you will see `inStock` with `null` values, and an error without `path` node. See https://gist.github.com/jodosha/df091662096a7df4c33f30f378b304da

```graphql
{
  topProducts {
    name
    inStock
  }
}
```

---

I believe that having `path` will help consumers (e.g. UI) to write more robust code, as they can to understand why `inStock` is `null`.

---

Another concerning aspect is the error message:

```
"request to http://localhost:4004/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4004"
```

It leaks sensitive details like the GQL endpoint that it supposed to abstract.

---

Thanks for your consideration.

**Comment by jhampton** [comment] 2020-07-15 17:42
A few follow-up thoughts:

My take here is that the correct behavior is to ensure (in the DOWNSTREAM SERVICE), that responses respect nullability, and that the types in question can optionally return a `union` of the request type or requested type-error.

If the user experience expects a given set of child objects to be available and they’re not, a reasonable pattern would be to hide the related UI.  But if the type is marked non-null, the right answer might be to contact support (because there must be something there in order to complete a task or flow.)
Having a consistent rule applied here might be challenging, but having a general guidance feels achievable:
- Partial data should be returned unless that partial data renders the user’s task unachievable or breaks a business rule, in which case an exception is returned.
- If partial data can be made available, it is the implementing service’s responsibility to ensure a valid result set at all times (in the case of nullability)
- Optionally, a service can choose to provide additional context in the form of a union of the expected type and an expressive error type

So as a graph administrator, I can apply these guidelines, make it a part of schema/code review, and write tests for it.

Thank you for the callout @jodosha on the leaking of error details.  This could be reformatted using the existing Apollo Server hooks: https://github.com/apollographql/apollo-server/blob/570f548b88750a06fbf5f67a4abe78fb0f870ccd/docs/source/data/errors.md#masking-and-logging-errors

I'd like to close this out as an active issue, but please feel free to re-open if this surfaces with better or more-specific patterns and practices from the field.

Thank you!

**Closed by jhampton** 2020-07-15 17:42 UTC
Labels: ⁉️ question, 💬 discussion

**Comment by jodosha** [comment] 2020-11-11 10:08
@jhampton Thanks for the pointer to masking errors, but still there is a bit that is missing IMO: the correlation between the error and the field, ideally with `path` information in error payload.

If you look again at the [output](https://gist.github.com/jodosha/df091662096a7df4c33f30f378b304da), there is no hint for the caller that `inStock` is `null` because of that `INTERNAL_SERVER_ERROR`.

From the caller perspective I don't know if `inStock` is `null` because it's a nullable field or because the service is down and Apollo Gateway implementation happens to return `null`.

I assume that the query planner can associate fields (like `inStock`) to HTTP requests to downstream services, and enrich each `errors` node with a `path` information.

**Comment by kindermax** [comment] 2021-07-06 18:43
I am also concerned about the way gateway handles partial responses if one of the underlying subgraph services are unable to respond. 
In @lennyburdette example, there is only one extending field `reviews: ReviewConnection!` and potentialy it can be made optional, but that is a no-go in my opinion. What if `reviews` service exposes a lot more fields. Are they all have to be declared as optional just to satisfy the case when `reviews` is down for some time ? It does not make sence.

I think it should be a way:
 - to have non-optional fields on subgraph service 
 - for a gateway to return as much queried data as possible and for the rest of fields just provide a sensible errors.

This will make a whole federated gateway way more fault tolerant.
