### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::4000

### ISSUE THREAD

**Issue by sesteva** [apollographql/apollo-server#3310] opened 2019-09-18 22:19 UTC
### This bug report should include:

Short description:
Expected: the previous instance to gracefully shut down and a new one to start up
Actual: previous instance is still running
Versions: 
```
    "apollo-datasource": "^0.6.3",
    "apollo-datasource-rest": "^0.6.4",
    "apollo-server": "^2.9.3",
    "datasource-sql": "^0.2.0",
    "date-fns": "^2.1.0",
    "deep-has": "^1.0.0",
    "graphql": "^14.5.6",
    "https-proxy-agent": "^2.2.2",
    "oracledb": "^4.0.1"
```

Error 

```
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at /Users/Projects/api-hub-graph/node_modules/apollo-server/dist/index.js:76
:28
    at new Promise (<anonymous>)
    at ApolloServer.<anonymous> (/Users/Projects/api-hub-graph/node_modules/apol
lo-server/dist/index.js:74:19)
    at Generator.next (<anonymous>)
    at /Users/Projects/api-hub-graph/node_modules/apollo-server/dist/index.js:8:
71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Projects/api-hub-graph/node_modules/apollo-server/dist/
index.js:4:12)
Emitted 'error' event at:
    at Server.emit (events.js:200:13)
    at emitErrorNT (net.js:1253:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 4000
}
```

Server.js

```
const { ApolloServer, gql } = require("apollo-server");
const dataSources = require("./datasources");
const typeDefs = require("./schema");
const resolvers = require("./resolvers");
const enhancedContext = require("./context");
const mocks = require("./mocks");

const formatError = error => {
  return error;
};

const formatResponse = response => {
  return response;
};

const Query = gql`
  type Query {
    _empty: String
  }
`;
console.log("Mocking Schema: ", process.env.MOCK_SCHEMA === "true");
console.log("Mocking Db: ", process.env.MOCK_DB === "true");
const server = new ApolloServer({
  typeDefs: [Query, ...typeDefs],
  resolvers,
  dataSources,
  formatError,
  formatResponse,
  context: enhancedContext,
  mocks,
  mockEntireSchema: process.env.MOCK_SCHEMA === "true"
});
```

**Comment by sesteva** [comment] 2019-09-19 02:02
I've been able to identify this only happens when a connection to the DB which is initialized in context timesout. 
Any ideas on why would that prevent the server to gracefully shutdown. ?

**Comment by abernix** [comment] 2019-09-19 10:50
This doesn't seem to be a bug with Apollo Server.  The general rules which apply to Node.js still apply when using Apollo Server.  If something is keeping the event loop active, then it will not terminate.

I'll close this because it doesn't appear to be anything we can resolve.  If you have any other questions or you're still having problems with this, feel free to ask in the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo), though I'd recommend bringing a runnable minimal reproduction for discussion to facilitate helping out!

In general though, I'd suggest gaining an understanding what might be keeping the event loop active — e.g. timers, network sockets, etc.

**Closed by abernix** 2019-09-19 10:50 UTC
