### ISSUE TITLE
RESTDataSource caching 4xx,5xx responses

### ISSUE THREAD

**Issue by uarsovic** [apollographql/apollo-server#1510] opened 2018-08-09 12:10 UTC
When you set the cacheOptions{ttl: someValue} in the get request and the request returns 4xx or 5xx response it will be cached in InMemory, Redis etc. This should not happen.

**Comment by martijnwalraven** [comment] 2018-08-10 11:09
Duplicate of #1481.

**Closed by martijnwalraven** 2018-08-10 11:09 UTC
Labels: bug, nug
