### ISSUE TITLE
Typescript compile errors apollo-server-lambda

### ISSUE THREAD

**Issue by solemidas** [apollographql/apollo-server#653] opened 2017-10-31 03:06 UTC
I am trying to get started with integrating graphql with AWS lambda, I am using typescript and from what I understand apollo is also using typescript. The issue is at compile time when I try to serve it locally using serverless-offline
**Intended outcome**
I was hoping it would compile.
**Actual outcome**
`ERROR in ./node_modules/apollo-server-lambda/dist/index.js
Module not found: Error: Can't resolve './lambdaApollo' in '/home/midas/Desktop/projects/nodejs/property-messenger-graphql/node_modules/apollo-server-lambda/dist'
 @ ./node_modules/apollo-server-lambda/dist/index.js 3:21-46
 @ ./src/lambda/handler.ts

ERROR in ./node_modules/graphql-tools/dist/index.js
Module not found: Error: Can't resolve './mock' in '/home/midas/Desktop/projects/nodejs/property-messenger-graphql/node_modules/graphql-tools/dist'
 @ ./node_modules/graphql-tools/dist/index.js 7:9-26
 @ ./src/lambda/handler.ts

ERROR in ./node_modules/graphql-tools/dist/index.js
Module not found: Error: Can't resolve './schemaGenerator' in '/home/midas/Desktop/projects/nodejs/property-messenger-graphql/node_modules/graphql-tools/dist'
 @ ./node_modules/graphql-tools/dist/index.js 6:9-37
 @ ./src/lambda/handler.ts

ERROR in ./node_modules/graphql-tools/dist/index.js
Module not found: Error: Can't resolve './stitching' in '/home/midas/Desktop/projects/nodejs/property-messenger-graphql/node_modules/graphql-tools/dist'
 @ ./node_modules/graphql-tools/dist/index.js 8:9-31
 @ ./src/lambda/handler.ts

ERROR in [at-loader] ./node_modules/@types/graphql/subscription/subscribe.d.ts:17:12
    TS2304: Cannot find name 'AsyncIterator'.

ERROR in [at-loader] ./node_modules/@types/graphql/subscription/subscribe.d.ts:29:12
    TS2304: Cannot find name 'AsyncIterable'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:75:13
    TS2403: Subsequent variable declarations must have the same type.  Variable 'process' must be of type 'any', but here has type 'Process'.

ERROR in [at-loader] ./node_modules/apollo-server-lambda/dist/lambdaApollo.d.ts:1:25
    TS2307: Cannot find module 'aws-lambda'.

ERROR in [at-loader] ./node_modules/graphql-tools/dist/stitching/introspectSchema.d.ts:2:28
    TS2307: Cannot find module 'apollo-link'.

ERROR in [at-loader] ./node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.d.ts:1:28
    TS2307: Cannot find module 'apollo-link'.
`

**Reproduction**

` tsconfig.json
{
    "compilerOptions": {
      "module": "es6", 
      "target": "es6", 
      "allowSyntheticDefaultImports": true,
      "baseUrl": ".", 
      "paths": {
        "gql/*": ["src/graphql/*"],
        "db/*": ["src/db/*"],
        "lambda/*": ["src/lambda/*"]
      },
      "outDir": "ts-build", 
      "strict": true,
      "moduleResolution": "node"
    },
    "exclude": [
      "node_modules"
    ]
  }

.babelrc

{
    "presets": ["es2015"]
}

webpack.config.js
// const externals = require('webpack-node-externals');
const webpack = require('webpack');
const slsw = require('serverless-webpack');
const path = require('path');
module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  module: {
    loaders: [
      { 
        test: /\.ts?$/,
        loaders: ['babel-loader', 'awesome-typescript-loader'],
        include: __dirname,
      }
    ]
  },
  resolve: {
    extensions: ['.ts'],
    alias: {
      gql: path.resolve('src/graphql'),
      db: path.resolve('src/db'),
      lambda: path.resolve('src/lambda'),
    }
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      comments: false,
      compress: {
        unused: true,
        dead_code: true,
        warnings: false,
        drop_debugger: true,
        conditionals: true,
        evaluate: true,
        sequences: true,
        booleans: true,
      },
    }),
  ],
};
`

**Comment by schickling** [comment] 2017-11-12 20:40
Running into the same error.

**Comment by sandangel** [comment] 2017-11-22 03:06
can anyone provide a full example with typescript and apollo-server-lambda include webpack.config.js and tsconfig.json?

**Comment by juliosampaio** [comment] 2018-07-01 21:46
Same problem here, no solutions yet?

**Comment by abernix** [comment] 2018-09-24 10:17
We believe this is fixed in more recent versions of Apollo Server since `@types/aws-lambda` are now properly dependended upon and included by the TypeScript (`tsc`).

If you’re still experiencing this problem, please open a new issue with a reproduction and we’ll be happy to take a look again.  Thanks!

**Closed by abernix** 2018-09-24 10:17 UTC
