### ISSUE TITLE
graphql-server-micro with graphiql issue - "Can't set headers after they are sent"

### ISSUE THREAD

**Issue by bwlt** [apollographql/apollo-server#449] opened 2017-07-02 18:34 UTC
The example [on the README.md](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-micro/README.md) does not work.
When calling `GET http://localhost:3000/graphiql` it responds 404 instead of serving the graphiql html app.
On console output there is an error message:
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at GraphiQL.resolveGraphiQLString.then.res.statusCode (.../node_modules/graphql-server-micro/src/microApollo.ts:67:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

I think that on [this line](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-micro/src/microApollo.ts#L66) the request handler is not waiting for 'resolveGraphiQLString'; So the request pass to the next handler (the 404 handler on the README example).

Later, when 'resolveGraphiQLString' resolves it try to respond but the response was already sent.

The issue is very similar with this: https://github.com/apollographql/graphql-server/pull/447

**Comment by jimthedev** [comment] 2017-07-07 18:54
I am using them together right now and I ran across this. You can work around it by adding a single 200 route. I didn't investigate further but I added this to my routes and voila everything worked.

```
get("/noop", (req, res) => {
  return send(res, 200, "");
}),
```

**Comment by jimthedev** [comment] 2017-07-07 19:04
Docs PR change submitted.

**Comment by bwlt** [comment] 2017-07-10 08:18
I'm not sure that the PR is the correct resolution of the problem. It fix only the README example with a workaround :(

**Comment by freiksenet** [comment] 2017-07-10 08:48
I'll reopen the issue, it was auto-closed. PRs to fix it properly are very welcome.

**Comment by farzd** [comment] 2017-07-18 17:59
i'm getting this as well

**Comment by frederikhors** [comment] 2018-08-13 17:01
The problem I think is still there: https://github.com/apollographql/apollo-server/issues/1523

**Comment by abernix** [comment] 2019-02-19 14:05
The most recent comment on this issue is different than the original issue which was reported.

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already, particularly since the `micro` implementation is now built with Apollo Server and now at `apollo-server-micro@2.4.2`.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-02-19 14:05 UTC
