### ISSUE TITLE
Question: Arrow function resolvers much slower than regular functions

### ISSUE THREAD

**Issue by scf4** [apollographql/apollo-server#499] opened 2017-08-09 03:02 UTC
I'm trying to diagnose why I'm getting such terrible performance with my server. 

I noticed even resolvers as simple as this are taking several milliseconds to resolve:

<img width="545" alt="screen shot 2017-08-09 at 03 58 22" src="https://user-images.githubusercontent.com/768234/29103353-0311928c-7cb7-11e7-8201-d354e4be50b0.png">

apollo optics:

<img width="413" alt="screen shot 2017-08-09 at 03 59 02" src="https://user-images.githubusercontent.com/768234/29103371-207eebe4-7cb7-11e7-92b9-59c417601bc1.png">

but then if I change the the resolver to this:

<img width="585" alt="screen shot 2017-08-09 at 04 00 33" src="https://user-images.githubusercontent.com/768234/29103416-5456d21a-7cb7-11e7-95eb-8c59c6ffa06e.png">

then it's in the microseconds as it should be:

<img width="315" alt="screen shot 2017-08-09 at 04 01 13" src="https://user-images.githubusercontent.com/768234/29103445-78ed9adc-7cb7-11e7-9949-5e2f5befea3f.png">

What's happening here?

**Comment by stubailo** [comment] 2017-08-16 13:27
> apparently, this deref costs 6 more ms.

A memory reference costing 6 ms would be pretty insane - it should be micro or nano seconds. There might be something else at play here...

@scf4 would you mind making a small app with two resolvers, one with a function declaration and one with an arrow, and comparing the two?

**Comment by stubailo** [comment] 2017-08-16 13:28
(Labeling as question because it's not an Apollo Server specific issue)

**Comment by abernix** [comment] 2018-09-24 10:43
Closing due to lack of reproduction, but please do re-open a new issue if you find time to put one together.  Thanks!

**Closed by abernix** 2018-09-24 10:43 UTC
Labels: question
