### ISSUE TITLE
Enable Caching only for subfield not for parent query

### ISSUE THREAD

**Issue by jitenderchand** [apollographql/apollo-server#4174] opened 2020-05-28 17:01 UTC
I have a requirement where the parent query doesn't need to be cached as it is frequently changes but the subfield which is resolved by another API needs to be cached. The parent query is list of  active feeds and subfield hold the detail of feed which often doest not change

```
type Feed @cacheControl(maxAge: 0){
        id: ID!
        name: String!
        feed: FeedType @cacheControl(maxAge: 100000)
}

```

Apollo server configuration

```
const server = new ApolloServer({
        typeDefs,
        resolvers,
        cacheControl: {
            defaultMaxAge: 60000,
            stripFormattedExtensions: false
        },
        plugins: [responseCachePlugin()],
        cache: new RedisCache({
            connectTimeout: 5000,
            reconnectOnError: function (err: Error) {
                console.log('Reconnect on error', err)
                var targetError = 'READONLY'
                if (err.message.slice(0, targetError.length) === targetError) {
                    // Only reconnect when the error starts with "READONLY"
                    return true
                }
            },
            host: 'redis',
            port: 6379,
            retryStrategy: function(times) {
                console.error("Redis Retry", times);
                if (times >= 3) {
                    return undefined;
                }
                return Math.min(times * 50, 2000);
            },
            // Options are passed through to the Redis client
        }),
        context: async ({ req }: ExpressContext) => {
            const uid = req.header('uid') ?? undefined;
            return { uid };
        },
        tracing: isDevelopmentEnvironment,
        mocks: config.get('enableMockResponse') && isDevelopmentEnvironment ? mocks : undefined,
        mockEntireSchema: config.get('enableMockResponse') && isDevelopmentEnvironment ? false : undefined,
        formatError: (error: GraphQLError): GraphQLFormattedError<Record<string, any>> => {
            logger.error(error);

            if (error instanceof ValidationError) {
                return {
                    message: error.message,
                    errorCode: '400',
                    timestamp: new Date().getTime(),
                    path: '/hyke-hff/graphql',
                    originalError: config.get('debug') ? error : undefined
                } as any;
            } else {
                return {
                    message: error.message,
                    errorCode: '500',
                    timestamp: new Date().getTime(),
                    path: '/hyke-hff/graphql',
                    originalError: config.get('debug') ? error : undefined
                } as any;
            }
        },
        dataSources: () => {
            return {
                feed: new FeedRepository(
                    `${config.get('services.baseURL')}${config.get('services.feed.endpoint')}`,
                ),
            };
        }
    });
```

resolver setup

```
const resolvers = {
    Feed: {
        feed: async (obj: any, args: any, { dataSources }: any, { cacheControl }: any): Promise<any> => {
            const response = await (dataSources.feed as FeedRepository).retriveFeedDetail(obj.id);
            return response.data
        },
    },
    Query: {
        feedStore: async (
            obj: any,
            { id }: { id: string;},
            { dataSources }: any
        ): Promise<any> => {
            // get pmids by inventoryLocationCode
            const response = await (dataSources.feed as FeedRepository).retriveFeed(id);
            
            return {
                items: response.data,
            };
        }
    }
};
```

```
"apollo-datasource-rest": "^0.8.1",
"apollo-server-cache-redis": "^1.2.1",
"apollo-server-express": "^2.12.0",
"apollo-server-plugin-response-cache": "^0.5.2",
```

**Comment by andreujuanc** [comment] 2021-06-17 12:12
I wanted to do the same, but I haven't figure out how besides not using apollo's cache but instead caching it in the resolver instead, which is MEH. 

Basically I have a query like this

```gql
type A @cacheControl(maxAge: 0){
        id: ID!
        thisChangesALot: String!
        link: B @cacheControl(maxAge: 100000) // I wanted to cache this since it comes from another system and it's quite slow.
}
```

It'd be really classy to use the apollo cache, but looks like I would have to roll my own. It's a bit sad that the library decides the caching strategy like if I'm not old enough to do it myself. ಠಿ_ಠ

**Comment by glasser** [comment] 2021-06-22 14:29
Yep, we'd love to eventually extend the full response cache into a partial response cache, but it's a much more complex project.

**Comment by glasser** [comment] 2022-10-21 04:38
Duplicate of #4042.

**Closed by glasser** 2022-10-21 04:38 UTC
