### ISSUE TITLE
Not implemented interface error

### ISSUE THREAD

**Issue by flyhigh-hifi** [apollographql/apollo-server#2080] opened 2018-12-10 16:01 UTC
Apollo server doesn't produce errors when schema has interfaces which are not implemented yet. That causes graphql-playground and apollo cli utility to crash without any errors: in console of graphql-playground there's an js error when trying to run loop on implementations: null property.

**Comment by martijnwalraven** [comment] 2019-07-08 21:49
Is this still an issue in recent versions of Apollo Server and `graphql-js`? I would expect schema validation to catch this.

**Comment by abernix** [comment] 2019-07-16 17:29
Happy to re-open if this has continued to be problematic but I'll close it for now since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-07-16 17:29 UTC
Labels: :wilted_flower: needs-reproduction
