### ISSUE TITLE
How to access a specific collection in MongoDB database?

### ISSUE THREAD

**Issue by sheshit** [apollographql/apollo-server#1916] opened 2018-11-03 07:13 UTC
I normally access a collection with the mongoose model. But I have a database in which there is a collection for each photo added to the application. In that case I have a unique name to each photo added to my application. How do I use mongoose to fetch data from a specific collection?

 const db = mongoose.connect(
        "mongodb+srv://<admin>:<passsword>@cluster0-53qcr.mongodb.net/Comments?",
        { useNewUrlParser: true }
      );
Comments = mongoose.connection.db.collection(`${post_id}`);

I used this code to fetch data. But it shows an error saying cannot read property of undefined.But the collection exists when I check the database.

**Comment by martijnwalraven** [comment] 2019-07-08 20:29
Closing this because the issue is not related to Apollo or GraphQL.

**Closed by martijnwalraven** 2019-07-08 20:29 UTC
