### ISSUE TITLE
Different errors and error codes in dev & production

### ISSUE THREAD

**Issue by SachaG** [apollographql/apollo-server#1541] opened 2018-08-16 07:00 UTC
I'm running into a weird issue. The same exact query gives me different errors in different environments. 

In dev, I get a full error message with a `200` return code:

```
Error: GraphQL error: Variable "$data" got invalid value {"photos":[],"floorPlans":[]}.
In field "name_intl": Expected "[JSON]!", found null.
In field "propertyType": Expected "String!", found null.
In field "description_intl": Expected "[JSON]!", found null.
```

While in production I only get:

```
Error: Network error: Network request failed with status 400
```

With a `400` return code. 

The weird part is that the response body in the Network tab is exactly the same in both environments. Is there something that could make my server throw a 400 error and my local environment a 200 error?

I'm using apollo-server-express v1.3.6 btw.

**Comment by jasonpaulos** [comment] 2019-07-08 20:39
Hi @SachaG, thanks for logging this concern originally. I'm going to close this issue since It hasn't received a lot of feedback or traction since it was first opened, and we've changed substantial portions of Apollo Server since then, including a major bump to support Apollo Server 2.x.

If this is still a problem, feel free to ping me back and I (or someone) will be happy to re-open it. Thanks again!

**Closed by jasonpaulos** 2019-07-08 20:39 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by glasser** [comment] 2022-12-07 22:00
I would be surprised if this issue still existed in Apollo Server 4. If you believe it does, can you share a complete reproduction recipe where no creativity is required on our part to observe the problem?
