### ISSUE TITLE
ApolloServer instance takes 8sec to load on Node.js boot | IMPORTANT!

### ISSUE THREAD

**Issue by georgekrax** [apollographql/apollo-server#6199] opened 2022-03-11 23:23 UTC
### Description & Actual behavior
I have a **Node.js** powered by Express.js backend server, built on TypeScript. I use SWC to compile the `.ts` files, and it works gracefully in a few milliseconds. I also use `nodemon` for restarting the Node.js server on change, which runs the script: `node build/index.js`. However, even if use simply in **cmd** (without nodemon) the script `node build/index.js`, Node.js takes **10 seconds** to boot -initialstartup. 

So, I started commenting out lines of code of my `src/index.ts` file, and saw that if I remove the `new ApolloServer()` instance, the initial boot time is **2 seconds**! I do not know why is this happening, and it is really frustrating.

I build my schema with the `nexus` package from Prisma, and it is large due to my application size, but not too big and complex.

### Apollo Version
I use the `apollo-server-core` & `apollo-server-express` packages. Here are their version:
```json
"apollo-server-core": "^3.6.4",
"apollo-server-express": "^3.6.4"
```
*This issue has been bothering me for months! So, there is not a version where this was not happening. 

### Expected behavior

I was expecting to have a maximum **2 seconds** initial boot/startup time. It is really upsetting, because there are other tools (like Next.js) that restart and run in milliseconds. If anyone knows how Next.js works for development server compilation, I would appreciate your comment and advice. 

### Code - Reproduction
Here is my `ApolloServer` instance code:
```js
const apolloServer = new ApolloServer({
    schema: schema as any,
    plugins: [ApolloServerPluginLandingPageGraphQLPlayground()]
  });
```

*I have removed `ApolloServerPluginLandingPageGraphQLPlayground()`, and still the issue remains.

I appreciate every help and comment! 
Thanks in advance

**Comment by glasser** [comment] 2022-03-12 01:09
That does seem very surprising! Some thoughts/double-checks:

- It's `new ApolloServer` that's slow, not `await ApolloServer.start()`?
- It's definitely *startup* that's slow, not *shutdown*? If you were saying that nodemon was slow then I might suggest that the issue is shutdown waiting for existing connections to drain rather than startup. But you're saying this occurs with single server startup, not restart? (And doesn't look like you're using [the recommended drain code](https://www.apollographql.com/docs/apollo-server/api/plugin/drain-http-server/) anyway.)
- Does this depend on the size of your schema? eg, if you shrink your schema to something much smaller, is it faster?
- Is it possible for you to create a reproduction of this that I can run (eg, a repo to `git clone` or codesandbox.io or something)?
- Can you try using the [Node profiler](https://nodejs.org/en/docs/guides/simple-profiling/) or something like that?

**Comment by georgekrax** [comment] 2022-03-12 11:48
Thanks, @glasser for your response!

* Yes, it is `new ApolloServer()` that is slow. If I removed the code snippet above, the boot time will be decreased significantly. If I want to use `await apolloServer.start()`, I should then uncomment and include `new ApolloServer()` instance. As I have measured, the `.start()` function does not seem to delay the boot time
* Yes, it is *startup* delay. When `nodemon` restarts, there is no delay. I tried the code in the docs you provided, but it only increases the boot time by *2 seconds*. So, I guess this is not it.
* Yes, if I remove all of the schema types (and leave just 5) this would decrease the boot time by *3 seconds*
* I will invite you to see my code repo
* I tried it. I used `node --prof build/index.js` , but when I tried to parse it with `node --prof-process` then there was an error. I am on Windows 11, and I do not know if that is the case. In the repo, you will find the relative `v8.log` file. If you can parse it on your computer, it would be really helpful.

Thanks for your help!

**Comment by glasser** [comment] 2022-03-30 19:16
@georgekrax My apologies: I've had this high on my list of "look at it when I've got a big bunch of time" but I didn't accept the invite to your private repo and it has expired. Can you send me another invite?

**Comment by georgekrax** [comment] 2022-03-30 20:36
@glasser No worries! Let me know if you got it

**Comment by glasser** [comment] 2022-03-30 20:51
@georgekrax I'm in, but `npm i` at the top level fails because it looks like there are some merge conflicts in packages/common/package.json.

**Comment by glasser** [comment] 2022-03-30 20:52
Ah nm looking at the wrong branch.

**Comment by glasser** [comment] 2022-03-30 20:53
Er nope, this is a problem on `issue` as well. Can you please let me know (via email to glasser@apollographql.com if it's sensitive) precisely what commands I need to run on precisely what branch?

**Comment by georgekrax** [comment] 2022-03-30 20:54
I would recommend using `yarn`, if you have it installed and you are familiar with it

**Comment by glasser** [comment] 2022-03-30 20:55
Sorry, I tried yarn as well, but it still doesn't want to deal with a package.json with merge conflicts :)

**Comment by georgekrax** [comment] 2022-03-30 21:13
The branch is called *issue*. There seem to be a merge conflict with the `/common` package. Please try it again, and let me know

**Comment by glasser** [comment] 2022-03-31 22:15
I'm really sorry but I'm still having trouble running your site. There are a bunch of different packages, lots of different npm scripts, different build commands. Can you provide me a precise set of commands starting with `git clone` that will reproduce? Consider deleting entire irrelevant subdirectories from the repo.

**Comment by georgekrax** [comment] 2022-04-01 16:35
No, you do not have to be sorry. My bad for not being precise. If you do not have an issue trying `yarn`, that would help, because I am using it too. So, here are the steps:

1. Use `git clone https://github.com/georgekrax/beach_bar.git -b issue <folder-name>` 
2. `cd ./<folder-name>`
3. `yarn` to install dependencies and node_modules
4. `yarn pre:dev`
5. `cd packages/server`
6. And finally `yarn swc:dev`

I have commented out any Prisma/Redis connections because these are local DBs in my computer. But feel free to use, them if you have any spare example ones in your system, and use the relative credentials and details. 

I hope this is more clear, and let you do your work. Please let me know of any upcoming problems.

**Comment by glasser** [comment] 2022-04-09 01:31
I was able to run your code. I was not able to reproduce the 8 second time for `new ApolloServer`. It seems to take a consistent half a second on my machine.

That's still not a trivial amount of time, so I used [0x](https://www.npmjs.com/package/0x) to generate a flamegraph. Surprisingly easy: just running `0x -o build/index.js` (after modifying your script to `process.exit(0)` after listening) gave me this flamegraph. https://gist.github.com/glasser/02200c8d20ef5a0063c142cb210618e9 (download the raw file and open it in your browser)

The left hand side has the `new ApolloServer` part. It looks like most of it is taken up by calculating a hash of the introspection of the schema, and the next bit after that by loading the Studio usage reporting protobuf package.

The hash is a deprecated thing we've already [removed on the in-progress `version-4` branch](https://github.com/apollographql/apollo-server/commit/f2f8faa07a02780ac87bfc2623231693cf32ed88).

The fact that the protobuf package is being loaded at this point rather than on startup is an optimization that we do so that you don't have to load it at all if you're not using studio reporting functionality. In this particular case it's being loaded as part of the [inline trace plugin](https://www.apollographql.com/docs/apollo-server/api/plugin/inline-trace/) which for technical reasons is installed in all servers by default; if you're not using it and want to avoid the overhead, you can install `ApolloServerPluginInlineTraceDisabled` which should prevent the need to load the protobuf package... actually, that doesn't quite work, I've filed https://github.com/apollographql/apollo-server/issues/6306 (PRs welcome).

Since I haven't been able to reproduce the worst behavior (many seconds of delay on startup) and the two biggest causes of slow behavior on my machine are addressed either in upcoming work or have a workaround (or at least a workaround that almost works and I've filed a more precise bug about the problem with the workaround) I'm going to close this issue for now!

**Closed by glasser** 2022-04-09 01:31 UTC

**Comment by georgekrax** [comment] 2022-04-10 15:45
@glasser Thank you for the detailed analysis!

I am still impressed that you do not get at least a 5 seconds delay. Did you try it with *nodemon*?
As I understand, you don't recommend adding the `ApolloServerPluginInlineTraceDisabled` plugin, right?

Thank you very much for your help.

**Comment by glasser** [comment] 2022-04-22 01:59
I didn't use nodemon and my checkout fell out of my `/tmp` :) Adding the plugin won't prevent the package from being loaded, sadly.

**Comment by georgekrax** [comment] 2022-04-22 14:44
@glasser What did you use instead of `nodemon`?

**Comment by glasser** [comment] 2022-04-22 18:14
`node`, just running the script directly.

**Comment by georgekrax** [comment] 2022-04-22 18:34
Oh okay. I will try to use `ts-node` with the `swc` option enabled, to see if it is any better. Thank you for all your help!

Hope you have a great rest of the day 😊
