### ISSUE TITLE
Cannot read property 'Access-Control-Request-Headers' of undefined Apollo-Server-Lambda

### ISSUE THREAD

**Issue by JacobT14** [apollographql/apollo-server#1560] opened 2018-08-21 14:54 UTC
I am currently using Apollo-Server-Lambda 2.0.4

My lambda logs are showing a lot of instances of this error:

TypeError: Cannot read property 'Access-Control-Request-Headers' of undefined
at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:63:38

However, it looks like the request is still responding just fine to the client, so it isn't really breaking anything, but my lambdas are technically erroring out.  I'm not really sure in what scenarios it is happening, but I'm thinking that it is the cors preflight check, as it happens before a lot of requests.

**Comment by JacobT14** [comment] 2018-08-21 17:56
Have confirmed that this is happening when an options request is sent to the API Endpoint, but I'm not really sure why event.headers is undefined in that case?

**Comment by charleswong28** [comment] 2018-10-03 04:55
My observation was wrong in the above comment. 

The problem is because of the setting in API gateway. When you are using integration setting other than `Lambda Proxy Integration` or `integration: LAMBDA-PROXY` in serverless, the event object is not constructed as what apollo-server expects. `event.headers` doesn't exists so you will see `Cannot read property 'Access-Control-Request-Headers' of undefined`. 

Also, the event object is constructed according to your setting in integration setting. When you test your lambda function in aws console without any parameters, you will also see this error since the request is not properly constructed through API gateway. (This is why I only got payload in the above comment.)

You may find [this](https://medium.com/@lakshmanLD/lambda-proxy-vs-lambda-integration-in-aws-api-gateway-3a9397af0e6d) helpful.

---
If you are using multipart/form-data, it works using `Lambda Proxy Integration` and adding `multipart/form-data` to Binary Media Types (Check [this](https://github.com/bbilger/jrestless-examples/blob/master/aws/gateway/aws-gateway-binary/README.md) for details). You will then see `event.isBase64Encoded` to be `true`. You can parse the event body using `Buffer.from(event.body, event.isBase64Encoded ? 'base64' : 'ascii')`. 

If you are using serverless, you will find it working on serverless-offline by just using ascii as encoding but when you deploy to API Gateway, the stream will be encoding wrongly.

**Comment by aarkerio** [comment] 2019-01-17 21:07
if you are testing in the AWS lambda console, you need to create a new test event json like:

`{
  "headers": {"origin":true}
}`

**Comment by caydie-tran** [comment] 2019-07-08 21:55
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by caydie-tran** 2019-07-08 21:55 UTC
