### ISSUE TITLE
startStandaloneServer: PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by klippx** [apollographql/apollo-server#7149] opened 2022-11-16 11:06 UTC
After upgrading to Apollo Server 4 and booting the app using `startStandaloneServer` we started getting a ton of bodyParser issues:

```
PayloadTooLargeError: request entity too large
    at readStream (/app/node_modules/@apollo/server/node_modules/raw-body/index.js:156:17)
    at getRawBody (/app/node_modules/@apollo/server/node_modules/raw-body/index.js:109:12)
    at read (/app/node_modules/@apollo/server/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/app/node_modules/@apollo/server/node_modules/body-parser/lib/types/json.js:135:5)
    at /app/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:211:41
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
```

The docs state this; which fits our use case 100%:

> This `startStandaloneServer` function helps you get started with Apollo Server quickly. This function is recommended for all projects that don't require serverless support or a particular Node.js framework (such as Fastify)

Googling the issue and of course winding up on SO, we saw we need to [tweak bodyParser](https://stackoverflow.com/questions/19917401/error-request-entity-too-large) options which we are not in control of.

The solution was to make a copy of `startStandaloneServer` where we are allowed to do so. 

The `startStandaloneServer` is using third party libs that will run in our apps and we need to have some control over them. We must be able to tweak the options. Otherwise `startStandaloneServer` would not be very useful, save for toy apps :)

**Comment by trevor-scheer** [comment] 2022-11-16 22:30
Hey @klippx, thanks for taking the time to open an issue (and PR). Based on your experience, it looks like there are some improvements and fixes we need to make.

`startStandaloneServer` really is expected to be for "toy apps" as you've pointed out. The expectation is that it makes for a simple and effective getting started experience. We also want its API to remain agnostic of its internals, i.e. exposing configuration options for `body-parser` and `cors` ties us to those packages internally for the life of the major version. For example, we've considered not using `express` at all.

What you're looking for is [`expressMiddleware`](https://www.apollographql.com/docs/apollo-server/api/standalone/#swapping-to-expressmiddleware). This express handler requires you to bring your own body parser and cors middlewares, allowing you to customize them as you please.

A couple takeaways for us though!
1) We should document the transition better and make it more obvious as to when you should be considering `expressMiddleware` instead of `startStandaloneServer`. This probably touches a few places in our docs, including the migration guide. I'll take a pass over what we have currently and see if we can't do better there. If you have a particular place in mind where that would've been helpful I'd be happy to hear it.
2) It looks like the previous `apollo-server` package (`startStandaloneServer` equivalent) came with a [`50mb` body parser limit](https://github.com/apollographql/apollo-server/blob/a0ccf23f50ae51e00a4f2fb260ce44d4b191eb5f/packages/apollo-server/src/index.ts#L114) by default, so that's a regression on our part which I'll open a PR to fix with a docs update.

I'll close this and spin out a couple issues for these^. Thanks!

**Closed by trevor-scheer** 2022-11-16 22:30 UTC
