### ISSUE TITLE
Cannot start apollo-server-express application  bundled by webpack

### ISSUE THREAD

**Issue by VitalyLipko** [apollographql/apollo-server#5231] opened 2021-05-23 15:37 UTC
I run apollo-server-express application with nodemon + ts-node . Dev server works without complaints. But when i try to run bundled app `$ node dist/back/app.js`  i come across with next error:

`(node:14376) UnhandledPromiseRejectionWarning: Error: Expected { __validationErrors: undefined, description: undefined, extensions: undefined, astNode: undefined, extension
ASTNodes: [], _queryType: Query, _mutationType: Mutation, _subscriptionType: undefined, _directives: [@cacheControl, @include, @skip, @deprecated, @specifiedBy], _typeMap:
{ Date: Date, Task: Task, ID: ID, String: String, User: User, Query: Query, Mutation: Mutation, Boolean: Boolean, CreateTaskInput: CreateTaskInput, UpdateTaskInput: UpdateT
askInput, CacheControlScope: CacheControlScope, Upload: Upload, Int: Int, __Schema: __Schema, __Type: __Type, __TypeKind: __TypeKind, __Field: __Field, __InputValue: __Inpu
tValue, __EnumValue: __EnumValue, __Directive: __Directive, __DirectiveLocation: __DirectiveLocation }, _subTypeMap: {}, _implementationsMap: {} } to be a GraphQL schema.
    at t.assertSchema (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:1285086)
    at m (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:1290335)
    at t.assertValidSchema (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:1290025)
    at E (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:988515)
    at S (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:987614)
    at Object.t.execute (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:986726)
    at Object.t.generateSchemaHash (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:54709)
    at m.generateSchemaDerivedData (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:141)
    at new t.ApolloServerBase (C:\Users\lipko\Projects\todo-app\dist\back\app.js:2:218389)
    at new m (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:63924)
    at C:\Users\lipko\Projects\todo-app\dist\back\app.js:54:1956
    at Generator.next (<anonymous>)
    at C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:2898614
    at new Promise (<anonymous>)
    at e (C:\Users\lipko\Projects\todo-app\dist\back\app.js:14:2898359)
    at C:\Users\lipko\Projects\todo-app\dist\back\app.js:54:1912
`

Dependencies list: 
```json
  "dependencies": {
    ...
    "apollo-server-express": "^2.22.2",
    "express": "^4.17.1",
    "graphql": "^15.5.0",
    ...
  },
  "devDependencies": {
     ...
    "nodemon": "^2.0.7",
    "ts-loader": "^9.1.2",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "~4.1.5",
    "webpack": "^5.36.2",
    "webpack-cli": "^4.7.0"
  }
```

Webpack configuration:

```typescript 
const config: Configuration = {
  mode: 'production',
  entry: './back/app.ts',
  target: 'node',
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  output: {
    filename: 'app.js',
    path: resolve(__dirname, '../dist/back'),
  },
  externals: [
    {
      'utf-8-validate': 'commonjs utf-8-validate',
      bufferutil: 'commonjs bufferutil',
      'mongodb-client-encryption': 'commonjs mongodb-client-encryption',
    },
  ],
}
```
Typescript webpack configuration:

```json
{
  "extends": "./tsconfig.back.json",
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "types": ["node"]
  }
}

```

Build script:
` $ cross-env TS_NODE_PROJECT=\"back/tsconfig.webpack.json\" webpack --config back/webpack.config.ts --stats-error-details`

**Comment by glasser** [comment] 2021-05-24 18:27
Hi. I think this is a duplicate of #4983. The conclusion over there is that something about how your webpack is set up is leading to multiple copies of the `graphql` library ending up in your bundle, and `graphql` (https://github.com/graphql/graphql-js) itself really doesn't like that.  This doesn't seem to be anything specific about Apollo Server: it's the graphql-js project that doesn't like having multiple copies, and it's webpack that's putting it together.  Fixing this probably requires understanding webpack at a deeper level than anyone on the Apollo Server team knows.

I think it would be great if one of our users who cares about using Apollo Server with webpack opened an issue with webpack (with a small clear reproduction that's as easy as possible for the webpack folks to use, ie probably starting with `git clone` not "copy some files from this issue") to try to work out why this is happening. Maybe there is something we can do in AS to make this less likely! But I think it's webpack experts who are going to be able to figure that out.

If you do open such an issue please mention it on #4983?

**Closed by glasser** 2021-05-24 18:27 UTC
