### ISSUE TITLE
Custom GraphQLScalarType instance: parseLiteral is called twice

### ISSUE THREAD

**Issue by mikeconley12** [apollographql/apollo-server#2202] opened 2019-01-20 18:00 UTC
The `parseLiteral` method is called twice for the same literal

### Steps to reproduce

* Run the following code

```javascript
const { ApolloServer, gql } = require('apollo-server');
const { GraphQLScalarType } = require('graphql');

const books = [{
  title: 'Harry Potter and the Chamber of Secrets',
  author: 'J.K. Rowling',
}, {
  title: 'Jurassic Park',
  author: 'Michael Crichton',
}];

const typeDefs = gql`
  scalar MyCustomScalar

  type Book {
    title: String
    author: String
  }

  type Query {
    books(dummy: MyCustomScalar): [Book]
  }
`;

const resolvers = {
  MyCustomScalar: new GraphQLScalarType({
    name: 'MyCustomScalar',
    description: 'Description of my custom scalar type',
    serialize(value) {
      console.log("serialize", value);
      return value;
    },
    parseValue(value) {
      console.log("parseValue", value);
      return value;
    },
    parseLiteral(ast, variables) {
      console.log("parseValue", ast, variables);
      return ast.value;
    }
  }),
  Query: {
    books: () => books
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers
});

server.listen().then(({ url }) => {
  console.log(`  Server ready at ${url}`);
});
```

* Open in browser http://localhost:4000/

* Execute in Playground

```graphql
{
  books(dummy: 1) {
    title
    author 
  }
}
```

### Check output in console

```bash
$ node index.js 
  Server ready at http://localhost:4000/
parseValue { kind: 'IntValue', value: '1', loc: { start: 17, end: 18 } } undefined
parseValue { kind: 'IntValue', value: '1', loc: { start: 17, end: 18 } } {}
```

It looks like a bug

**Comment by createcsoft** [comment] 2019-02-04 12:49
Hello, I have the same situation, using  buildSchema 

    const express_graphql = require('express-graphql')
    var { buildSchema } = require('graphql')

    var OddType = new GraphQLScalarType({
      name: 'Odd',
      parseLiteral(ast) {
       console. log('hola parseLiteral')
        return null
  }
    })

**Comment by trevor-scheer** [comment] 2019-07-08 23:57
Hey @mikeconley12, thanks for submitting an issue and providing some details. Could you please help me out by getting your reproduction into a runnable state? I copied the code you gave into a sandbox and it doesn't run. Here's my [progress so far](https://codesandbox.io/embed/quirky-zhukovsky-6viqr). Thanks!

**Comment by abernix** [comment] 2019-07-16 17:32
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

As @trevor-scheer noted, if this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-07-16 17:32 UTC
Labels: :wilted_flower: needs-reproduction, 🚧👷‍♀️👷‍♂️🚧 in triage
