### ISSUE TITLE
Inconsistent behaviour when resolving enums

### ISSUE THREAD

**Issue by will-fagerstrom** [apollographql/apollo-server#2556] opened 2019-04-10 01:56 UTC
I am having an issue with how enums are handled between a root query extension and a field resolver.  The field resolver works as expected and the root query throws an error. Does anyone have any ideas? This feels like a bug with apollo-server 

Here is my schema 

```
extend type Query {
  weatherSatellite(
    type: SatelliteType
    hours: SatelliteAnimationFramePeriod
    location: SatelliteLocations!
  ): WeatherSatelliteAnimation!
}

extend type WeatherResource {
  satellite(
    type: SatelliteType
    hours: SatelliteAnimationFramePeriod
  ): WeatherSatelliteAnimation!
}

enum SatelliteAnimationFramePeriod {
  HOURS_1
  HOURS_2
  HOURS_3
  HOURS_4
}

enum SatelliteLocations {
  National
  NewSouthWales
  NorthernTerritory
  Queensland
  SouthAustralia
  Tasmania
  Victoria
  WesternAustralia
}

enum SatelliteType {
  Infrared
  InfraredAlpha
}

``` 

my resolvers looks like this:

```
const resolvers: IResolvers = {
  Query: {
    weatherSatellite: async (obj, args, context, info) => {
      console.log(args); // Error message: "Variable \"$_v0_location\" got invalid value \"wa\"; Expected type SatelliteLocations.\nVariable \"$_v1_type\" got invalid value \"infrared\"; Expected type SatelliteType; did you mean Infrared or InfraredAlpha?\nVariable \"$_v2_hours\" got invalid value 1; Expected type SatelliteAnimationFramePeriod."
    }
  },

  WeatherResource: {
    satellite: async (obj, args, context, info) => {
      console.log(args); // { type: 'infrared', hours: 1 }
    }
  },

  SatelliteLocations: {
    National: 'national',
    NewSouthWales: 'nsw',
    NorthernTerritory: 'nt',
    Queensland: 'qld',
    SouthAustralia: 'sa',
    Tasmania: 'tas',
    Victoria: 'vic',
    WesternAustralia: 'wa'
  },

  SatelliteType: {
    Infrared: 'infrared',
    InfraredAlpha: 'infrared-alpha'
  },

  SatelliteAnimationFramePeriod: {
    HOURS_1: 1,
    HOURS_2: 2,
    HOURS_3: 3,
    HOURS_4: 4
  }
};
```

My queries looks like this

```
{
  locationByPostcode(postcode:"4000") {
    weather {
      satellite(hours:HOURS_1, type:Infrared) {
        # truncated
      }
    }
  }
}

###

{
  weatherSatellite(location:WesternAustralia, hours:HOURS_1) {
    # truncated
  }
}
```

**Comment by patrick-chaumeil** [comment] 2019-07-24 13:59
I got the same error in context bellow. My schema merge GraphQL Object and SDL from makeExcutableSchema.

My typeDefs contains
`enum ProcessDefinitionSortType {
    LABEL
    REF
    VERSION
  }`
My resolvers contains
`  ProcessDefinitionSortType: {
    LABEL: 'label',
    REF: 'ref',
    VERSION: 'version',
  },
`
And my query is
`query allProcessDefinition {
  allProcessDefinitions(maxResults: 20, firstResult: 5, sortBy: LABEL, sortOrder: DESC, filters: { onlyActive: true, allVersions: true }) {
    items {
      id
      ref
      label
    }
    totalCount
    firstResult
  }
}`
Then an error occures
Variable "$_v2_sortBy" got invalid value "label"; Expected type ProcessDefinitionSortType. Did you mean LABEL?

I resolved this problem when i use only SDL and don't use makeExecutableSchema

**Comment by abernix** [comment] 2019-07-24 15:00
If this is still a problem, could someone who's experiencing this problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

I'll close this since it hasn't received a lot of traction, but also happy to reopen if it still persists (also, if the problem is in `makeExecutableSchema`, we're trying to phase out that coupling and dependence on the package that provides it, `graphql-tools`, so we'll likely want to make sure we check this out if it's actually a problem.

Anyhow, reproduction welcome, and happy to reopen with that!

**Closed by abernix** 2019-07-24 15:00 UTC
