### ISSUE TITLE
apollo-server-micro: "API resolved without sending a response for /api/graphql, this may result in stalled requests." with CORS

### ISSUE THREAD

**Issue by SteliosRammos** [apollographql/apollo-server#5596] opened 2021-08-10 09:06 UTC
I am trying to use apollo-server-micro with Next.js and CORS enabled but haven't been able to access the Apollo Playground as the connection to the '/api/graphql' endpoint fails, displaying the following error in the terminal: "API resolved without sending a response for /api/graphql, this may result in stalled requests."

For a minimal reproducible example, first run: `npx create-next-app` then add the following code in `/api/graphql.js`: 

```js
import { ApolloServer, gql } from 'apollo-server-micro';
import cors from 'micro-cors';
import {send} from 'micro';
const typeDefs = gql`
  type Query {
    sayHello: String
  }
`;

const resolvers = {
  Query: {
    sayHello(parent, args, context) {
      return 'Hello World!';
    },
  },
};

const apolloServer = new ApolloServer({ typeDefs, resolvers });
module.exports = apolloServer.start().then(() => {
  const handler = apolloServer.createHandler({path: '/api/graphql'});
  return cors((req, res) => req.method === 'OPTIONS' ? send(res, 200, 'ok') : handler(req, res))
});
```

The above code is taken from the package [examples](https://www.npmjs.com/package/apollo-server-micro) (only the import syntax is different).

`npm list` output:

├── apollo-server-micro@3.1.2
├── eslint-config-next@11.0.1
├── eslint@7.32.0
├── graphql@15.5.1
├── micro-cors@0.1.1
├── micro@9.3.4
├── next@11.0.1
├── react-dom@17.0.2
└── react@17.0.2

Note that without CORS enabled I am running into CORS issues which is why I added it in the first place.

**Comment by glasser** [comment] 2021-08-17 20:44
I think this is a duplicate of #5547?

As I mentioned on this issue, I do not understand why we have a huge influx of people expecting apollo-server-micro to work out of the box with Next.js despite literally no references on the Micro or Next websites/docs to the other project, other than the existence of one sample project that uses apollo-server-micro in Next. I've [asked the author of that sample](https://github.com/vercel/next.js/pull/13202#issuecomment-892278511) to help me understand why they made that choice and help upgrade the sample to AS3. In the meantime, I'm not a Next expert and I think it makes sense for Next people to figure out how to get Apollo Server to work on their platform. I'm happy to help but my first question keeps being "why apollo-server-micro?" and I haven't gotten a good answer yet.

**Closed by glasser** 2021-08-17 20:44 UTC

**Comment by glasser** [comment] 2021-09-21 18:49
Doesn't "express" sound fast too? :)
