### ISSUE TITLE
An error has occured for subscription 'chatMessageAdded' #

### ISSUE THREAD

**Issue by akaNightmare** [apollographql/apollo-server#528] opened 2017-08-27 17:49 UTC
Hello, I receive next error message from backend
`{message: "Cannot read property 'then' of undefined"}`

I believe the issue related to https://github.com/graphql/graphql-js/releases/tag/v0.11.0

Thanks.

**Comment by kachkaev** [comment] 2017-08-28 19:53
Looks like I'm also facing this – the subscriptions stopped working after a recent upgrade. Rolling back to `"graphql": "0.10.5"` helped. How about downgrading this dependency until a proper bugfix has been found?

**Comment by nowzig** [comment] 2017-08-29 11:34
I can confirm this problem. It works with `"graphql": "0.10.5"` but not with `"graphql": "0.11.*"`

**Comment by dangerdespain** [comment] 2017-08-30 02:18
+1 I'm experience this issue with 0.11.* as well. Downgrading to 0.10.5 resolves the issue.

**Comment by luizstacio** [comment] 2017-09-01 14:26
+1 I'm experience this issue too

**Comment by kachkaev** [comment] 2017-09-01 15:15
Ping @stubailo @martijnwalraven. It is likely that all the apollo newcomers are installing a broken version – might be crucial to fix ASAP.

**Comment by AkimaLunar** [comment] 2017-12-04 23:19
This is still an issue for me and downgrading to 0.10.5 resolves it. Ideally, I'd like to use 0.11.

**Comment by martijnwalraven** [comment] 2017-12-04 23:34
@AkimaLunar: What version of `graphql-subscriptions` are you using?

**Comment by AkimaLunar** [comment] 2017-12-05 22:57
@martijnwalraven It's `"graphql-subscriptions": "^0.4.4"`

**Comment by martijnwalraven** [comment] 2017-12-06 02:27
@AkimaLunar: The latest version of `graphql-subscriptions` is 0.5.5, so I believe upgrading that should solve this.

**Comment by perrosnk** [comment] 2017-12-07 11:24
Any updates on this?

**Comment by martijnwalraven** [comment] 2017-12-07 11:28
@perrosnk This seems unrelated to this issue (which should be solved in recent versions of `graphql-subscriptions`). Are you in fact returning an `AsyncIterable` from the `subscribe` function in your schema?

**Comment by perrosnk** [comment] 2017-12-07 11:40
Yes:

```javascript
    subscribe: withFilter(
      () => pubsub.asyncIterator(ON_NEW_ROUND),
      (roundData, args, { userOnDB }) => {
        if (!userOnDB || !userOnDB.complete) {
          return false;
        }
        return _.some(roundData.data, userOnDB.id);
      },
    ),

```

Although I am not sure about it it might be related to this: https://github.com/graphql/graphql-js/pull/918#issue-236614665

I am starting the server like this:
```javascript
new SubscriptionServer({
          schema: executableSchema,
          execute,
          subscribe,
          onConnect,
          // onOperation: (message, params) => {
          //   console.log('onOperation');
          // },
          onDisconnect: (a) => {
            console.log('Disconnecting');
          },
        }, {
          server: ws,
          path: GRAPHQL_PATH,
        });
```
I am pulling the `subscribe` from `graphql`
Where should I call this?

```javascript
try {
  const result = await subscribe(...);
  if (result.errors) {
    // errors are informative and can be sent to the client
  } else {
    // result is guaranteed to be an AsyncIterable at this point
    return result;
  }
} catch (error) {
  // system error, log the problem and send a failure response to the client.
}
```

**Comment by abernix** [comment] 2019-02-20 18:04
I suspect this problem has been resolved quite some time ago, so I'll close this.  If anyone is still experiencing the problem, please feel free to open a new issue with a reproduction using a recent version of Apollo Server.  Thanks!

**Closed by abernix** 2019-02-20 18:04 UTC
