### ISSUE TITLE
graphql-tag picking wrong version of graphql peer dependency

### ISSUE THREAD

**Issue by olistic** [apollographql/apollo-server#1252] opened 2018-06-26 17:40 UTC
**Intended outcome:**

`graphql-tag` template tag parses SDL using parser of `graphql` package specified in `package.json`.

**Actual outcome:**

When using yarn, if there are many versions of `graphql` in `node_modules`, `graphql-tag` uses a different version of it than the one specified in `package.json`. This doesn't happen with npm (which makes me think that this is maybe a bug in yarn) but I figured I'd start reporting it here in case there's an issue with the way dependencies (or peer dependencies specifically) are specified in the `apollo-server` ecosystem of packages.

**How to reproduce:**

```sh
$ mkdir test && cd test
$ yarn init -y
$ yarn add apollo-server-lambda@rc graphql
```
_This will install `apollo-server-lambda@2.0.0-rc.5` and `graphql@0.13.2` as of today._

At this point, running ``node -e 'require("apollo-server-lambda").gql`type Foo`'`` (which defines an empty type, possible since graphql v0.12.0) succeeds.

```sh
$ yarn add serverless --dev
```
_This will install `serverless@1.27.3`, which has some apollographql dependencies that install `graphql@0.10.0`, `graphql@0.10.1` and `graphql@0.10.3`, ending with those three versions of `graphql` installed plus 0.13.2 from the previous step._

At this point, running ``node -e 'require("apollo-server-lambda").gql`type Foo`'`` **fails**.

**More info:**

* Node versions: v8.10 and v10.4.1.
* NPM version: v6.1.0
* Yarn version: v1.7.0.

**Comment by evans** [comment] 2018-06-26 21:44
😬There's not super great solution here. Ideally serverless would add graphql as a peer dependency, so that there could be a single version of the graphql library.

The other option is to `yarn add graphql@0.10` instead of latest. You'll get a peerDep warning, which you should be able to safely ignore. When  graphql gets bumped to 14, then hopefully a majority of these issues fall away. Let me know if you run into issues with installing 0.10

**Comment by olistic** [comment] 2018-06-26 22:05
@evans Well, thing is I don't want to install `graphql@0.10` because I want to use the latest features of graphql, like empty types and `""` field descriptions. The reason why `graphql` is a peer dependency of `graphql-tag` is because it should parse the SDL using whatever version of graphql the project is using, right? So if my project is using graphql v0.10, the `gql` template tag should parse the SDL using v0.10 whereas if I'm using graphql v0.12 `gql` should parse using v0.12. That means that `graphql-tag` should be using the version of `graphql` defined in my project's `package.json`, and not any version that happens to be in my `node_modules` because of my other dependencies' sub-dependencies. So the more I think about this, the more I think this is an issue with yarn (the problem is not present when using npm).

BTW, I realized I should have probably opened this issue in the `graphql-tag` repo instead of here, do you want for me to move this discussion over there?

**Comment by evans** [comment] 2018-06-27 00:15
Yeah that's the expected behavior of `graphql-tag`, since it expects graphql as a peer dep https://github.com/apollographql/graphql-tag/blob/master/package.json#L34. So gql should be picking up the graphql defined in your package.json. I'm not sure what the correct thing to do.

Given that this https://medium.com/@leeb/graphql-js-preparing-for-v14-0-0-839f823c144e was recommended, I would suggest that serverless be changed to make graphql a peer dependency, rather than pinning the version of graphql or if it's reasonable, use npm

**Comment by evans** [comment] 2018-06-29 22:33
I'm going to close this for now, since there's a work around and unfortunately not much we can do in apollo-server

**Closed by evans** 2018-06-29 22:33 UTC
