### ISSUE TITLE
apollo-server-micro enable subscriptions

### ISSUE THREAD

**Issue by julianux** [apollographql/apollo-server#2639] opened 2019-05-02 06:55 UTC
Hi, I am trying to move the api to apollo-server-micro, for some reason subscriptions gets disabled or maybe they are not implemented yet with micro, before I was using the standalone apollo-server package and subscriptions were just working, can you help me :) ?

**Comment by terrencewwong** [comment] 2019-06-15 23:37
Hi @julianux , I too am using apollo-micro-server and I was wondering if anyone came up with a hack to solve this. My hypothesis is that apollo-server needs internal state to keep a track of the clients that are listening for a subscription and for this reason, it is not possible to use subscriptions with micro (which is more like a lambda and not a running server with state).

That being said, maybe there is some clever solution out there that could make this work?

**Comment by abernix** [comment] 2019-07-04 12:16
I don't suspect this has anything to do with state requirements.  That said, both of your help in looking into this would be greatly appreciated.  Given the very small usage rate of the `apollo-server-micro` package, I'm not sure many users are actively using subscriptions _and_ `micro`.

The contribution which enabled `micro` did claim to provide subscriptions support, but again, your help would be appreciated in debugging it.

**Comment by abernix** [comment] 2019-07-04 12:19
Could this be related to https://github.com/apollographql/apollo-server/issues/1638 and #1630?

**Comment by abernix** [comment] 2019-09-06 14:15
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by abernix** 2019-09-06 14:15 UTC
Labels: :beetle: bug, :wilted_flower: needs-reproduction, 🖇️ micro, 🧬 subscriptions

**Comment by SirensOfTitan** [comment] 2019-10-04 13:48
For those flowing in from Google, here's an example of subscriptions working successfully with micro:
https://codesandbox.io/embed/apollo-server-gnt97

**Comment by berkaey** [comment] 2019-12-18 09:27
@SirensOfTitan did you bypass the micro? did you test it with any other micro routes + GraphQL handler?

**Comment by SirensOfTitan** [comment] 2019-12-24 14:24
@berkaey: I'm using this primarily in a next.js app with some other routes and a graphql handler, although that implementation required a lot more effort than the sandbox I shared above.  Happy to put together an example for that if it would be helpful.

**Comment by berkaey** [comment] 2019-12-24 14:28
Ditched the micro on this projects and kept the express version for this project but I would like to see the implementation 👍

**Comment by david718** [comment] 2020-07-16 05:26
> @berkaey: I'm using this primarily in a next.js app with some other routes and a graphql handler, although that implementation required a lot more effort than the sandbox I shared above. Happy to put together an example for that if it would be helpful.

How connect your nextjs apollo server micro with apollo client(subscription)??

Can I show your example code about nextjs apollo server?

**Comment by tettoffensive** [comment] 2020-09-08 19:08
@SirensOfTitan Can you share how you got graphql subscriptions with next.js? I've been stuck on this for days.

**Comment by nenjamin2405** [comment] 2021-08-01 05:48
Hi @SirensOfTitan, could you please share an example of using graphql subscriptions in Next.js?

**Comment by woojoo666** [comment] 2022-01-21 10:38
@nenjamin2405 and @david718 and @tettoffensive and anybody else that might land here from Google. There is an example for getting NextJS with subscriptions working in [this Stackoverflow answer](https://stackoverflow.com/questions/62371284/apollo-server-with-subscriptions-used-inside-next-js-api-routes-websockets-trou/66268643#66268643). Note that this is for apollo-server v2, not v3. Also note that NextJS actually uses express, and the Micro server doesn't even support websockets (https://github.com/vercel/micro/issues/377) so I doubt it will ever work with subscriptions.

**Comment by tettoffensive** [comment] 2022-01-24 19:11
@woojoo666 I've personally moved away from apollo-server-micro. See #5547

**Comment by woojoo666** [comment] 2022-01-29 23:18
@tettoffensive in that thread the last comment you said stated that you were still using apollo-server-micro 2.0. Are you using something else now?

**Comment by tettoffensive** [comment] 2022-01-30 00:34
> @tettoffensive in that thread the last comment you said stated that you were still using apollo-server-micro 2.0. Are you using something else now?

Yes. I eventually switched to what they recommended in that thread.
