### ISSUE TITLE
apollo-server-testing fails to execute 2 or more queries in the same test.

### ISSUE THREAD

**Issue by pBeliauskas** [apollographql/apollo-server#3906] opened 2020-03-20 14:31 UTC
I have a really simple test.

```
it("should get all groups", () => {
    const { query, mutate } = createTestClient(Apollo.apollo);
    
    const response1 = await query({  
       query: Q_GET_ALL_GROUPS  
    });
    const response2 = await query({  
        query: Q_GET_ALL_GROUPS  
    });

});
```

if I try to execute this tests I get: 
```
Please use the dataSources config option instead of putting dataSources on the context yourself.
     at node_modules/apollo-server-core/src/requestPipeline.ts:635:15
     at fulfilled (node_modules/apollo-server-core/dist/requestPipeline.js:5:58)
```

if I try to execute single query -> all works fine as it should.

ApolloServer is constructed as follows and works perfectly fine: 

```
    this.apollo = new ApolloServer({
      typeDefs: types,
      resolvers,
      dataSources,
      context: testContext
        ? testContext
        : async ({ req, res }: any) => {
            const user = req.user;
            const token = req.headers.authorization || "";
            return { userToken: token, user };
          },
      introspection: true,
      playground: true
    });
  }
```

Would anyone be able to help me out and point to the right direction? :)

**Comment by glasser** [comment] 2022-10-20 20:18
Duplicate of https://github.com/apollographql/apollo-server/issues/2144

**Closed by glasser** 2022-10-20 20:18 UTC
