### ISSUE TITLE
Docs don't match typescript types

### ISSUE THREAD

**Issue by dborstelmann** [apollographql/apollo-server#5870] opened 2021-11-06 06:53 UTC
https://www.apollographql.com/docs/apollo-server/migration/#handler-is-always-async

This doc says callback can be ignored.

```
Expected 3 arguments, but got 2.ts(2554)
handler.d.ts(87, 5): An argument for 'callback' was not provided.
const apolloHandler: (event: any, context: Context, callback: Callback<any>) => void | Promise<any>
```

apollo-server-lambda 3.4

**Comment by glasser** [comment] 2021-11-10 17:15
Duplicate of #5592. There's a discussion of a potential fix on #5593 but the submitted PR does not build.

**Closed by glasser** 2021-11-10 17:15 UTC
