### ISSUE TITLE
Error masking does not work

### ISSUE THREAD

**Issue by ghost** [apollographql/apollo-server#1456] opened 2018-07-31 12:42 UTC
An example given here https://github.com/apollographql/apollo-server/blob/ae9da10e625cf283568ba6d29cea8c3e69a7a03f/docs/source/features/errors.md#masking-and-logging-errors does not work returning empty object. I've reproduced this issue here https://github.com/almostprogrammer/format-error

Also I'd like to know whether it's a good practice to handle errors in `formatError` avoiding duplicating code throughout the app?

**Comment by hwillson** [comment] 2019-07-08 20:38
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed** 2019-07-09 19:32 UTC
Labels: :memo: documentation, :rose: has-reproduction, 🚧👷‍♀️👷‍♂️🚧 in triage
