### ISSUE TITLE
enum default not sent to resolver

### ISSUE THREAD

**Issue by JeffML** [apollographql/apollo-server#1818] opened 2018-10-15 01:47 UTC
Given the following schema definitions:
```
type EngineOps {
    newGame (positionType: POSITION_ENUM=startpos, moves: [Move]): String!
  }

  enum POSITION_ENUM {
    fen,
    startpos
  }
```
I would expect the resolver to get at least one argument (positionType) with this query:

```
    const query = ` mutation {
      Engine(id: "1") {
        newGame
      }
    }`;
```
However the engine gets *no* arguments.  If I specify an argument, like so:
```
    const query = ` mutation {
      Engine(id: "1") {
        newGame(positionType: startpos)
      }
    }`;
```
Then the resolver receives a positionType argument.

**Comment by jbaxleyiii** [comment] 2019-07-08 22:23
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by jbaxleyiii** 2019-07-08 22:23 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
