### ISSUE TITLE
subscription resolver is blocking?

### ISSUE THREAD

**Issue by StefanFeederle** [apollographql/apollo-server#1608] opened 2018-09-03 19:39 UTC
Most examples around subscriptions use the data passed to pubsub.publish() to directly respond to the client. I need to fetch additional data but ran into a problem with concurrency. `workingEmployees.getWorkingEmployee()` is a database call and returns a promise. While this is pending all further events on the pubsub are delayed. Is there a way to do async work without blocking other events?

```javascript
{
   type: employeeType,
   resolve: (parent, args, context, info) => workingEmployees.getWorkingEmployee(parent.id),
   subscribe: () => pubsub.asyncIterator([
      channels.WORKING_EMPLOYEE_ADDED,
      channels.WORKING_EMPLOYEE_REMOVED]),
}
```

**Comment by abernix** [comment] 2019-07-04 12:33
@StefanFeederle Are you still hung up on this, or did you ever find an answer?  I'll close this since this doesn't _appear_ to be a bug with Apollo Server, but rather a question about how to use it or one of its components.  While it might be a limitation, I think we should first make sure it's not working as intended prior to reporting it as an issue.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!

**Closed by abernix** 2019-07-04 12:33 UTC
Labels: tag: subscriptions, ⁉️ question
