### ISSUE TITLE
maxAge of 0 results in no cache-control header

### ISSUE THREAD

**Issue by rainboxx** [apollographql/apollo-server#2605] opened 2019-04-24 22:14 UTC
## Problem

We're facing issues with persisted queries using `GET` requests and IE11. This lovely browser is serving responses without a `cache-control` header from its cache. While this is ok for most of _our current_ application's queries, some queries ***should not*** be cached.

We consider leaving out `cache-control` headers for a `maxAge` setting of `0` a bug. Also the `scope` is ignored while `Cache-Control: private` would be a totally reasonable header.

## Workaround

A workaround for us is to annotate specific types with a `maxAge` of `1` second, which is ugly but works for these kind of requests (we don't expect the user to be faster, but in case he is, it results in glitches).

Furthermore, this workaround for types containing other types is not that easy: as soon as another type without a cache hint is added to a type, the `cache-control` header is no longer sent to the browser because the default `maxAge` is `0` and therefore lower than `1`. We need to annotate all types used in a type as well, which results in a mess: some types by itself might benefit from a different `cacheControl` settings in certain situations.

This code is responsible for leaving out the headers for situations when the lowest `maxAge` is `0`: https://github.com/apollographql/apollo-server/blob/821578775d3ca62ac33a76a8d3d8f51f412cdd80/packages/apollo-cache-control/src/index.ts#L171-L178

## Possible solution

A possible solution for our case would be to still send headers in case the lowest `maxAge` is `0`.

I'd be happy to submit a PR for a proper solution that enables consumers of `apollo-server` to specify a `maxAge` of `0` or `scope` only if this is a reasonable approach.

However, it seems more cache requirements are out there (eg. the old and long untouched #1295 as well as #1424, which might also work for our situation) so this solution might not fit to the overall roadmap. Unfortunately for us #2360 doesn't mention any plans for `cacheControl`.

**Comment by spondbob** [comment] 2019-08-23 04:50
I didn't encounter the issue mentioned, but the same code block might cause [this issue](https://spectrum.chat/apollo/apollo-server/cachecontrol-does-not-work-unless-defaultmaxage-is-set~0e4dc3c5-7cdc-40be-b833-0b2d436d1288).

Basically if you set `maxAge` from `@cacheControl` it will return `undefined` because `lowestMaxAge` will always looking at lowest value therefore no caching will be performed.

Unless your `maxAge` > `cacheControl.defaultMaxAge` then `maxAge` will be returned with lowest value but all your query will be cached.

**Comment by molomby** [comment] 2020-02-13 04:49
This is a pretty serious bug, no?

Specifying `Cache-Control: private, max-age: 0` is completely valid -- it tells shared caches (like CDNs) to exclude the resource, allows private caches (like the browser) to store the resource but instructs them to validate its freshness before using it. This is _very_ different than not returning a cache control header at all which, I believe, is the current behaviour.

At best this incorrectly conflates these two directives, causing sub-optimal caching, at worst it allows information (that has been explicitly marked as private) to be leaked/shared between requests from different users.

If i'm understanding correctly, due to the way cache hints from multiple queries are combine (by min'ing the max ages), **it's possible that _adding_ a field to a query can cause the cache control header to be dropped, even if all the existing fields in the query are `private`**.

Eg. with this type:

```graphql
type User {
  id: ID
  name: String
  email: String @cacheControl(scope: PRIVATE)
  notes: String @cacheControl(scope: PRIVATE, maxAge: 0)
}
```

This query will return with a cache control header of `Cache-Control: private`:

```graphql
query {
  User (id: "123") { id name email }
}
```

But if you also hit the `notes` field, the max age of 0 takes precedence and no cache control header is added:

```graphql
query {
  User (id: "123") { id name email notes }
}
```

This implicitly makes the entire result cacheable, even though it's pretty clear the developer intended the opposite.

**Comment by stevez86** [comment] 2020-05-25 19:33
PR submitted to fix this issue: https://github.com/apollographql/apollo-server/pull/4162

**Comment by timsuchanek** [comment] 2021-01-30 08:20
In case you don't want to wait for a fix, here a shameless plug:
I created a dedicated GraphQL CDN where this is fixed - https://graphcdn.io
We send `private, no-store` in these cases to make it explicit.

**Comment by liamchilds** [comment] 2021-07-01 11:36
I came here with the same problem and while there is still no fix I thought I would share my "workaround" that can be adapted. The following works as an apollo plugin which sets the cache control header if it hasn't already been set.

```ts
export class CacheControlFallbackPlugin implements ApolloServerPlugin<BaseApolloContext> {
  public requestDidStart(): GraphQLRequestListener<BaseApolloContext> {
    return {
      willSendResponse(requestContext: GraphQLRequestContextWillSendResponse<BaseApolloContext>): ValueOrPromise<void> {
        const existingCacheHeader = requestContext.response.http?.headers.get('Cache-Control');
        if (!existingCacheHeader) {
          // This can be tailored....
          requestContext.response.http?.headers.set('Cache-Control', 'no-store, max-age=0');
        }
      },
    };
  }
}
```

**Comment by kdybicz** [comment] 2021-07-01 12:30
I can confirm @liamchilds approach is working, I'm using exactly the same in my project.

**Comment by glasser** [comment] 2021-07-02 22:37
The "workaround" seems reasonable. The approach Apollo Server's cache plugin has always taken was to only send cache headers for cacheable responses, on the assumption that clients wouldn't choose to cache responses without explicit header noting it's OK.  If that assumption is wrong, fixing it with your own plugin seems reasonable.  Alternatively, instead of looking at the existing header, you can just look at the request's cache policy and see if it's cacheable.  The API for this is changing a bit in Apollo Server 3, where it'll be:

```js
export class CacheControlFallbackPlugin<TContext> implements ApolloServerPlugin<TContext> {
  public async requestDidStart(): Promise<GraphQLRequestListener<TContext>> {
    return {
      async willSendResponse(requestContext: GraphQLRequestContextWillSendResponse<TContext>): Promise<void> {
        if (!requestContext.overallCachePolicy.policyIfCacheable()) {
          // This can be tailored....
          requestContext.response.http?.headers.set('Cache-Control', 'no-store, max-age=0');
        }
      },
    };
  }
}
```

In general my philosophy about the cache control plugin is that the main thing it does is calculate `requestContext.overallCachePolicy`; then, as a convenience, it also by default sets a Cache-Control header. But rather than providing lots of knobs for configuring exactly what that header looks like, if you don't like the default behavior, you can disable it (calculateHttpHeaders: false) and have your own plugin look at overallCachePolicy and set headers yourself.

I think this is working as intended.

**Comment by rainboxx** [comment] 2021-07-09 13:11
It seems the docs have been rewritten 5 months ago to indicate that no header is sent if `maxAge` is zero. This _technically_ solves this issue.

However, I still find this behaviour weird and misleading. The resulting reduced DX is pointed out by disclaimers in the documents, e.g. this one:

https://github.com/apollographql/apollo-server/blob/1de9af077bf0c992dd5a82d8ef48bc47dc8afbe7/docs/source/performance/caching.md#L47

The use of the cache plugin is not very straight-forward in this respect.

**Comment by glasser** [comment] 2021-07-12 17:08
In an ideal world, how would Apollo Server know when to send a `max-age=0` header and when to send no header at all? (That's the difference you're describing, right?)

**Comment by rainboxx** [comment] 2021-07-15 06:50
I would probably see `maxAge` being `undefined`/`null` as default and indicating that no cache headers should be sent. Setting `maxAge` to a specific positive integer value would mean to cache the resource for the value given.

**Comment by thehideki81** [comment] 2021-09-02 10:39
I needed to be able to explicitly add max-age: 0, and not send header s if not set.

For this i used a decorator, and a custom plugin. The decorator sets a context, that the pluginc checks, as follows:

Note: Used typescript.

Decorator:

```
import { CacheHint } from 'apollo-server-types'
import { UseMiddleware } from 'type-graphql'

export function CacheControl(hint: CacheHint) {
  return UseMiddleware(({ info, context }, next) => {
    info.cacheControl.setCacheHint(hint)
    // So we can control if we want to set explicit max-age zero headers later.
    context.cacheControlSet = true
    return next()
  })
}
```

Plugin:

```
/**
 * Add cache-control no-cache headers if no headers set.
 */
export const cacheControlFallbackPlugin = (): ApolloServerPlugin => ({
  async requestDidStart(
    _request: GraphQLRequestContext
  ): Promise<GraphQLRequestListener> {
    return {
      willSendResponse(requestContext: GraphQLRequestContext): Promise<void> {
        console.log(requestContext.context)
        // Only if we have explicitly set max age to zero with CacheControl()
        if (
          requestContext.overallCachePolicy.maxAge === 0 &&
          requestContext.context?.cacheControlSet === true
        ) {
          requestContext.response.http?.headers.set(
            'Cache-Control',
            'max-age=0, no-store'
          )
        }
        return
      }
    }
  }
})
```

Usage:

```
  @Query(() => SomeDto, {})
  @CacheControl({ maxAge: 0 })
  async resolverFunction(
    @Arg('id', () => Int) id: number
  ): Promise<SomeDto> {
    return doStuff(id)
  }
```

**Comment by molomby** [comment] 2022-09-28 01:23
This is still so broken. `GET` requests are cacheable by default:

> The response to a GET request is cacheable; a cache MAY use it to satisfy subsequent GET and HEAD requests unless otherwise indicated by the Cache-Control header field
> – [RFC 9110 HTTP Semantics](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.1-7)

> HTTP is designed to cache as much as possible, so even if no Cache-Control is given, responses will get stored and reused if certain conditions are met.
> [MDN HTTP caching: Heuristic caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching)

_Removing_ the `Cache-Control` header when `max-age=0` is the opposite of what should happen. This is especially true when the `Cache-Control` header includes additional directives like specifying a `private` scope, as per my [earlier example](https://github.com/apollographql/apollo-server/issues/2605#issuecomment-585548840). This can easily create a situation where data _that has been explicitly marked as private by the developer_ has that designation removed and replaced with implicit permission to save the response in a shared cache.

Documenting the broken behaviour doesn't make the behaviour any less broken.

**Comment by glasser** [comment] 2022-09-29 21:09
I don't really disagree with you. That said, a bit of a challenge here is that there does appear to be multiple desired outcomes here. I can see an argument for "as long as you have the (installed-by-default) cache control plugin installed (and haven't disabled HTTP header calculation), we should *always* set a cache-control header". But I also see @thehideki81 wants to only set max-age=0 if a field that explicitly uses CacheControl is invoked.  So improving this for your use can might not be right for @thehideki81 's use case. And it does seem that the "always send a cache-control header" use case can be addressed by just setting `calculateHttpHeaders: false` and setting HTTP headers in your own plugin.

That said, you do have a point that HTTP RFCs encourage everyone to set `cache-control` on every response and that browsers will cache many GET requests by default. It's admittedly quite late in the AS4 release cycle (release candidate is out) but changing the behavior of `calculateHttpHeaders: true` (the default) to always set `cache-control` does seem worth considering.

**Comment by glasser** [comment] 2022-09-29 21:13
@molomby How would you feel about changing the behavior of `calculateHttpHeaders: true` to use the same logic as we have now to decide whether to set a cache-control header based on the calculated policy (ie: policy must have positive max-age, response must have no errors) but in *any* case where that's not true, setting a fixed `cache-control: no-store` header?  (and not caring if `private` was selected or not.)

**Comment by glasser** [comment] 2022-09-29 21:15
(We could also keep the current semantics for `POST` and only add the new header for `GET`.)

**Closed** 2022-10-04 19:58 UTC
Labels: 🧬 cache-control
