### ISSUE TITLE
`operationName` in a POST body must be a string if provided for null value

### ISSUE THREAD

**Issue by kdybicz** [apollographql/apollo-server#7199] opened 2022-11-28 14:52 UTC
Some older clients, ie. GraphQL Playground, seems to send request with `operationName` set to `null`. This was not an issue with Apollo Server v3, but it started to be a problem with Apollo Server v4 due to changes in [runHttpQuery.ts](
https://github.com/apollographql/apollo-server/blob/main/packages/server/src/runHttpQuery.ts#L174-L181). Here is old [runHttpQuery.ts](https://github.com/apollographql/apollo-server/blob/6247d96ba90de6fa9b45995dcab72758c99aab78/packages/apollo-server-core/src/runHttpQuery.ts) for reference.

**Stacktrace**
```
POST /graphql (λ: api)
{"message":"`operationName` in a POST body must be a string if provided.","code":"BAD_REQUEST","status":500} BadRequestError [GraphQLError]: `operationName` in a POST body must be a string if provided.
    at new GraphQLErrorWithCode (/Users/user/work/project/node_modules/@apollo/server/src/internalErrorClasses.ts:15:5)
    at new BadRequestError (/Users/user/work/project/node_modules/@apollo/server/src/internalErrorClasses.ts:116:5)
    at runHttpQuery (/Users/user/work/project/node_modules/@apollo/server/src/runHttpQuery.ts:178:15)
    at runPotentiallyBatchedHttpQuery (/Users/user/work/project/node_modules/@apollo/server/src/httpBatching.ts:85:30)
    at ApolloServer.executeHTTPGraphQLRequest (/Users/user/work/project/node_modules/@apollo/server/src/ApolloServer.ts:1038:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  path: undefined,
  locations: undefined,
  extensions: {
    http: { status: 400, headers: HeaderMap(0) [Map] {} },
    code: 'BAD_REQUEST'
  }
}
```

**Expected behaviour**
I believe requests sent with `operationName` set as `null` should be treated as one sent without `operationName` and should be processed without errors.

**Dependencies**
```
"@apollo/datasource-rest": "^4.3.2",
"@apollo/server": "^4.2.1",
"@apollo/server-plugin-landing-page-graphql-playground": "^4.0.0",
"@apollo/utils.keyvadapter": "^1.1.0",
"@apollo/utils.keyvaluecache": "^1.0.1",
```

**Reproduce**
I don't have any working PoC, but you should be able to easily reproduce the issue by using `ApolloServerPluginLandingPageGraphQLPlayground` in your project and running some GQL nameless requests from the Playground.

```
import { ApolloServerPluginLandingPageGraphQLPlayground } from '@apollo/server-plugin-landing-page-graphql-playground';
```

**Comment by glasser** [comment] 2022-11-28 18:41
Duplicate of #7200. Introduced in v4.2.0. Will be fixed in v4.2.2 very soon.

**Closed by glasser** 2022-11-28 18:41 UTC
