### ISSUE TITLE
Playground: Resize schema panel

### ISSUE THREAD

**Issue by joseluisq** [apollographql/apollo-server#2529] opened 2019-04-04 13:19 UTC
Now I' using `apollo-server-express v2.3.1`. I can resize the schema panel once but when I choose some query in the right then I can not resize it anymore and the panel returns to its original position.

I would be great if the schema panel could have the same resize functionality as editor panel and to persist the resize position if I refresh the page later.

**Comment by JacksonKearl** [comment] 2019-07-01 23:44
The GraphQL Playground is actually a separate project under different ownership, located at https://github.com/prisma/graphql-playground. 

Closing this for now - definitely an issue over on the project's repository if this is still a concern for you.

**Comment by websolutions-hamburg** [comment] 2019-07-25 21:53
Maybe it's a problem of the Apollo Fork from the Prisma Playground. Because the current Prisma Playground **v1.7.20** works correct.
With `apollo-server-express: "2.6.9"` it also works correct. But since **v2.7.0** it doesn't work. If you try to change the schema panel size, you now get the following error in the console:

```
SideTabs.tsx:216 Uncaught TypeError: n.props.changeWidthDocs is not a function
    at HTMLDocument.i (SideTabs.tsx:216)
```

![image](https://user-images.githubusercontent.com/26099903/61911291-612e5800-af37-11e9-933a-341dd460600a.png)

**Comment by websolutions-hamburg** [comment] 2019-07-30 21:48
This issue still exists with:
```
apollo-server-express : 2.8.0
apollo playground fork: 1.7.30
```

**Comment by spencersteers** [comment] 2019-08-22 19:03
Looks like it isn't binding the action.


fork: https://github.com/apollographql/graphql-playground/blob/apollo/packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx#L247

prisma: https://github.com/prisma/graphql-playground/blob/5fa7d8398b4af77cd54ddc9a16cfd8a30936ff67/packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx#L272

**Comment by abernix** [comment] 2019-08-24 16:24
@spencersteers 	The "prisma" link you've referenced above is not the current state of (their) `master`:

[This is `master`](https://github.com/prisma/graphql-playground/blob/master/packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx#L247) ([and a perma link to it](https://github.com/apollographql/graphql-playground/blob/59e5690187c61eb8f0d6d734514a78380d66a118/packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx) at the time of this writing, just in case it changes)

Where did you get the `5fa7d83` Git hash that you referenced?

**Comment by abernix** [comment] 2019-08-24 16:30
It looks like it was removed, relatively recently, in https://github.com/prisma/graphql-playground/pull/1001.

Perhaps @yoshiakis could provide some insight/justification on this?

**Comment by spencersteers** [comment] 2019-08-24 19:44
@abernix My bad - not sure how I ended up there.

Looking at the latest release though the action is still being bound [(v1.8.10 SideTabs.tsx)](https://github.com/prisma/graphql-playground/blob/v1.8.10/packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx#L278)

Digging a bit deeper all the commits currently going into master have the resize issue. I pulled master and added the action back in and it seems to be working.

**Comment by abernix** [comment] 2019-08-24 20:15
@spencersteers Would you consider opening a PR for the fix to either the upstream or our fork (and maybe most preferably, out of a matter of timeliness, both?)

If you can, I can probably ship a patch for this fairly quickly.

**Comment by spencersteers** [comment] 2019-08-24 20:17
@abernix Sure, can do.

**Closed** 2019-08-28 17:12 UTC
Labels: 🛹 playground

**Comment by yoshiakis** [comment] 2019-08-30 12:41
@spencersteers Thank you for pushing PR for fixing the regression I've introduced!

**Comment by abernix** [comment] 2019-08-30 12:54
This should be fixed in the GraphQL Playground that's referenced from Apollo Server 2.9.1 if anyone wouldn't mind testing it and reporting back!
