### ISSUE TITLE
Fastify-apollo not working

### ISSUE THREAD

**Issue by R0N1n-dev** [apollographql/apollo-server#6464] opened 2022-05-23 05:29 UTC
This is not working as the documentation says. Actually , not working at all.

const { ApolloServer } = require("apollo-server-fastify");
const { ApolloServerPluginDrainHttpServer } = require("apollo-server-core");

const fastify = require("fastify");

function fastifyAppClosePlugin(app) {
  return {
    async serverWillStart() {
      return {
        async drainServer() {
          await app.close();
        },
      };
    },
  };
}

const { typeDefs } = require("./Schema/TypeDefs");
const { resolvers } = require("./Schema/Resolvers");

async function startApolloServer(typeDefs, resolvers) {
  const app = fastify();
  const server = new ApolloServer({
    typeDefs,
    resolvers,
    csrfPrevention: true,
    plugins: [
      fastifyAppClosePlugin(app),
      ApolloServerPluginDrainHttpServer({ httpServer: app.server }),
    ],
  });

  await server.start();
  app.register(server.createHandler());
  await app.listen(4000);
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`);
}

Result: 
ronin@ronin-HP-Laptop:~/fastify-apollo$ nodemon index
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
[nodemon] clean exit - waiting for changes before restart

**Comment by trevor-scheer** [comment] 2022-05-23 18:50
Thanks @R0N1n-dev, I've opened #6465 to address this. You need to call `startApolloServer` in order for anything useful to happen.

**Comment by glasser** [comment] 2022-05-23 19:20
Duplicate of #6403 (where I had a comment on why we made this choice in the docs)

**Closed by glasser** 2022-05-23 19:20 UTC

**Comment by R0N1n-dev** [comment] 2022-05-24 02:59
This part of the documentation should be improved. It's problematic 
assuming people will get it

**Comment by glasser** [comment] 2022-05-24 05:38
Closed as duplicate does not mean it won't be fixed. It just means we don't need two identical open issues. @trevor-scheer is on it!
