### ISSUE TITLE
[apollo-server-plugin-response-cache]: memcache called twice when query itself is non private

### ISSUE THREAD

**Issue by maapteh** [apollographql/apollo-server#4877] opened 2021-01-28 15:20 UTC
When having cacheControl we noticed cache being called twice. At first we thought something in our monitoring setup. Then putting breakpoint in the app showed indeed it calls it twice on single query, single field with 2 times inside getCache with a different key.

```
  "name": "apollo-server-plugin-response-cache",
  "version": "0.5.7",
 ```
 
 When i set breakpoint in getCache i notice it goes in there two times:
 ![screenshot](https://i.imgur.com/6Prnptl.png)
 
 Now since Redis is superfast normally we wouldnt even notice, but it now becomes less and less stable :(
 
It seems to come from the following code part:
```
            const privateResponse = await cacheGet({
              sessionId,
              sessionMode: SessionMode.Private,
            });
            if (privateResponse !== null) {
              return privateResponse;
            }
            return cacheGet({ sessionMode: SessionMode.AuthenticatedPublic });
 ```
 
So the user comes to this endpoint: `query Foo @cacheControl(maxAge: 600, scope: PUBLIC)` but he has a header in which we told the plugin he is having a sessionId in the responseCachePlugin. That makes the user "private". 

Then the main question. Why does a public only query result in first trying to retrieve PRIVATE data from server? Because the visitor is targeted as unique?

**Comment by trevor-scheer** [comment] 2022-10-20 21:23
Sorry this issue was never addressed. If it's still happening, would you mind putting together a reproduction so we can run and debug the issue on our end?

Since this issue is so old, I'm going to close it. Will gladly reopen if this is still affecting you and you can provide us with a reproduction.

**Closed by trevor-scheer** 2022-10-20 21:23 UTC

**Comment by glasser** [comment] 2022-10-21 04:09
That said, this is working as intended. The plugin doesn't know whether or not the query is going to read private data until *after* the query runs: the cache policy depends on exactly which fields in the operation execute (not every field written in the operation may execute, as some may be nested under non-matching fragments, null objects, empty lists, etc), plus resolvers can dynamically set cache hints as well.  So at read time, if a session ID is set, it does have to look in both caches.

If you don't like the concept of an "authenticated public" cache perhaps we could add a flag to the plugin to disable it entirely.
