### ISSUE TITLE
405 Apollo supports only GET/POST requests.

### ISSUE THREAD

**Issue by btibarra** [apollographql/apollo-server#2362] opened 2019-02-22 21:02 UTC
Hello,

i'm trying to use apollo-server-lambda to deploy my graphql api. This are my settings:

```
// graphql.js
const { ApolloServer } = require('apollo-server-lambda');
const { schema } = require('./app/schema');

const server = new ApolloServer({
  schema,
  context: ({ event, context }) => ({
    headers: event.headers,
    ...
  })
});

exports.graphqlHandler = server.createHandler({
  cors: {
    origin: '*',
    methods: ['POST', 'GET'],
    allowedHeaders: ['Content-Type', 'Origin', 'Accept']
  }
});
```

```
# serverless.yml
service: apollo-lambda
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: LAMBDA

```

When I do a post i get this message:
```{
  "body": "Apollo Server supports only GET/POST requests.",
  "statusCode": 405,
  "headers": {
    "Allow": "GET, POST",
    "Access-Control-Allow-Methods": "POST,GET,OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type,Origin,Accept",
    "Access-Control-Allow-Origin": "*"
  }
}
```

**Comment by juusaw** [comment] 2019-02-28 19:17
While I think this should be configurable, you can alternatively solve it by wrapping the apollo handler in a HTTP method check like this:

```javascript
const withCors = handler => (req, res, ...args) => {
  if (req.method === 'OPTIONS')
    // add required headers here
    res.end()
  else {
    return handler(req, res, ...args)
  }
}

exports.graphqlHandler = withCors((server.createHandler({ ...opts )))
```

It intercepts `OPTIONS` requests before Apollo server and writes the cors headers for the response.

**Comment by JakeDawkins** [comment] 2019-07-08 21:08
Hi @btibarra, this is pretty hard for us to reproduce/test right now, since we don't have the infrastructure set up. This _may_ have been fixed here: 

https://github.com/apollographql/apollo-server/blob/5b46e44451094c4daae3022f40347e234225a7de/packages/apollo-server-lambda/src/ApolloServer.ts#L151-L161

Since this issue seems old and maybe fixed, I'll close it for now. If this is still an issue, I can reopen it though. We'd also love a runnable reproduction/PR if you can :)

**Closed by JakeDawkins** 2019-07-08 21:08 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by waydelyle** [comment] 2019-10-21 13:24
This seems to be an issue when adding
`integration: LAMBDA`
The way I got around this was by doing the following
```js
exports.graphql = (
  event: APIGatewayProxyEvent,
  context: LambdaContext,
  callback: APIGatewayProxyCallback,
) =>{
  const handler = server.createHandler({
    cors: {
      origin: '*',
      credentials: true,
    },
  })

  if (!event.httpMethod) {
    event.httpMethod = event.method
  }

  if (event.body && typeof event.body !== 'string') {
    event.body = JSON.stringify(event.body)
  }

   return handler(event, context, callback);
 };
```

The main reason for having to do it like this is because when you add integration as type lambda, the http method is no longer found under event.httpMethod, but instead found under event.method. The second issue is that with integration lambda event.body is no longer a string, which throws an error later when apollo server lambda tries to json parse the body.

**Comment by waydelyle** [comment] 2019-10-21 16:16
using integration: lambda makes the request template different.
https://serverless.com/framework/docs/providers/aws/events/apigateway/#lambda-integration
