### ISSUE TITLE
apollo-engine-reporting pins dependency on old version of apollo-server-core

### ISSUE THREAD

**Issue by taion** [apollographql/apollo-server#3022] opened 2019-07-10 13:32 UTC
Currently, `apollo-server-core@2.6.8` has a dependency on `apollo-engine-reporting@1.3.5`. The latter has a pinned dependency on `apollo-server-core@2.6.7`.

This means that when you install `apollo-server-core@2.6.8`, you also end up recursively with `apollo-server-core@2.6.7`, which is weird.

This doesn't break anything, as far as I can tell, but it's probably wrong, and the release tooling here should probably also bump `apollo-engine-reporting` on `apollo-server-core` bumps, if it's to have a pinned dependency on core.

**Comment by abernix** [comment] 2019-07-17 15:37
👋 @taion! This should have been resolved by a follow-up release for `apollo-engine-reporting` specifically released to fix this unfortunate weirdness.  It was caused by some hiccup in the release tooling that failed to publish that package, though the exact reason isn't known (I've never seen this before and we haven't changed the release process in a fair bit).

Anyhow, this is hopefully _further_ resolved by a removal of the direct dependency on `apollo-server-core` from `apollo-engine-reporting` in 2.7.0, in lieu of the `apollo-server-types` package (used internally to avoid cycles and introduced in #2990).  Additionally, I intend on loosening the exact pinning of packages within `apollo-server.*` packages in the near future, which will hopefully avoid what is arguably _over-publishing_ of packages that only have their dependent versions bumped. (i.e. The use of Lerna's `--exact` flag).

All in all, thanks for reporting this. 😄

**Closed by abernix** 2019-07-17 15:37 UTC

**Comment by taion** [comment] 2019-07-17 17:51
Thanks!
