### ISSUE TITLE
Apollo Sandbox cannot be loaded

### ISSUE THREAD

**Issue by tobiasschweizer** [apollographql/apollo-server#7628] opened 2023-07-06 14:13 UTC
### Issue Description

Hi there,

I am using NestJs and added a GraphQL endpoint. I [migrated](https://docs.nestjs.com/graphql/migration-guide) to @apollo/server 4.7.5

The endpoint itself works well with GraphiQL etc. but I cannot access the Apollo Sandbox (playground):

> Welcome to Apollo Server
> Apollo Sandbox cannot be loaded; it appears that you might be offline.

In my browser console, I see the following errors:

> Refused to load the image 'https://apollo-server-landing-page.cdn.apollographql.com/_latest/assets/favicon.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".

> graphql:22 Refused to load the image 'https://apollo-server-landing-page.cdn.apollographql.com/_latest/assets/favicon.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".
> 
> graphql:1 Refused to load the script 'https://embeddable-sandbox.cdn.apollographql.com/_latest/embeddable-sandbox.umd.production.min.js?runtime=%40apollo%2Fserver%404.7.4' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> 
> graphql:71 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-OK7pAH5PWuMz0B3Z+8KJD+AVvhgLxb2X4W00TmJw2M8='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> Refused to load the image 'https://apollo-server-landing-page.cdn.apollographql.com/_latest/assets/favicon.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".
> 
> graphql:1 Refused to load manifest from 'https://apollo-server-landing-page.cdn.apollographql.com/_latest/manifest.json' because it violates the following Content Security Policy directive: "default-src 'self' Note that 'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.

I tried the setup described in https://docs.nestjs.com/graphql/quick-start#apollo-sandbox and added:

```js
playground: false,
      plugins: [
        ApolloServerPluginLandingPageLocalDefault({
          headers: {
            'Content-Security-Policy':
              "default-src 'self' https://embeddable-sandbox.cdn.apollographql.com/;",
          },
        }),
      ],
```

In HTML, it looks like follows:

```html
```html
<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'nonce-b5693f538f65c3b4938853dfcf85ff99c16ab6ef4dc5341e87b0c69ccbafa012' https://apollo-server-landing-page.cdn.apollographql.com https://embeddable-sandbox.cdn.apollographql.com https://embeddable-explorer.cdn.apollographql.com; style-src 'nonce-b5693f538f65c3b4938853dfcf85ff99c16ab6ef4dc5341e87b0c69ccbafa012' https://apollo-server-landing-page.cdn.apollographql.com https://embeddable-sandbox.cdn.apollographql.com https://embeddable-explorer.cdn.apollographql.com https://fonts.googleapis.com; img-src https://apollo-server-landing-page.cdn.apollographql.com; manifest-src https://apollo-server-landing-page.cdn.apollographql.com; frame-src https://explorer.embed.apollographql.com https://sandbox.embed.apollographql.com https://embed.apollo.local:3000" />
 
...

<script nonce="b5693f538f65c3b4938853dfcf85ff99c16ab6ef4dc5341e87b0c69ccbafa012">

  var initialEndpoint = window.location.href;
  var embeddedSandboxConfig = {"target":"#embeddableSandbox","initialState":{"headers":{"Content-Security-Policy":"default-src \u0027self' https://apollo-server-landing-page.cdn.apollographql.com;"}},"hideCookieToggle":false,"endpointIsEditable":false,"runtime":"@apollo/server@4.7.5","runTelemetry":true,"allowDynamicStyles":false};
  new window.EmbeddedSandbox(
   {
   ...embeddedSandboxConfig,
   initialEndpoint,
   }
   );
   </script>


```

I think this is a security configuration problem because the browser prevents the loading of the scripts.
So either the config does not take effect or I just put in the wrong options.

This seems to be a known issue, see the original issue below.

### Link to Reproduction

https://github.com/graphql/graphql-playground/issues/1283#issuecomment-1292153300

### Reproduction Steps

I am aware that this is not an actually reproducible bug report. But since this seems to be a known issue, could you please guide me to the correct place? Thx!

**Comment by trevor-scheer** [comment] 2023-07-06 20:20
If you _can_ provide a reproduction that would be very helpful. Have you tried other browsers? Which browser are you using? The CSP stuff shouldn't require configuration on your end for all of this to work fine. I can't reproduce the issue and I haven't seen similar reports so it's probably something with your configuration that we should be able to resolve. I would start by deleting all of the landing page configuration you have currently and seeing if the default behavior still gives you the same issue.

It's worth mentioning that [I just landed a bunch of CSP-related changes in the most recent patch](https://github.com/apollographql/apollo-server/commit/0adaf80d1ee51d8c7e5fd863c04478536d15eb8c), so it's possibly related (but I would've expected more reports by now)

**Comment by tobiasschweizer** [comment] 2023-07-07 07:00
Thanks for your answer.

I have now added a usage example here: https://github.com/tobiasschweizer/apollo-sandbox

However, there it works fine. I used the same versions as in the productive app. Could it be related to deployment?

**Comment by tobiasschweizer** [comment] 2023-07-07 12:23
@trevor-scheer I found the reason: there was some content policy config in NestJs's `main.ts` that had to be extended so it does not block the loading of the JS (the content security policy directives in the error message above come from there). I could make it work for the "traditional" playground so far.

I will try to make this work also for the Apollo Sandbox.

**Comment by tobiasschweizer** [comment] 2023-07-07 12:36
Ok, I also found this

> WARNING
> When using helmet, @apollo/server (4.x), and the [Apollo Sandbox](https://docs.nestjs.com/graphql/quick-start#apollo-sandbox), there may be a problem with [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on the Apollo Sandbox. To solve this issue configure the CSP as shown below:
> 

```js
app.use(helmet({
  crossOriginEmbedderPolicy: false,
  contentSecurityPolicy: {
    directives: {
      imgSrc: [`'self'`, 'data:', 'apollo-server-landing-page.cdn.apollographql.com'],
      scriptSrc: [`'self'`, `https: 'unsafe-inline'`],
      manifestSrc: [`'self'`, 'apollo-server-landing-page.cdn.apollographql.com'],
      frameSrc: [`'self'`, 'sandbox.embed.apollographql.com'],
    },
  },
}));
```

https://docs.nestjs.com/security/helmet

Man, I am feeling a bit stupid now ... Sorry for wasting your time

**Comment by trevor-scheer** [comment] 2023-07-07 16:09
You didn't waste my time. No worries, and thanks for reporting back with the solution!

**Closed by trevor-scheer** 2023-07-07 16:09 UTC
