### ISSUE TITLE
Query stuck on loading after migrating to V3

### ISSUE THREAD

**Issue by pnkapadia64** [apollographql/apollo-server#5700] opened 2021-09-10 12:39 UTC
After updating to v3, queries and mutations are stuck in loading state.

```
"apollo-server-lambda": "^3.3.0",
"apollo-datasource": "^3.1.0",
"type-graphql": "^1.1.1"
"graphql": "^15.5.1",
"@apollo/client": "^3.4.10",
```

There are no errors on the server-side and I also checked the response from `formatResponse` callback of the server.

**Comment by trevor-scheer** [comment] 2021-09-10 15:21
Hey @pnkapadia64, thanks for submitting an issue. Without any obvious problems like a thrown error, this is tough to diagnose on our end. What other debugging steps have you taken? Can you provide a reproduction that we can pull down?

Closing, but we'll reopen if more information is provided.

**Closed by trevor-scheer** 2021-09-10 15:21 UTC
Labels: :wilted_flower: needs-reproduction

**Comment by eportet** [comment] 2022-02-04 09:18
@pnkapadia64 Did you ever find the root cause of the issue? Facing a similar issue and would take any pointers as to where I should look.
