### ISSUE TITLE
apollo-server-testing on server error catch block not executed

### ISSUE THREAD

**Issue by EhsanSarshar** [apollographql/apollo-server#4953] opened 2021-02-24 06:09 UTC
when an error raised on the server. apollo-server-testing not throw it.

**Comment by glasser** [comment] 2021-02-24 07:20
Hi @EhsanSarshar. In order for this to be an actionable bug report, we're going to need a much more clear explanation of what you tried, what you expected, and what you saw instead.  This is most productive as a fully self-contained reproduction, like a git repo I can clone or a codesandbox.io demo. There's not enough information in your post for me to understand your concern, so I'm going to close this issue for now. I'm happy to reopen it if you provide a reproduction!

**Closed by glasser** 2021-02-24 07:20 UTC

**Comment by EhsanSarshar** [comment] 2021-02-24 07:46
@glasser I think it's by design.
when the server throws an error by api call, the catch block must be triggered.

a sample 
``` try {
     const result = await mutata({...something in here})

    if (result. errors) {
    // this block executed when errors occurred. instead of catch block
    }
} catch (e) {
     console.log(e.message)
}
```

**Comment by glasser** [comment] 2021-02-24 18:46
As mentioned, I need a full reproduction to be helpful, not just a small code snippet.

**Comment by youbek** [comment] 2021-02-28 10:16
Simple reproduction https://codesandbox.io/s/apollo-server-testing-on-server-error-catch-block-not-executed-reproduction-w764u?file=/src/index.js

**Comment by youbek** [comment] 2021-02-28 10:19
`client.mutation` is returning an object instead of throwing an Error. Because there is an error in the mutation resolver function. Maybe it is intentional?

**Comment by glasser** [comment] 2021-03-05 23:59
I think this is (as you suggested) working as designed. You're getting back the same kind of object that would be sent to the client, which may contain errors on a subfield.

It would probably be better if this were actually documented! I'd be happy to review a PR for `docs/source/testing/testing.md`.

**Comment by EhsanSarshar** [comment] 2021-03-06 05:21
@glasser if the client receive any error it receive it inside catch block not result.
if it's by design it should have a flexible way to check for errors. like function chaining. 
you can have a look on super-test library.

**Comment by glasser** [comment] 2021-03-08 19:30
By "the client" are you describing the Apollo Client behavior? That is only the default behavior with [`errorPolicy: none`](https://www.apollographql.com/docs/react/data/error-handling/#graphql-error-policies).

If you'd like a helper that throws if any errors are returned, it's easy to write. I'll reiterate that `apollo-server-testing` is merely an ostensibly helpful wrapper around `server.executeOperation` and you can pretty easily write your own wrapper like

```
async function executeOrThrow(server: ApolloServer, request: GraphQLRequest) {
  const response = server.executeOperation(request);
  if (response.errors?.length) {
    throw new GraphQLResponseHasErrors(request);
  }
  return response.
}
```
