### ISSUE TITLE
Errors thrown in the parseLiteral method of custom scalars are not handled anymore

### ISSUE THREAD

**Issue by antogyn** [apollographql/apollo-server#381] opened 2017-05-05 13:56 UTC
Since version 0.5.1 of `graphql-server-koa` (I have only tested the bug with Koa), exceptions thrown in the `parseLiteral` method of custom scalars result in an `Internal Server Error`.

e.g. if we modify the example in the docs to throw an exception:

```js
import { GraphQLScalarType } from 'graphql';
import { GraphQLError } from 'graphql/error';

const resolverMap = {
  Date: new GraphQLScalarType({
    name: 'Date',
    ...
    parseLiteral(ast) {
      throw new GraphQLError('Example error in parseLiteral'); // <===
    },
  }),
};
```
If we run a query with an argument of type `Date`, the server will return `Internal Server Error`.

In version 0.5.0, the error is correctly returned:

```js
{
  "errors": [
    {
      "message": "Example error in parseLiteral"
    }
  ]
}
```

The problem is still present in version 0.7.2.

**Comment by helfer** [comment] 2017-05-05 18:00
Which version of `graphql-js` is this with?

**Comment by antogyn** [comment] 2017-05-10 08:12
In the package.json of version 0.5.0 & 0.5.1:

```
"graphql": "^0.8.2"
```

0.7.2:
```
"graphql": "^0.9.2"
```

I tryed with both 0.8.2 & 0.9.2 for each version, and also 0.9.6 (lastest) for version 0.7.2, the same thing happens

**Comment by helfer** [comment] 2017-05-12 04:03
Ok, it seems it's not due to `graphql-js` then. Could you provide us with a reproduction of the issue? 🙂

**Comment by erezool** [comment] 2017-06-26 06:41
I'm experiencing the same issue and **it's critical bug**!

Attached is an example of reference implementation VS. Apollo.
Do:
`yarn install`

To start the reference implementation (accessible on [http://localhost:3000/graphql](http://localhost:3000/graphql))
`yarn start-reference`

To start the Apollo server implementation (accessible on [http://localhost:3000/graphiql](http://localhost:3000/graphiql))
`yarn start-apollo`

Use the following query for both:
`query test {
  test(custom: "bla, bla bla")
}`

Reference's server response (with 500 HTTP status code) (**expected**):
`{
  "errors": [
    {
      "message": "Did't check, but invalid date!"
    }
  ]
}`

Apollo server response (with 500 HTTP status code)(**unexpected**):
`"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>GraphQLError: Did&#39;t check, but invalid date!<br> &nbsp; &nbsp;at parseLiteral (/Users/erezool/Development/playground/500Error/schema.js:8:34)<br> &nbsp; &nbsp;at GraphQLScalarType.parseLiteral (/Users/erezool/Development/playground/500Error/node_modules/graphql/type/definition.js:239:21)<br> &nbsp; &nbsp;at GraphQLScalarType.isValidLiteral (/Users/erezool/Development/playground/500Error/node_modules/graphql/type/definition.js:231:43)<br> &nbsp; &nbsp;at isValidLiteralValue (/Users/erezool/Development/playground/500Error/node_modules/graphql/utilities/isValidLiteralValue.js:102:13)<br> &nbsp; &nbsp;at isValidLiteralValue (/Users/erezool/Development/playground/500Error/node_modules/graphql/utilities/isValidLiteralValue.js:41:12)<br> &nbsp; &nbsp;at Object.Argument (/Users/erezool/Development/playground/500Error/node_modules/graphql/validation/rules/ArgumentsOfCorrectType.js:40:67)<br> &nbsp; &nbsp;at Object.enter (/Users/erezool/Development/playground/500Error/node_modules/graphql/language/visitor.js:297:29)<br> &nbsp; &nbsp;at Object.enter (/Users/erezool/Development/playground/500Error/node_modules/graphql/language/visitor.js:339:25)<br> &nbsp; &nbsp;at visit (/Users/erezool/Development/playground/500Error/node_modules/graphql/language/visitor.js:229:26)<br> &nbsp; &nbsp;at visitUsingRules (/Users/erezool/Development/playground/500Error/node_modules/graphql/validation/validate.js:76:22)</pre>\n</body>\n</html>\n"
[500Error.tar.gz](https://github.com/apollographql/graphql-server/files/1101189/500Error.tar.gz)
`

**Comment by helfer** [comment] 2017-06-28 21:44
Thanks @antogyn and @erezool. We can probably fix this relatively quickly and have the same behavior as express-graphql by wrapping a `try/catch` around the whole execution block and returning any error thrown inside the `errors` array.

**Comment by helfer** [comment] 2017-06-29 05:40
Hey @antogyn, I made a PR with a failing test case in #441 trying to fix this. As I was doing it I noticed that this is not an issue with graphql-server but with `graphql-js`. May I suggest you check for an issue in that repo, and if it doesn't exist open a new one there? Thanks!

**Comment by RayzRazko** [comment] 2017-07-05 10:40
@helfer I just checked ith graphql 0.9.6 and still getting "Unhandled promise rejection". The problem appeared after update from old apollo server versions to the latest.

**Comment by helfer** [comment] 2017-07-06 03:53
@RayzRazko it's possible that you need to use an even earlier version.

**Comment by abernix** [comment] 2018-09-24 10:09
The error handling and underlying request processing has changed quite a bit since this issue was originally opened, so I’d imagine this has been fixed for a while, but I can confirm that the reproduction provided above by @erezool (thanks for that!) is resolved with the last 1.x version of `apollo-server-express` and the most recent version of `graphql` which the 1.x-series supported: `graphql@0.13.2`.

More specifically, the problem still exhibited itself on newer versions of `apollo-server-express` with the older version `graphql@0.10`, so the problem does appear to have been resolved in a more recent version of `graphql`, though I can’t be sure exactly which version.  Suffice to say, it’s best to use a more recent version of `graphql` at this point since there have been a lot of fixes.

I’ll close this everything seems to be working properly now.  Thanks for opening this originally!

**Closed by abernix** 2018-09-24 10:09 UTC
Labels: duplicate

**Comment by rodrigosanchezg8** [comment] 2018-10-24 16:21
I can confirm this issue still occurs under Apollo-server-express 2.1.0 and graphql 14.0.2 (the newest versions)

**Comment by abernix** [comment] 2018-10-25 08:03
@rodrigosanchezg8 Thanks for the update! Can you put together a simple runnable reproduction on [CodeSandbox w/ Apollo](https://codesandbox.io/s/apollo-server) that shows that the problem?
