### ISSUE TITLE
Datasource instance created on each request

### ISSUE THREAD

**Issue by tyriis** [apollographql/apollo-server#6075] opened 2022-02-02 09:30 UTC
### Description:
We observe a call to the constructor on each request, is this intended?
If yes, the behaviour feels a little bit strange to me, is there a reason to recreate all datasource instances on each request?

### Packages:
```
    "apollo-datasource-rest": "^3.2.0",
    "apollo-server": "^3.4.0",
    "apollo-server-express": "^3.4.0",
```

### Expected:
Datasource instance lifecycle should not end with request end

### Actual:
Datasource instance lifecycle ends with request end.
Thanks for filing an issue on Apollo Server!

### Codebase:
Just used the example on the homepage.

**Comment by glasser** [comment] 2022-02-02 18:59
Yes, the docs might not be very clear, but that's the expected behavior.  "data sources" (or at least the REST data source) are intended to work kinda like [data loaders](https://www.npmjs.com/package/dataloader) where they can do aggressive per-request caching if a request asks for the same data repeatedly.  Specifically, RESTDataSource does two layers of caching: one in-memory cache without expiration, and another layer using a potentially shared cache with expiration based on HTTP headers in the response.

This is documented in https://www.apollographql.com/docs/apollo-server/data/data-sources/#adding-data-sources-to-apollo-server but it's possible it could be more clear.

@trevor-scheer is in the process of doing some refactorings related to data sources (#6047 #6048 #6049). I'm going to close this issue as "working as intended" but I suspect Trevor's data source work will involve refreshing the docs and README a bit, so while he does that I hope he can bear in mind making sure this aspect of the packages is clear in the docs. (eg, I'm not even sure if our docs page describes the multi-layer aspect of RESTDataSource at all.)

**Closed by glasser** 2022-02-02 18:59 UTC
