### ISSUE TITLE
Not able to access response object from context in apollo-server-fastify

### ISSUE THREAD

**Issue by techyrajeev** [apollographql/apollo-server#3156] opened 2019-08-14 08:27 UTC
Previously I was using `apollo-server-express` and I wanted to migrate to fastify so I change it to `apollo-server-fastify`. But it started giving lots of issues.

One of such issue is - Not able to access `res` object from context function.
Below code was working perfectly but res object itself was not available with `apollo-server-fastify`
```
context: async ({ req, res, connection }) => {
// res <--------- undefined
    if (connection) {
      return {
        models,
      }
    }
    if (req) {
      const me = await getMe(req, res)
      return {
        models,
        me,
        secret: process.env.SECRET,
      }
    }
  },
```

**Comment by blacksmoke26** [comment] 2019-08-14 16:09
Yeah, the same issue but you can pass `reply` instance manually.


File `plugins/fastify-apollo-server/index.js`
```js
const fp = require('fastify-plugin');
const {ApolloServer} = require('apollo-server-fastify');

// **** Plugin: plugins/fastify-apollo-server/index.js
module.exports = fp(async ( fastify, opts, next ) => {
  const server = new ApolloServer({
    /* ... */
    context: async request => {
      const {reply} = request;
      return {
        request,
        reply,
        app: fastify,
      };
    },
  });
  
  fastify.addHook('preHandler', async ( request, reply ) => {
    if ( String(request.req.url).startsWith('/graphql') ) {
      request.reply = reply;
    }
  });
  
  fastify.register(server.createHandler({cors: false}), {
    cors: false,
  });
  
  next();
}, {
  name: 'fastify-graphql-server',
});
```

File: `init-server.js`
```js
const app = require('fastify')();

// Plugins
app.register(require('plugins/fastify-apollo-server'));

(async function () {
  app.register(server.createHandler());
  await app.listen(3000);
})();
```

**Comment by techyrajeev** [comment] 2019-08-16 17:34
@blacksmoke26 seems like kind of hack, but thats simplest solution as well.

**Comment by abernix** [comment] 2019-08-26 19:17
Seems at least somewhat related to https://github.com/apollographql/apollo-server/issues/2476.

**Comment by devin-fee-ah** [comment] 2020-03-02 18:23
@abernix unfortunately, they're unrelated. If you look at the [`context` param](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#parameters) then it's documented that `fastify` receives nothing in the context... (which is inaccurate, it actually receives the `req` as context.

The linked issue is about `express` and what its context consists of.

**Comment by HW13** [comment] 2020-03-16 21:15
I've been having the same issue and was able to track down the cause. Should have a bug-fix PR up shortly, I'll be sure to link this issue. Meanwhile, if you'd like to check out the fix here it is -> https://github.com/autotelic/apollo-server/pull/1

**Comment by ALITHEALI** [comment] 2020-04-24 11:46
Any update on this one?

**Comment by HW13** [comment] 2020-04-24 18:14
#3895 is awaiting review. In the meantime I've published a standalone version of apollo-server-fastify with the fix applied, here: https://github.com/autotelic/apollo-server-fastify.

**Comment by benjsicam** [comment] 2020-05-23 02:31
Waiting on #3895 to be merged. Planning to use it to set (JWT) authentication cookies.

**Comment by skozer** [comment] 2020-06-25 06:32
Would be great to see this merged! 🙂

**Closed** 2020-07-15 10:03 UTC
Labels: 🖇️ fastify
