### ISSUE TITLE
Improve the docs about "modules" when initialize ApolloServer

### ISSUE THREAD

**Issue by mrdulin** [apollographql/apollo-server#4386] opened 2020-07-16 06:16 UTC
Don't find any doc about "modules" config. Code here:
`server.ts`:
```js
import { ApolloServer } from 'apollo-server';
import { Post, Tag } from './modules';

const server = new ApolloServer({
  modules: [Post, Tag],
  playground: true,
  introspection: true,
});

server.listen().then(({ url }) => {
  console.log(`apollo server is listening on ${url}`);
});
```

`types.ts`:
```js
export interface Config extends BaseConfig {
  modules?: GraphQLSchemaModule[];
  // ...
}
```

Please add a doc and usage for it.  I create a minimal example, but it doesn't work. Got error:

> Type "Query" was defined more than once.

repo: https://github.com/mrdulin/apollo-graphql-tutorial/tree/master/src/initialize-with-modules

**Comment by justinmchase** [comment] 2020-08-07 15:45
You have to `extend` a type that appears in multiple modules.

```gql
extend type Query {
  posts: [Post]!
}
```
```gql
extend type Query {
  tags: [Tag]!
}
```

**Comment by glasser** [comment] 2022-10-21 05:16
Duplicate of #3642

**Closed by glasser** 2022-10-21 05:16 UTC
Labels: :memo: documentation
