### ISSUE TITLE
Standalone Server hosted in Azure App Service with Easy Authentication prompting CORS Issue

### ISSUE THREAD

**Issue by tyutyu2012** [apollographql/apollo-server#4989] opened 2021-03-06 00:27 UTC
I'm running Apollo standalone server in Azure App service with easy authentication(Azure Active Directory), but I'm getting CORS issue after redirect back to playground page .

CORS error message:

Access to fetch at 'https://login.windows.net/96060fbd-bc66-4ff6-9878-8865580ffd2d/oauth2/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fmyapp.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=150c8b93-7a67-43bb-b8a9-4aa0b959a45b&scope=openid+profile+email&response_mode=form_post&nonce=4b68ae31662f4db79b5e0e7599842ae8_20210306002029&state=redir%3D%252F' (redirected from 'https://myapp.azurewebsites.net/') from origin 'https://myapp.azurewebsites.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. httpLink.js:83 GET https://login.windows.net/96060fbd-bc66-4ff6-9878-8865580ffd2d/oauth2/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fmyapp.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=150c8b93-7a67-43bb-b8a9-4aa0b959a45b&scope=openid+profile+email&response_mode=form_post&nonce=4b68ae31662f4db79b5e0e7599842ae8_20210306002029&state=redir%3D%252F net::ERR_FAILED

package version:

    "apollo-server": "^2.21.0",
    "graphql": "^15.5.0"

```js
const { ApolloServer, gql } = require('apollo-server');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    announcement: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    announcement: () =>
      `Say hello to the new Apollo Server! A production ready GraphQL server with an incredible getting started experience.`
  }
};

const server = new ApolloServer({ typeDefs, resolvers,     playground: true,
  introspection: true});

server.listen(process.env.PORT || 1337).then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

**Comment by glasser** [comment] 2021-03-06 00:47
Hi! Just to be clear, you're *not* using `apollo-server-azure-functions`: this is in Azure but not an Azure Function?

I don't think anyone on the Apollo Server core team has expertise in Easy Authentication, so I'm not really even sure I understand what the issue is or how you've integrated your server with this feature (is this something that's supposed to affect your code at all?). You can configure cors in Apollo Server but that's about what CORS headers AS serves, and it sounds like the problematic cors header in this case is being served by login.windows.net.  Have you integrated this auth with the apollo-server built in copy of graphql-playground somehow?

**Comment by tyutyu2012** [comment] 2021-03-06 00:58
> Hi! Just to be clear, you're _not_ using `apollo-server-azure-functions`: this is in Azure but not an Azure Function?
> 
> I don't think anyone on the Apollo Server core team has expertise in Easy Authentication, so I'm not really even sure I understand what the issue is or how you've integrated your server with this feature (is this something that's supposed to affect your code at all?). You can configure cors in Apollo Server but that's about what CORS headers AS serves, and it sounds like the problematic cors header in this case is being served by login.windows.net. Have you integrated this auth with the apollo-server built in copy of graphql-playground somehow?

I'm not using `apollo-server-azure-functions` . It's hosted in Azure App Service.  I didn't do any authentication inside the code. In the Azure App Service, I turned on the App Service Authentication service
![image](https://user-images.githubusercontent.com/25856852/110189400-9160fc80-7de4-11eb-9441-f964539be53a.png)

I followed this doc to set up my code
https://www.apollographql.com/docs/apollo-server/migration-two-dot/#stand-alone

**Comment by glasser** [comment] 2021-03-06 01:33
OK. I mean I guess I'm not sure what this has to do with Apollo Server — it sounds like something in Azure is adding something to your app that makes it have browsers talk to login.windows.net, which then doesn't pass back appropriate CORS headers?

**Comment by itpropro** [comment] 2021-03-07 13:41
You can configure CORS in your GraphQL server like this:

```Typescript
exports.graphqlHandler = server.createHandler({
  cors: { origin: "*", credentials: true },
});
```

**Only use `*` for development!**

To verify authentication and do proper authorization in your GraphQL server, just use e.g. the following header fields:
- X-MS-CLIENT-PRINCIPAL-NAME
- X-MS-CLIENT-PRINCIPAL-ID

See here for more information on the available fields (https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to#access-user-claims).
If you have token store enabled, use the /.auth/me endpoint to get more information about the user context (https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#token-store).
You should parse auth information directly to the context, he is an basic example:

```Typescript
const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req }) => {
    const header = req.headers["x-ms-client-principal"];
    const encoded = Buffer.from(header, "base64");
    const decoded = encoded.toString("ascii");
    const user = JSON.parse(decoded);
    if (!user) throw new AuthenticationError("Please login first");
    return { user };
  },
});
```

**Comment by tyutyu2012** [comment] 2021-03-08 21:21
> You can configure CORS in your GraphQL server like this:
> 
> ```ts
> exports.graphqlHandler = server.createHandler({
>   cors: { origin: "*", credentials: true },
> });
> ```
> 
> **Only use `*` for development!**
> 
> To verify authentication and do proper authorization in your GraphQL server, just use e.g. the following header fields:
> 
> * X-MS-CLIENT-PRINCIPAL-NAME
> * X-MS-CLIENT-PRINCIPAL-ID
> 
> See here for more information on the available fields (https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to#access-user-claims).
> If you have token store enabled, use the /.auth/me endpoint to get more information about the user context (https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#token-store).
> You should parse auth information directly to the context, he is an basic example:
> 
> ```ts
> const server = new ApolloServer({
>   typeDefs,
>   resolvers,
>   context: ({ req }) => {
>     const header = req.headers["x-ms-client-principal"];
>     const encoded = Buffer.from(header, "base64");
>     const decoded = encoded.toString("ascii");
>     const user = JSON.parse(decoded);
>     if (!user) throw new AuthenticationError("Please login first");
>     return { user };
>   },
> });
> ```

I configured CORS in many ways but it didn't work

**Comment by glasser** [comment] 2021-03-08 21:22
I think it is very unlikely that the Apollo Server team will be able to help you with this issue, so I'm going to close it. If other folks who use this software want to try to help, that would be grea!

**Comment by tyutyu2012** [comment] 2021-03-08 21:32
> OK. I mean I guess I'm not sure what this has to do with Apollo Server — it sounds like something in Azure is adding something to your app that makes it have browsers talk to login.windows.net, which then doesn't pass back appropriate CORS headers?

I also tried to use Apollo Server v1 with the following code. With Azure AD authentication, I don't see a CORS issue. What did do differently between Apollo Server v1 and v2?
```
const express = require('express');
const bodyParser = require('body-parser');
const { makeExecutableSchema } = require('graphql-tools');
const { graphqlExpress } = require('apollo-server-express');

const typeDefs = `
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello: () => 'Hello world!'
  },
}

const myGraphQLSchema = makeExecutableSchema({
  typeDefs,
  resolvers,
});

const PORT = 3000;

const app = express();

// bodyParser is needed just for POST.
app.use('/graphql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));

app.listen(PORT);
```

**Comment by glasser** [comment] 2021-03-08 21:34
If you can provide two deployed versions of the working and non-working app and full instructions about how to use them (do I need some sort of Azure login) then it might be possible to at least start to come up with a theory.

**Closed by glasser** 2021-03-08 21:34 UTC

**Comment by tyutyu2012** [comment] 2021-03-08 21:52
> If you can provide two deployed versions of the working and non-working app and full instructions about how to use them (do I need some sort of Azure login) then it might be possible to at least start to come up with a theory.

I will set up something little quick

**Comment by tyutyu2012** [comment] 2021-03-09 00:09
> If you can provide two deployed versions of the working and non-working app and full instructions about how to use them (do I need some sort of Azure login) then it might be possible to at least start to come up with a theory.

here is the non-working example: [https://apollographqltest.azurewebsites.net](url)
To reproduce this issue

1. clone https://github.com/tyutyu2012/graphqlv2 with visual studio code 
2. install Azure App service extension in visual studio code
![image](https://user-images.githubusercontent.com/25856852/110390640-ee022880-802b-11eb-8631-9f0b508b1ab4.png)

3. in Azure Portal, https://portal.azure.com/,  create an app service with the following set up
![image](https://user-images.githubusercontent.com/25856852/110390427-96fc5380-802b-11eb-8e31-9d672b86d809.png)
4. In Visual Studio Code - Azure Extension -  deploy code from the repository
![image](https://user-images.githubusercontent.com/25856852/110390937-5fda7200-802c-11eb-9b28-fece4ee9ba21.png)
5. In Azure Portal - Azure App service - Configuration - Default Document, add 'index.js' as a default document
![image](https://user-images.githubusercontent.com/25856852/110391364-f7d85b80-802c-11eb-996f-f5e0d286d2ab.png)
6. In Azure Portal - Azure App Service - Configuration - Application settings - advanced edit - change to the following config 
```
[
  {
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "8e6f8c64-40b7-469a-b2b1-a8e78ba67d4c",
    "slotSetting": false
  },
  {
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "value": "InstrumentationKey=8e6f8c64-40b7-469a-b2b1-a8e78ba67d4c;IngestionEndpoint=https://centralus-0.in.applicationinsights.azure.com/",
    "slotSetting": false
  },
  {
    "name": "ApplicationInsightsAgent_EXTENSION_VERSION",
    "value": "~2",
    "slotSetting": false
  },
  {
    "name": "NODE_OPTIONS",
    "value": "--max-http-header-size=16384",
    "slotSetting": false
  },
  {
    "name": "VSTS_ARM_REST_IGNORE_SSL_ERRORS",
    "value": "true",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
    "value": "7",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_NODE_DEFAULT_VERSION",
    "value": "12.18.0",
    "slotSetting": false
  },
  {
    "name": "XDT_MicrosoftApplicationInsights_Mode",
    "value": "default",
    "slotSetting": false
  }
]
```
![image](https://user-images.githubusercontent.com/25856852/110398176-f57bfe80-8038-11eb-89ff-8237b7a3729e.png)

7. In Azure Portal - Azure App Sevice - Authentication settings - create a default app registration, and only allow 'login with Active Directory'
![image](https://user-images.githubusercontent.com/25856852/110396874-5fdf6f80-8036-11eb-8123-db65006d114c.png)
![image](https://user-images.githubusercontent.com/25856852/110396804-463e2800-8036-11eb-97cc-9d74d7ca6934.png)

**Comment by tyutyu2012** [comment] 2021-03-09 00:22
https://github.com/tyutyu2012/graphqlv1
this repo has the graphql v1(working version)

**Comment by tyutyu2012** [comment] 2021-03-23 18:34
@glasser 
were you able to take a look at this? We have an open ticket with Microsoft, and they are curious if this problem has to do with Apollo. How can we get together and resolve this issue? Maybe we could arrange a time to look at this as a team?

**Comment by glasser** [comment] 2021-03-23 20:01
I do have this on my list of "things to dig into on a day that I have time to work on issues that require research and learning".
