### ISSUE TITLE
Make possible run loggers and other middleware after graphqlExpress();

### ISSUE THREAD

**Issue by pks1989** [apollographql/apollo-server#3115] opened 2019-07-31 11:03 UTC
Hello all!

I use graphqlExpress() in my project to send graphQL queries, and its work fine:
```javascript
...

server.use(
    '/graphql',
    bodyParser.json(),
    graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }),
    cors(),
    graphqlExpress(async request => ({
      schema,
      context: { headers: request ? request.headers : null },
    })),
  );

...
```

after some time I want to add the story of queries in my project so I try to do something like this: 

```javascript
...
server.use(
    '/graphql',
    bodyParser.json(),
    graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }),
    cors(),
    graphqlExpress(async request => ({
      schema,
      context: { headers: request ? request.headers : null },
    })),
    logger((tokens, req, res) => {
      // parse res.body stuff and logging
    })
  );
...
```

and it's not working, I going to graphqlExpress() code and see that part:
```javascript
...
 if (typeof res.send === 'function') {
    res.send(graphqlResponse);
  }
...
```
with no next() after send. 

if i add next(), after send() my middleware code works fine:

```javascript
if (typeof res.send === 'function') {
  res.send(graphqlResponse);
  next();
}
```

Sorry, if this dumb question, but why reason don't add next() after send() ?

**Comment by abernix** [comment] 2019-08-26 19:58
Are you sure this is still problematic after the landing of https://github.com/apollographql/apollo-server/pull/2842 in [v2.8.0]https://github.com/apollographql/apollo-server/blob/master/CHANGELOG.md#v280)?

**Comment by glasser** [comment] 2022-10-20 00:54
This is essentially a duplicate of #5560.

**Closed by glasser** 2022-10-20 00:54 UTC
Labels: 🖇️ express
