### ISSUE TITLE
graphqlLambda - Invalid event.body results in 'Unhandled promise rejection' not a proper Lambda Proxy response

### ISSUE THREAD

**Issue by simonpetty** [apollographql/apollo-server#727] opened 2017-12-19 21:03 UTC
If like me you screw up the serialisation of the event.body when using HTTP Post, the Lambda function simply errors. This means there's no proper response that the Lambda Proxy Integration can understand and forward on to the client.

The Lambda function logs only contain something like the following:

2017-12-19T17:58:20.390Z	32c7df19-e4e6-11e7-96b9-11ab75859385	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token q in JSON at position 0

I'll see about creating a pull request, but a try catch around the JSON.parse(query) (line 38 of ambdaApollo.ts) would allow us to return a proper 500 callback.

**Comment by tomyitav** [comment] 2018-08-18 11:55
@simonpetty +1. Anything new about this? I'm getting a similar error on my lambda when executing post:
![erroroncloudswatch](https://user-images.githubusercontent.com/16193919/44299019-b0ffaa80-a2f6-11e8-92cd-397613a5b1e6.PNG)

**Comment by mrkewcz** [comment] 2018-09-25 08:12
I have similar problem. 
`.... SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at graphqlHandler (/var/task/node_modules/apollo-server-lambda/dist/lambdaApollo.js:24:24)
    at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:90:85`

**Comment by tomyitav** [comment] 2018-09-25 08:30
After a long time of not getting an answer, I got my server up and running by using express directly, with the serverless-http plugin. My code is available at https://github.com/tomyitav/apollo-typed-lambda
The lambda.js file directly wraps the express server instance with serverless-http. Hope it helps!

**Comment by mrkewcz** [comment] 2018-09-25 08:42
Thank you :) I will look! But I found problem at my side, I was testing my code by directly running lambda and Api Gateway in AWS, and my test data was badly formatted.

So I changed it to this: 

`{
  "httpMethod": "POST",
  "body": "{\"query\": \"{users{user_id email}}\"}"
}`

Before that I had object inside body, but this configuration works on apollo-server-lambda 1.x.x.

**Comment by abernix** [comment] 2019-07-02 13:14
Closing as this issue is quite old, but if anyone is still encountering this problem, please open a new issue with a reproduction (and since it's Lamdba, preferably a reproduction that is also a [`serverless`](https://serverless.com) project so it can be quickly reproduced and tested).

That said, a lot has changed with `apollo-server-lambda` since this issue was first opened, so perhaps this has already been fixed.  Thanks!

**Closed by abernix** 2019-07-02 13:14 UTC
Labels: integration: lambda
