### ISSUE TITLE
I want to use multiple types in input type.But it go an error(The type of Mutation.fbAddSet(param:) must be Input Type but got: set_input.)

### ISSUE THREAD

**Issue by TimLiu1** [apollographql/apollo-server#2183] opened 2019-01-15 09:18 UTC
scalar Date
union Types = String | Int

input Promoted_object {
    application_id: Int
    pixel_id: Int
    custom_event_type: String
    object_store_url: String
    offer_id: Types
    page_id: String
    product_catalog_id: Types()
    product_item_id: Types
    product_set_id: Types
    event_id: Types
    offline_conversion_data_set_id: Types
    fundraiser_campaign_id: Types
    spend_cap: Int
    status: String

  }

  input Campaign_spec {
    name: String,
    objective:String,
    buying_type: String
  }

  input set_input {
    adset_schedule: String
    attribution_spec: String
    bid_amount: Int
    bid_strategy: String
    billing_event: Float
    campaign_id: String
    campaign_spec: Campaign_spec
    creative_sequence: String
    daily_budget: Int
    daily_imps: String
    daily_min_spend_target: Int
    daily_spend_cap: Int
    destination_type: String
    end_time: Date
    execution_options: [String]
    frequency_control_specs: String
    is_dynamic_creative: Boolean
    lifetime_budget: Int
    lifetime_imps: Int
    lifetime_min_spend_target: Int
    lifetime_spend_cap: Int
    name: String
    optimization_goal: String
    pacing_type: [String]
    promoted_object: Promoted_object
    rf_prediction_id: String
    status: Date
    targeting: Date
    time_based_ad_rotation_id_blocks: [String]
  }

extend type Mutation {
  fbAddSet(input: set_input): JSON
  }

**Comment by TimLiu1** [comment] 2019-01-15 09:18
How can i fix it?

**Comment by JakeDawkins** [comment] 2019-07-08 23:32
Hi! I'm quite what this issue is asking about. Since there's no description or reproductions, I'm going to close this. If you're still having an issue, feel free to let me know, and provide a runnable reproduction.

**Closed by JakeDawkins** 2019-07-08 23:32 UTC

**Comment by wtfiwtz** [comment] 2021-02-09 20:10
`input union` types aren't yet available
https://github.com/graphql/graphql-spec/issues/488
