### ISSUE TITLE
internal values for enums break schema validation, directive validation and array upcasting for arguments in directives

### ISSUE THREAD

**Issue by despairblue** [apollographql/apollo-server#2908] opened 2019-06-23 15:32 UTC
Using the [internal values](https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values) for enums breaks the type system with regards to directives.

The examples are rather lengthy, here is a codesandbox showing all the errors: https://codesandbox.io/s/apollo-server-3scz9

## This here should fail because the schema is invalid:

```graphql
directive @hasRoles(roles: [UserRoleType!]!) on FIELD_DEFINITION

enum UserRoleType {
  ADMIN
}

type Query {
  getSomethingElse: String @hasRoles(roles: FOOL)
}
```

It should be invalid because `FOOL` is not part of `UserRoleType`. But when adding internal values for `UserRoleType` the server starts **without** producing and error like `GraphQLError: Argument "roles" has invalid value FOOL.`.

## This also breaks the directive validation:

This fails with `Error: SchemaDirectiveVisitor for @hasRoles must implement visitFieldDefinition method` as it should:

```js
const { ApolloServer, SchemaDirectiveVisitor } = require("apollo-server");

class HasRolesDirective extends SchemaDirectiveVisitor {
}

const schemaDirectives = {
  hasRoles: HasRolesDirective
};

// ...

const server = new ApolloServer({
  typeDefs,
  schemaDirectives
});

server.listen();
```

This starts even though it should not:

```js
const { ApolloServer, SchemaDirectiveVisitor } = require("apollo-server");

class HasRolesDirective extends SchemaDirectiveVisitor {
}

const schemaDirectives = {
  hasRoles: HasRolesDirective
};

// ...

const resolvers = {
  UserRoleType: {
     ADMIN: "admin"
  },
};

const server = new ApolloServer({
  typeDefs,
  schemaDirectives,
  resolvers
});

server.listen();
```

The only difference are the internal values.

## This should cast a singe value into an array:

This logs `{ roles: [ 'ADMIN' ] }` to the console when starting:

```js
const { ApolloServer, gql, SchemaDirectiveVisitor } = require("apollo-server");

class HasRolesDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition() {
    console.log(this.args);
  }
}

const schemaDirectives = {
  hasRoles: HasRolesDirective
};

const typeDefs = gql`
  directive @hasRoles(roles: [UserRoleType!]!) on FIELD_DEFINITION

  enum UserRoleType {
    ADMIN
  }

  type Query {
    getSomething: String @hasRoles(roles: ADMIN)
  }
`;

const server = new ApolloServer({
  typeDefs,
  schemaDirectives
});

server.listen();
```

When using internal values it logs `{ roles: 'ADMIN' }`, `roles` is not an array anymore, even though the schema says it should be:

```js
const { ApolloServer, gql, SchemaDirectiveVisitor } = require("apollo-server");

class HasRolesDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition() {
    console.log(this.args);
  }
}

const schemaDirectives = {
  hasRoles: HasRolesDirective
};

const typeDefs = gql`
  directive @hasRoles(roles: [UserRoleType!]!) on FIELD_DEFINITION

  enum UserRoleType {
    ADMIN
  }

  type Query {
    getSomething: String @hasRoles(roles: ADMIN)
  }
`;

const resolvers = {
  UserRoleType: {
    ADMIN: "admin"
  },
};

const server = new ApolloServer({
  typeDefs,
  schemaDirectives,
  resolvers
});

server.listen();

```

**Comment by alexpyoung** [comment] 2019-10-22 18:00
I am also seeing some unexpected behavior parsing schema directives when using literal values. Here is a sandbox demonstrating what I am seeing: https://codesandbox.io/s/apollo-server-6gl9w
```javascript
const {
  ApolloServer,
  gql,
  SchemaDirectiveVisitor,
  makeExecutableSchema
} = require("apollo-server");

class MapUnknownEnumValueDirective extends SchemaDirectiveVisitor {
  visitEnum(type) {
    const { to: defaultValue = "__UNKNOWN__" } = this.args;
    const valueMap = type.getValues().reduce((result, value) => {
      result[value.value] = value.name;
      return result;
    }, {});
    type.serialize = v => valueMap[v] || defaultValue;
  }
}

const schemaDirectives = {
  mapUnknownEnumValue: MapUnknownEnumValueDirective
};

const typeDefs = gql`
  directive @mapUnknownEnumValue(to: String) on ENUM

  enum Foo @mapUnknownEnumValue(to: "UNKNOWN_FOO") {
    bar
    baz
  }

  type Query {
    list: [Foo!]!
  }
`;

const Query = {
  list: () => ["bar", "baz", "foo"]
};

const schema = makeExecutableSchema({
  typeDefs,
  schemaDirectives,
  resolvers: {
    Foo: {
      bar: "_bar",
      baz: "_baz"
    },
    Query
  }
});

console.log("Enum with literal values", schema.getDirectives());

console.log(
  "Enum without literal values",
  makeExecutableSchema({
    typeDefs,
    schemaDirectives,
    resolvers: {
      Query
    }
  }).getDirectives()
);

const server = new ApolloServer({ schema });

server.listen();

```

**Comment by electerious** [comment] 2020-06-21 10:27
Here's another issue that seems to be related to internal enum values: When you define internal values for an enum and you try to use enum values as argument default you get "Enum \"EnumName\" cannot represent value: \"EnumValue\"".

```graphql
enum Range {
	LAST_24_HOURS
	LAST_7_DAYS
	LAST_30_DAYS
	ALL_TIME
}

type Page {
	id: ID!
}

Query {
	pages(
		range: Range = LAST_7_DAYS
	): [Page!]
}
```

```js
// The resolver
Range: {
	LAST_24_HOURS: 'a',
	LAST_7_DAYS: 'b',
	LAST_30_DAYS: 'c',
	ALL_TIME: 'd'
}
```

Error: `Enum \"Range\" cannot represent value: \"LAST_7_DAYS\""`

It can be fixed by either removing the default value _or_ the internal values.

**Comment by glasser** [comment] 2021-05-06 20:02
I'm not sure if this issue is entirely about schemaDirectives or if there's another aspect.

Right now we are planning to remove support for `schemaDirectives` in Apollo Server 3, because the project that implements it (graphql-tools) considers it to be a legacy API. Folks who want to use `schemaDirectives` or its non-legacy replacement `schemaTransforms` can use `@graphql-tools/schema` directly to create a schema passed in with `new ApolloServer({schema})`;  issues relating to these options should probably be opened in the graphql-tools repo.

If there's an aspect to this issue that can be reproduce without using schemaDirectives, let me know!

**Closed by glasser** 2021-05-06 20:02 UTC
