### ISSUE TITLE
Not working for node 6x

### ISSUE THREAD

**Issue by debanjanbasu** [apollographql/apollo-server#1167] opened 2018-06-13 05:11 UTC
/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runHttpQuery.js:35
async function runHttpQuery(handlerArguments, request) 

This is causing the module to be unusable for node 6.x

Please transpile if possible, as there are many servers still using node 6x.

**Comment by debanjanbasu** [comment] 2018-06-13 05:11
async await should be at least transpiled to using generators

**Comment by debanjanbasu** [comment] 2018-06-13 06:05
Traced it down to an upgrade of the TypeScript version.

**Comment by debanjanbasu** [comment] 2018-06-13 11:34
`npm ls apollo-server-express`

`C:\Users\deban\Desktop\trade-box-serverless
`-- apollo-server-express@2.0.0-beta.8`

I've been using apollo-server-express@2.0.0-beta.5 for quite some time. However, this version broke everything. The issue is that google cloud functions are still running version 6.11.5 of node. Which means, that I've ensure everything works with nodejs 6x.

I am myself using node 10x on my local dev machine. Is there a proposed fix for apollo-server-express to be compatible with node 6x?

**Comment by debanjanbasu** [comment] 2018-06-14 02:09
Broken again after version beta.10 beta.9 worked for a moment.

**Comment by evans** [comment] 2018-06-15 05:05
@debanjanbasu The CI on #1125 is passing for Node 6, so I'm not sure what the issue is. Can you post the problem you're running into?

**Comment by evans** [comment] 2018-06-18 07:46
I'm going to close this issue, you can install the latest rc with `npm install apollo-server@rc`, which should support the Node 6

**Closed by evans** 2018-06-18 07:46 UTC
