### ISSUE TITLE
Custom validation rules break query argument validation

### ISSUE THREAD

**Issue by maxevilmind** [apollographql/apollo-server#1627] opened 2018-09-07 05:25 UTC
I try to query a model with the single id parameter
The request looks like this:
{"operationName":"GetClient","variables":{"id":3},"query":"query GetClient($id: Int!) {\n  client(id: $id) {\n    node {\n      email\n      id\n      profile {\n        phone\n        name\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}
**Intended outcome:**
The operation succeeds and returns proper values
**Actual outcome:**
The response comes back with a status 400 and the following error:
{"errors":[{"message":"Argument \"id\" of required type \"Int!\" was provided the variable \"$id\" which was not provided a runtime value.","name":"ValidationError","locations":[{"line":2,"column":14}]}]}
**How to reproduce the issue:**
Send a single id parameter in query variables to your grapqh-server-express
This does happen ocasionally so you may do it several times
At some point you will see that the $id is being sent properly, but it does not pass grapqh-server-express validation for some reason

Attaching screenshots from a browser network tab:
<img width="407" alt="screen shot 2018-09-07 at 11 14 59 am" src="https://user-images.githubusercontent.com/9032848/45199880-f4af5980-b28f-11e8-9aaa-0a35cdd363b8.png">
<img width="862" alt="screen shot 2018-09-07 at 11 15 13 am" src="https://user-images.githubusercontent.com/9032848/45199882-f4af5980-b28f-11e8-9471-31fda3c97494.png">

**Comment by mxstbr** [comment] 2018-10-02 13:47
I'm also running into this error during my upgrade to Apollo Server v2, see withspectrum/spectrum#3855 

I think it has something to do with adding custom `validationRules`. This specific commit started failing the build with the error "Argument "id" of required type "ID!" was provided the variable "$id" which was not provided a runtime value.": https://github.com/withspectrum/spectrum/pull/3855/commits/0cb181d462dc6c6fb1bd0f000845f3029e3e9eba Before that it was working perfectly fine.

**Comment by mxstbr** [comment] 2018-10-03 09:31
I've renamed the issue accordingly to the assumption that the cause are the custom validation rules!

**Comment by mxstbr** [comment] 2018-10-03 11:35
I've tried upgrading us to `graphql@0.13` (from `0.11`), hoping it would resolve this error, but unfortunately it stil happens.

Any clue why this could be failing?

**Comment by mxstbr** [comment] 2018-10-03 11:40
It appears that `graphql-cost-analysis` is the root cause here—as soon as I remove that validation rule everything starts working again. /cc @pa-bru 

Probably related to https://github.com/pa-bru/graphql-cost-analysis/issues/12 in my case.

**Comment by martijnwalraven** [comment] 2019-07-08 22:01
Closing this because it doesn't seem like an issue with Apollo Server itself.

**Closed by martijnwalraven** 2019-07-08 22:01 UTC
Labels: :rose: has-reproduction
