### ISSUE TITLE
Unable to determine event source based on event

### ISSUE THREAD

**Issue by alakdam07** [apollographql/apollo-server#6179] opened 2022-03-05 07:33 UTC
I am using [apollo-server-lambda](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-lambda) for my app. I have create custom authoization http headers and it is required . if `authoization: LETMEIN` then it will return true and also return all data, if there is no any `authoization` or wrong `authoization` then it wll throw an error. For local development I used [serverless-offline](https://www.serverless.com/plugins/serverless-offline).In Local environment, it works as expected and here is the [image][1] but when I deploy my code to AWS, the api end does not work. It always throws me the error:  here is the [link](https://0gdih9yldd.execute-api.eu-north-1.amazonaws.com/development/api/v1/graphql). 

I test my function AWS console. I am getting this error:

[![enter image description here][2]][2]

**I did not get what I am doing wrong.**

**Here is my code**

    /* eslint-disable @typescript-eslint/no-var-requires */
    import { ApolloServerPluginLandingPageGraphQLPlayground } from 'apollo-server-core';
    import { ApolloServer, AuthenticationError } from 'apollo-server-lambda';
    import schema from '../graphql/schema';
    import resolvers from '../resolvers';
    import runWarm from '../utils/run-warm';

    export const authToken = (token: string) => {
      if (token === 'LETMEIN') {
        return;
      } else {
        throw new AuthenticationError('No authorization header supplied');
      }
    };

    const server = new ApolloServer({
      typeDefs: schema,
      resolvers,
      debug: false,
      plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
      context: ({ event }) => {
        //console.log(context);

        if (event.headers) {
          authToken(event.headers.authorization);
        }
      },
    });

    export default runWarm(
      server.createHandler({
        expressGetMiddlewareOptions: {
          cors: {
            origin: '*',
            credentials: true,
            allowedHeaders: ['Content-Type', 'Origin', 'Accept'],
            optionsSuccessStatus: 200,
            maxAge: 200,
          },
        },
      })
    );

**This is my lambda warmup**

    /**
     * Running warm functions help prevent cold starts
     */
    const runWarm =
      (lambdaFunc: AWSLambda.Handler): AWSLambda.Handler =>
      (event, context, callback) => {
        // Detect the keep-alive ping from CloudWatch and exit early. This keeps our
        // lambda function running hot.
        if (event.source === 'serverless-plugin-warmup') {
          return callback(null, 'pinged');
        }
        return lambdaFunc(event, context, callback);
      };

    export default runWarm;

  [1]: https://i.stack.imgur.com/9aeUZ.png
  [2]: https://i.stack.imgur.com/4qXVp.png

**Comment by glasser** [comment] 2022-03-08 21:43
Does the same issue happen without your auth token check and/or without runWarm? ie, is this a minimal reproduction or can you simplify it further?

What AWS product are you running your Lambda function behind? We support a few specific products like API Gateway. We have an open PR to improve the docs at https://github.com/apollographql/apollo-server/pull/5789

**Comment by glasser** [comment] 2022-03-08 21:44
Also is the issue that it *always* throws that error or only without that header?

**Comment by alakdam07** [comment] 2022-03-10 11:13
Really sorry for late reply.


>  I removed the runWarm plugin still throwing me the error.
> reproduce the code and here is the link:  https://github.com/alakdam07/lambda-graphql
> I pushed this above code to cloud and still getting this error: https://i4m96hm2kb.execute-api.eu-north-1.amazonaws.com/development/api/v1/graphql

**Comment by glasser** [comment] 2022-03-10 20:35
Can you provide a detailed list of steps for how you reproduce this? eg the README talks about `npm run serve`; can the problem be reproduced with that, or only in the cloud? Does the issue happen when you use Playground, or some sort of manual GraphQL post? Are you including your special header when the issue occurs, or not including it? etc.

**Comment by alakdam07** [comment] 2022-03-11 09:17
Issue can only reproduce only in **the cloud**.
**This is basically all my code**
```
import { ApolloServerPluginLandingPageGraphQLPlayground } from ‘apollo-server-core’;
import {
  ApolloServer,
  AuthenticationError,
  ForbiddenError,
  gql,
} from ‘apollo-server-lambda’;
import * as R from ‘ramda’;
const typeDefs = gql`
  type Query {
    hello: String
  }
`;
const resolvers = {
  Query: {
    hello: () => ‘Hello world!’,
  },
};
export const authToken = (token: string) => {
  if (token === ‘HELLO’) {
    return true;
  } else {
    throw new AuthenticationError(‘No authorization header supplied’);
  }
};
const server = new ApolloServer({
  typeDefs,
  resolvers,
  debug: false,
  plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
  context: ({ event }) => {
    if (R.isNil(event.headers.authorization)) // IF THERE IS NO ANY `headers.authorization` throw this error.
      throw new ForbiddenError(‘You must be authenticated’);
    return authToken(event.headers.authorization); // this function  returns true. if headers.authorization === ‘HELLO’ return true if something else throw error
  },
  introspection: true,
});
exports.graphql = server.createHandler({
  expressGetMiddlewareOptions: {
    cors: {
      origin: ‘*’,
      credentials: true,
      allowedHeaders: [‘Content-Type’, ‘Origin’, ‘Accept’, ‘authorization’],
      optionsSuccessStatus: 200,
      maxAge: 200,
      exposedHeaders: [‘authorization’],
    },
  },
});
```
**This is local environment playground  👇🏾👇🏾👇🏾**

https://user-images.githubusercontent.com/47625626/157837881-d2ea41de-c59a-4cef-bda8-8c5852105336.mov


**This is in the cloud, it returns first condition IF THERE IS NO ANY `headers.authorization` throw error.  Commented that condition in the code**

https://user-images.githubusercontent.com/47625626/157837978-265326d3-8db3-4d0e-acdc-0877d0de7706.mov

**Comment by glasser** [comment] 2022-03-11 21:06
I'm sorry, this isn't enough to let me run it myself in my own cloud or local environment so it's still hard for me to investigate. Are you saying that the same invocation does both of these things:
- Returns a `You must be authenticated` error to the user (ie, implies that your `context` function is actually running)
- Logs the "Unable to determine event source based on event" error message

This is surprising to me since my understanding of how the Lambda layer works is that the code that would call getEventSourceNameBasedOnEvent would get called a lot earlier than the context function. So it's hard for me to reason more about what's happening here in the abstract.

**Comment by glasser** [comment] 2022-03-11 22:35
Going to close this for now since I haven't been able to experiment with it myself. If there are very detailed instructions saying exactly how to deploy it to my own AWS account I'd reopen.

**Closed by glasser** 2022-03-11 22:35 UTC

**Comment by alakdam07** [comment] 2022-03-12 06:17
Thank you for spending time for my matters🙏🏾🙏🏾. I found better solution 😌

**Comment by Pigius** [comment] 2022-04-11 10:59
@alakdam07 can you share your better solution?

**Comment by alakdam07** [comment] 2022-04-11 11:10
I create an authorization function and attached to the lamda. Like this:

```
  graphql:
    handler: src/handlers/graphql.graphql
    events:
      - http:
          path: ${self:service, 'dev'}/graphql
          method: get
          cors: true
      - http:
          path: ${self:service, 'dev'}/graphql
          method: post
          cors: true
          authorizer: AuthFunction // below is the auth function 
  ## Authorization function
  AuthFunction:
    handler: src/auth/auth.auth
```

This is the `auth` function. 
```
import { APIGatewayTokenAuthorizerEvent } from 'aws-lambda';

exports.auth = async (event: APIGatewayTokenAuthorizerEvent) => {
  const token = event.authorizationToken.toLowerCase();
  const methodArn = event.methodArn;

  console.log(token);

  switch (token) {
    case 'allow':
      return generateAuthResponse('user', 'Allow', methodArn);
    default:
      return generateAuthResponse('user', 'Deny', methodArn);
  }
};

function generateAuthResponse(
  principalId: string,
  effect: string,
  methodArn: string
) {
  const policyDocument = generatePolicyDocument(effect, methodArn);

  return {
    principalId,
    policyDocument,
  };
}

function generatePolicyDocument(effect: string, methodArn: string) {
  if (!effect || !methodArn) return null;

  const policyDocument = {
    Version: '2012-10-17',
    Statement: [
      {
        Action: 'execute-api:Invoke',
        Effect: effect,
        Resource: methodArn,
      },
    ],
  };

  return policyDocument;
}
```

The headers will be

```
{
  "Authorization": "Allow"
}
```

**Comment by alakdam07** [comment] 2022-04-11 11:17
Here is nice doc about `authorizer` : https://www.serverless.com/framework/docs/providers/aws/events/apigateway
