### ISSUE TITLE
INTERNAL_SERVER_ERROR is thrown when mutation variables are of invalid type

### ISSUE THREAD

**Issue by fhpriamo** [apollographql/apollo-server#3361] opened 2019-10-01 23:42 UTC
I guess this issue is related to #1410 and #2204.

The problem occurs in the package apollo-server at version 2.8.2.

An error being thrown inside the scalar evaluation code is being treated like an INTERNAL_SERVER_ERROR, when in fact it should be treated like a GRAPHQL_VALIDATION_FAILED or something like that. This issue occurs when dealing with variables in the graphql query/mutation. Somehow, the value of the variable manages to pass through schema validation and ends up causing trouble further up.

[Here is a reproduction on CodeSandbox](https://codesandbox.io/embed/apollo-server-eisg9)

Although my code is a little bit more complex than the example I cooked up in CodeSandbox, I think it shows the nature of the problem.

I really hope this get solved.

Thank you guys, you're awesome!

**Comment by geovanevital** [comment] 2019-11-04 20:44
Had the same issue here, did you found any solutions?

Thanks!!

**Comment by glasser** [comment] 2021-04-06 22:53
Duplicate of #3498

**Closed by glasser** 2021-04-06 22:53 UTC
Labels: :pear: error-handling

**Comment by glasser** [comment] 2021-04-09 00:06
I've released a prerelease with this fix, version `2.23.0-alpha.0`. Try out the alpha and see if it works for you! Please provide any feedback in #5094.

**Comment by glasser** [comment] 2021-04-14 23:25
This is released in Apollo Server 2.23.0.
