### ISSUE TITLE
Express Charset in Content-Type Header

### ISSUE THREAD

**Issue by wyattjoh** [apollographql/apollo-server#652] opened 2017-10-30 21:36 UTC
While the JSON output from the following certainly outputs a UTF-8 encoded string:

https://github.com/apollographql/apollo-server/blob/197cf6802c16dc92c25f14f78de89b89f2f8afb3/packages/apollo-server-express/src/expressApollo.ts#L35-L38

It still does not write the correct headers when serving the output. I'm proposing that it should be changed to read:

```js
res.setHeader('Content-Type', 'application/json; charset=utf-8');
```

To reflect the output encoding especially given the fact that it's recommended by the express wiki to do so: https://github.com/expressjs/express/wiki/Migrating%20from%203.x%20to%204.x#rescharset

**Comment by ApricumMedia** [comment] 2018-09-05 11:36
I don't understand, does Apollo itself not establish a `utf8` charset for the connection or might that be an issue with the GraphQL playground?

![screen shot 2018-09-05 at 13 35 41](https://user-images.githubusercontent.com/7656669/45090798-ac1d6200-b110-11e8-869e-bb416dc45bb2.png)

**Comment by abernix** [comment] 2019-02-19 14:22
I'm fairly sure that JSON is required by specification to be encoded as Unicode (e.g. UTF-8, UTF-16 or UTF-32) so providing a UTF encoding seems reasonable, particularly since we're already encoding the data itself using `utf8`.  It was tempting to also think about considering byte-length savings which might be achieved for some character sets by using UTF-16, but that seems like a concern we could store separately.  The goal of this PR seems to be to make sure that we're expressing what encoding we're using internally to the client which is consuming it, which seems right to me.

That said, I suspect **we'd happily welcome a PR that made this change** to the `apollo-server-express` integration (and ideally, the other integrations as well, even though it's only reported here within the scope of `express`), though I'm curious if anyone has any insight on whether or not this would be a breaking change.  It would be desirable if any such PR also include some research to confirm that some range of clients will continue to behave properly if we start returning this additional `charset=` parameter on the `Content-type`.  I suspect they probably will work fine since they would be likely be broken if they expected any `charset` other than UTF-8.

PRs welcome!

**Comment by jhampton** [comment] 2019-07-08 20:36
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.  The Express integration has changed, and the inclusion of gateway changes how responses might be configured.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by jhampton** 2019-07-08 20:36 UTC
Labels: 🖇️ express, 🙏 help-wanted, 🚧👷‍♀️👷‍♂️🚧 in triage
