### ISSUE TITLE
Not found error with Express route but it works!

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-server#1523] opened 2018-08-11 17:23 UTC
I have a problem with my `express` app:

https://glitch.com/edit/#!/enthusiastic-velociraptor

When I navigate to `GET` `/graphql` it gives me Playground but in console I have a `Not found`

Why?

Reproducible with these steps:

- go to: https://glitch.com/edit/#!/enthusiastic-velociraptor
- see the code and open console
- go to: https://enthusiastic-velociraptor.glitch.me/graphql
- Graphql Playground works but in console you have "Not found" error!

**Comment by sbrichardson** [comment] 2018-08-11 18:12
I don't get it, I would check the network tab. Not Found on the base route shows up because there isn't a favicon, but that's typical if you don't handle that case. No issue other than the favicon on the base route for me.

**Comment by frederikhors** [comment] 2018-08-11 18:17
Not. It's not the favicon the problem. Try to go back and forward in the browser!

**Comment by sbrichardson** [comment] 2018-08-12 04:40
I thought Express error handler is called specifically with 4 arguments?
You are calling it on all routes I think, so change it to:

```
app.use(function(err, req, res, next) {
  next(createError(404))
})
```

From https://expressjs.com/en/guide/error-handling.html

> Writing error handlers
> Define error-handling middleware functions in the same way as other middleware functions, except error-handling functions have four arguments instead of three: (err, req, res, next). For example:

```
app.use(function (err, req, res, next) {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
```

**Comment by sbrichardson** [comment] 2018-08-12 04:56
It looks like you are adding a middleware on all routes, to call 404?

The error handler in Express is only invoked when it has 4 arguments (err, req, res, next).

Or you can add a catchall to the router stack instead of adding to app. Quick glance, may not be correct.

https://stackoverflow.com/questions/11500204/how-can-i-get-express-js-to-404-only-on-missing-routes

**Comment by frederikhors** [comment] 2018-08-13 15:51
I think I'm good as it is. Because I started a new express-generator app with:

`express --view=pug myapp`

and it wrote these files:

./app.js:

![image](https://user-images.githubusercontent.com/41120635/44042432-89bd2d1e-9f20-11e8-943f-000b275c7e12.png)


and routes/index.js:

![image](https://user-images.githubusercontent.com/41120635/44042408-79352aaa-9f20-11e8-87e4-f5292a3222e4.png)

You can try it with:

- `npm install express-generator -g`
- `express --view=pug myapp`

I have and I think the problem is just with `apollo-server`.

**Comment by frederikhors** [comment] 2018-08-13 16:41
I found this problem: https://stackoverflow.com/questions/51826711/express-js-error-handler-doesnt-work-if-i-remove-next-parameter

But now the error handler with `next` works, and I have the same problem with different error:

`Error: /app/views/error.hbs: Can't set headers after they are sent.`

![image](https://user-images.githubusercontent.com/41120635/44045300-64e15d3c-9f28-11e8-83ac-d59d2131a221.png)

Reproducible with these steps:

- go to: https://glitch.com/edit/#!/enthusiastic-velociraptor
- see the code and **open console**
- go to: https://enthusiastic-velociraptor.glitch.me/graphql
- Graphql Playground works but in console you have the error!

**Comment by JacksonKearl** [comment] 2019-07-01 22:41
Closing this for now as it's quite old and it seems to be an error in how you're using express. If you still need help feel free to reopen and let us know updated steps on how to reproduce it!

**Closed by JacksonKearl** 2019-07-01 22:41 UTC
