### ISSUE TITLE
[gateway@0.14.0] Schema doesn't roll forward in managed mode.

### ISSUE THREAD

**Issue by rtymchyk** [apollographql/apollo-server#3976] opened 2020-04-11 22:23 UTC
**Package Version**
`@apollo/gateway 0.14.0`
`apollo-server 2.12.0`

**Previous Working Package Version**
`@apollo/gateway 0.13.2`
`apollo-server 2.11.0`

**Actual Behaviour**
_Boot Message_
```
Error checking for changes to service definitions: When `serviceList` is not set, an Apollo Engine configuration must be provided. See https://www.apollographql.com/docs/apollo-server/federation/managed-federation/ for more information.
```

_Push Service Update (command)_
```
The gateway for the 'nl-web-graph@staging' graph was NOT updated with a new schema
```

_Push Service Update (gateway)_
```
(no log message)
```

**Expected Behaviour**
_Boot Message_
```
Sat Apr 11 2020 22:16:55 GMT+0000 (Coordinated Universal Time) apollo-gateway: Gateway successfully loaded schema.
* Mode: managed
* Service: nl-web-graph@production
```

_Push Service Update (command)_
```
The gateway for the 'nl-web-graph@production' graph was updated with a new schema, composed from the updated 'nl-api' service
```

_Push Service Update (gateway)_
```
Sat Apr 11 2020 22:16:55 GMT+0000 (Coordinated Universal Time) apollo-gateway: Gateway config has changed, updating schema
```

**Setup**
```javascript
const apolloServer = new ApolloServer({
  gateway,
  subscriptions: false,
  engine: {
    apiKey: config.get('engine.apiKey'),
    schemaTag: config.get('appEnv'),
  },
})
```

```javascript
const gateway = new ApolloGateway({
  buildService({ name, url }) {
    switch (name) {
      case config.get('services.first.name'):
        return new SomeApiDataSource({ url })
      case config.get('services.second.name'):
        return new AnotherApiDataSource({ url })
    }
  },
)
```

Note that I have `ENGINE_API_KEY` ENV set and I also pass it to the server initializer.

**Comment by rtymchyk** [comment] 2020-04-11 23:01
At first, I thought this was just a log message problem, but it looks deeper.

It can connect to the Graph Manager to get the initial schema, but the gateway fails to get updated on service pushes.

**Comment by rtymchyk** [comment] 2020-04-13 15:35
@abernix @trevor-scheer I've looked through all the PRs that were shipped in 0.14.0 but wasn't able to spot an issue. If there's something wrong with my configuration above please let me know :)

**Comment by trevor-scheer** [comment] 2020-04-13 16:52
@rtymchyk description (actual behavior) seems to imply the service failed to update at all when you run `service:push` from the CLI. However, if it's actually the case that the previous working version of gateway doesn't have any issue then I'll need to get a reproduction together.

I'm stepping away for ~1hr so if you somehow see this and have time to share a reproduction with me that would be wonderful, otherwise I'll be taking a look when I'm back. Thank you for reporting!

**Comment by trevor-scheer** [comment] 2020-04-13 19:28
@rtymchyk I've got a reproduction of this now, working on identifying the issue and putting together a fix.

**Comment by rtymchyk** [comment] 2020-04-13 19:46
Sorry @trevor-scheer, just saw the first message. Thanks for digging into it! Let me know if I can help with anything.

**Comment by abernix** [comment] 2020-04-14 12:04
I've just published `@apollo/gateway@0.14.1-alpha.0` with the fix provided by @trevor-scheer in #3979.

Could you please try installing it and seeing if it resolves this problem for you?

(It's published on the npm "`next`" tag, but you can also just install it directly — e.g. `npm install @apollo/gateway@0.14.1-alpha.0` or `yarn add @apollo/gateway@0.14.1-alpha.0`)

**Comment by rtymchyk** [comment] 2020-04-14 13:20
> I've just published `@apollo/gateway@0.14.1-alpha.0` with the fix provided by @trevor-scheer in #3979.
> 
> Could you please try installing it and seeing if it resolves this problem for you?
> 
> (It's published on the npm `next` tag, but you can also just install it directly — e.g. `npm install @apollo/gateway@0.14.1-alpha.0` or `yarn add @apollo/gateway@0.14.1-alpha.0`)

Wonderful, I'll give this a shot a bit later and report back.

**Comment by abernix** [comment] 2020-04-14 13:38
Please do report back! Since we're confident that this at least fixes https://github.com/apollographql/apollo-server/issues/3982 (which is related), I've gone ahead and graduated this release to `@apollo/gateway@0.14.1` and published it on `latest`.

Thanks so much for reporting this originally.  Please do close this issue if you find the `0.14.1` release resolves it for you.

**Comment by rtymchyk** [comment] 2020-04-14 16:33
@abernix the boot sequence seems solid now, but I'm not sure how to read service update logs (and I never paid much attention to them till now)

For example, is this normal when doing a `service:push`?
```
The 'nl-api' service for the 'nl-web-graph@staging' graph was updated
The gateway for the 'nl-web-graph@staging' graph was NOT updated with a new schema
```

(assuming there were no changes to the graph)

**Comment by rtymchyk** [comment] 2020-04-16 21:55
@abernix @trevor-scheer The seems fixed, but I just want to double-check that the above output for service pushes is as expected. 

Thank you for the super quick response to this issue by the way.

**Comment by trevor-scheer** [comment] 2020-04-17 00:08
@rtymchyk did you have composition errors? This is normal, but your composed schema was *not* updated as the messaging says. It's possible to get your managed schema into a "limbo" state, if you will. Graph Manager will update the composed schema once you've resolved all composition errors. Usually, for example, this requires updating a different service.

I can be more helpful if you paste the full output of the command. Also, I'd recommend using `service:check` as well to gain a better understanding of your graph's current state.

**Comment by trevor-scheer** [comment] 2020-04-17 00:12
@rtymchyk The gateway has a configuration point for observing composition changes via a hook. It's undocumented for now as the lifecycle hooks are still experimental, but you can see the API / types here:

https://github.com/apollographql/apollo-server/blob/84fdcafd0b9024cf64ae88fedd52ec7adaf8c11f/packages/apollo-gateway/src/index.ts#L61

https://github.com/apollographql/apollo-server/blob/84fdcafd0b9024cf64ae88fedd52ec7adaf8c11f/packages/apollo-gateway/src/index.ts#L130-L133

**Closed** 2020-04-17 00:12 UTC
Labels: :beetle: bug, 👩‍🚀 federation

**Comment by rtymchyk** [comment] 2020-04-17 00:29
@trevor-scheer so there are no composition errors, this was basically a service push that is no-op since the graph did not change. I think I'm just reading too much into that message, will check this out again on deploy with actual graph changes and see. Thanks for your response and help with everything.
