### ISSUE TITLE
lambda: playground Server cannot be reached

### ISSUE THREAD

**Issue by Kcin1993** [apollographql/apollo-server#2136] opened 2018-12-26 08:23 UTC
Hi team,

### Intended outcome

Using `"apollo-server-lambda": "^2.3.1"` expect the playground work fine.

---

### Actual outcome

Outcome in Playground webiste right side show 
```
{
  "error": "Response not successful: Received status code 403"
}
```

Check the browser console. The network's response in playground is `{"message":"Forbidden"}`

Note. I can test my graphQL api with curl command or aws lambda test. Only playground can not work fine.

---

### How to reproduce the issue

Here is my serverless.yml
```yml
service: jk-bot

custom:
  BOT_FB: "jk-bot-fb-table"

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["JkBotFb", "Arn"] }
  environment:
    BOT_FB: ${self:custom.BOT_FB}

resources:
  Resources:
    JkBotFb:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.BOT_FB}

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: POST
          cors: true
      - http:
          path: graphql
          method: GET
          cors: true
```

Here is my handler.js
```javascript
const { ApolloServer, gql } = require("apollo-server-lambda");
const { botTypeDef, botResolvers } = require("./models/bot");

const typeDefs = gql`
  ${botTypeDef}
`;
const resolvers = botResolvers;

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ event, context }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context
  }),
  playground: {
    settings: {
      "request.credentials": "same-origin"
    }
  }
});

exports.graphql = server.createHandler({
  cors: {
    origin: "*",
    credentials: true
  }
});
```

### Issue might relative
* https://github.com/apollographql/apollo-server/issues/1500
* https://github.com/prisma/graphql-playground/issues/748
* https://github.com/prisma/graphql-playground/issues/826

---

Could anyone help this situation. Any better idea?

**Comment by taogilaaa** [comment] 2019-01-29 09:15
I also encounter this, It looks like `stage` inside `serverless.yml` is causing this issue

When we access the playground, it points to the wrong url (without stage)
![image](https://user-images.githubusercontent.com/11565866/51896560-56a76180-23df-11e9-8555-f13a8b977e9e.png)

Here is the `event` log from the cloudwatch
![image](https://user-images.githubusercontent.com/11565866/51896943-22807080-23e0-11e9-849a-82784daab289.png)
![image](https://user-images.githubusercontent.com/11565866/51897243-e7327180-23e0-11e9-88a3-66eaf2bdf96b.png)

**Comment by taogilaaa** [comment] 2019-01-29 09:17
I also encounter this, It looks like `stage` inside `serverless.yml` is causing this issue

When we access the playground, it points to the wrong url (without stage)
![image](https://user-images.githubusercontent.com/11565866/51896560-56a76180-23df-11e9-8555-f13a8b977e9e.png)

Here is the `event` log from the cloudwatch
![image](https://user-images.githubusercontent.com/11565866/51896943-22807080-23e0-11e9-849a-82784daab289.png)
![image](https://user-images.githubusercontent.com/11565866/51897421-498b7200-23e1-11e9-8925-2caa129004b6.png)

**Comment by abernix** [comment] 2019-07-16 15:54
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Comment by abernix** [comment] 2019-07-29 02:04
I'll re-open this since it still has a corresponding PR (https://github.com/apollographql/apollo-server/pull/2241).  If any of the _many_ folks who have 👍 'd the above comment could chime in on that PR to help clarify how it _wouldn't_ be a breaking change (i.e. `event.requestContext.path` taking precedence over `event.path` instead of the previous behavior of the opposite), I'd really appreciate it!

Perhaps it's just a matter of how the Lambda is invoked, but I'd love some input from those that use the `apollo-server-lambda` package more than I do!

**Comment by phoenecke** [comment] 2019-10-26 02:58
Manually adding the stage seems to at least gets it working.
![image](https://user-images.githubusercontent.com/4790779/67613387-d69a0680-f77a-11e9-951c-3b05f7172026.png)

**Comment by DrYSG** [comment] 2019-11-11 15:51
Can you fix the page? (https://www.apollographql.com/docs/apollo-server/deployment/lambda/  I ran into the same issue as this guy about the missing /dev in the url. Took me a while to find the fix.
https://stackoverflow.com/questions/57741390/error-with-message-forbidden-trying-to-query-an-apollo-serverless-lambda-se

**Comment by Mellbourn** [comment] 2020-02-02 22:10
This problem seems to still be a thing. I'm using AWS SAM, so I don't have a serverless.yaml file to fix.
Here is my project with this problem: https://github.com/Mellbourn/saved-counter

**Comment by taogilaaa** [comment] 2020-02-03 02:11
@Mellbourn you might want to try this workaround on your exported handler

```js
exports.graphql = (event, lambdaContext, callback) => {
  // Playground handler
  if (event.httpMethod === 'GET') {
    server.createHandler()(
      {...event, path: event.requestContext.path || event.path},
      lambdaContext,
      callback,
    );
  } else {
    server.createHandler()(event, lambdaContext, callback);
  }
};
```

[file for context](https://github.com/taogilaaa/serverless-basic-graphql/blob/master/src/handler.js#L25-L37)

**Comment by Mellbourn** [comment] 2020-02-03 20:03
@taogilaaa that worked right away. Thank you!

**Comment by glasser** [comment] 2022-10-04 22:22
In Apollo Server v3.0.1 we changed serverless integrations such as Lambda to not care about the URL path any more. (In Apollo Server v4 (currently a Release Candidate) no integrations care about the URL path, and the Lambda integration is no longer part of the core project.)) So I do not believe this is an issue any more.

**Closed by glasser** 2022-10-04 22:22 UTC
Labels: :beetle: bug, 🖇️ lambda
