### ISSUE TITLE
Input variable validiations for object values are throwing InternalServerError

### ISSUE THREAD

**Issue by asafigan** [apollographql/apollo-server#1410] opened 2018-07-24 14:31 UTC
When passing a object as a input variable, validation on the input type throws internal server error rather than a validation or graphql error.

message:
`Variable "$review" got invalid value {"communication":0,"quality":0,"value":0,"creativity":0,"title":"","partnerId":"sldkj"}; Field value.details of required type String! was not provided.`

error code: 
`INTERNAL_SERVER_ERROR`

**Comment by jbaxleyiii** [comment] 2019-07-08 21:05
Thanks for reporting this issue originally!

If this is still a problem, could someone who's experiencing this problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back with a reproduction.  Thanks!

**Closed by jbaxleyiii** 2019-07-08 21:05 UTC
Labels: :beetle: bug, 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by fhpriamo** [comment] 2019-10-01 23:15
Well, I'm having the same problem. Although my code is little bit more complex than the example I cooked up in CodeSandbox, I think it shows the nature at the problem.

To my understanding, an error ocuring inside the scalar evaluation code is being treated like an `INTERNAL_SERVER_ERROR`, when in fact it should be treated like a `GRAPHQL_VALIDATION_FAILED` or something like that. This occurs when dealing with variables in the graphql query/mutation. The value of the variable manages to pass through schema validation and ends up in causing trouble further up.

[Here is the CodeSandbox app](https://codesandbox.io/embed/apollo-server-eisg9)

I really hope this get solved.

Thanks you guys, you're awesome!

**Comment by glasser** [comment] 2021-04-06 22:53
Duplicate of #3498

**Comment by glasser** [comment] 2021-04-09 00:06
I've released a prerelease with this fix, version `2.23.0-alpha.0`. Try out the alpha and see if it works for you! Please provide any feedback in #5094.

**Comment by glasser** [comment] 2021-04-14 23:25
This is released in Apollo Server 2.23.0.
