### ISSUE TITLE
POST 400 between apollo-server-lambda <-> GraphQL

### ISSUE THREAD

**Issue by mj-dcb** [apollographql/apollo-server#5771] opened 2021-10-01 10:18 UTC
**Package name:** `"apollo-server-lambda": "^3.3.0",`

**Expected behavior:**
A user registers an account on our platform(NextJS), the request will be pushed by Apollo client to the API Gateway and will be processed by AWS Lambda. A new account will be registered and the user can continue with their journey.

To simplify things, this is how the flow would look like (technically speaking): Apollo Client -> API Gateway -> AWS Lambda

**The actual behavior:**
This flow worked until yesterday evening. We received feedback from users that couldn't register their account, they click on the Register button, it loads, but then they get a 400 ERROR.
![Screenshot 2021-10-01 at 12 14 23](https://user-images.githubusercontent.com/81908549/135603756-48890e67-f787-453c-bec1-58ffbd974758.png)

We have checked the API logs from AWS, we did notice an increase in API calls but couldn't find errors or things that could be related to AWS, hence this issue @apollo-server.

This is what see at the API Gateway dashboard:
![image](https://user-images.githubusercontent.com/81908549/135604090-cd00a4d8-7a66-414d-8bb6-c7cc4a7ca63f.png)

If we zoom in on the API calls chart, then we get this:
![image](https://user-images.githubusercontent.com/81908549/135604160-308914b4-7c4e-48a8-a2bd-5a712c9f4518.png)

**Comment by glasser** [comment] 2021-10-01 17:51
I'm not sure if there's much for us to investigate here. It looks like you had a big spike in requests — could that have caused other issues? I don't understand if you're able to reproduce this yourself or not; if you can, can you show the complete contents of the 400 response (headers and body)?  I don't think there's enough detail for us to do any real investigation so I'm going to close this, but happy to reopen if it becomes more reproducible.

**Closed by glasser** 2021-10-01 17:51 UTC
