### ISSUE TITLE
formatResponse no use

### ISSUE THREAD

**Issue by yuu2lee4** [apollographql/apollo-server#2030] opened 2018-11-27 07:20 UTC
After upgrading to 2.2.3 from 2.1.0,formatResponse function doesn't take effect

**Comment by abernix** [comment] 2018-11-27 10:07
Could you please create a runnable reproduction of this problem via [CodeSandBox w/ Apollo](codesandbox.io/s/apollo-server)?

Be sure to set the correct version of `apollo-server` as a dependency, and provide the link to the CodeSandbox reproduction back in this issue.  Thanks!

**Comment by joaquinmoreira** [comment] 2018-12-20 02:30
duplicate of #2068 ?

**Comment by yuu2lee4** [comment] 2019-02-15 03:24
not fixed in 2.4.0

**Comment by yuu2lee4** [comment] 2019-02-15 03:35
in 2.1.0,my formatResponse like this: 
````javascript
formatResponse(data) {
   return {
      data: data.data,
      code: 0,
      time: Date.now() / 1000,
   };
}
````
but in 2.4.0,i can't get `code`、`time` except for `data`, when i modify formatResponse like this:
````javascript
formatResponse(data) {
   return {
          data: {
            data: data.data,
            code: 0,
            time: Date.now() / 1000,
      },
   };
}
````
i can get all fileds but the structure is not what i want.

**Comment by martijnwalraven** [comment] 2019-03-22 09:25
We haven't been as strict about this in the past, but the object you return from `formatResponse` has to be a valid GraphQL response, and `data`, `errors`, and `extensions` are the only top-level fields allowed (see [this description of the response format in the spec](
https://facebook.github.io/graphql/draft/#sec-Response-Format)). So if you want to return additional fields, you should nest these under `extensions`.

**Comment by martijnwalraven** [comment] 2019-07-08 20:26
Closing this issue, see previous response.

**Closed by martijnwalraven** 2019-07-08 20:26 UTC
