### ISSUE TITLE
Apollo Error Code lost when using mergeSchemas

### ISSUE THREAD

**Issue by ksmithut** [apollographql/apollo-server#1582] opened 2018-08-27 01:06 UTC
It is expected that the error codes and other error extensions maintain themselves when returning to the client. When using mergeSchemas, when a custom error is thrown using ApolloError, the error code is lost. Although it's understandable why this might happen when merging remote schemas, this even happens with local schemas. An example server (or set of servers) and example curl requests show the difference in results:

To reproduce, run:

```
mkdir apollo-server-error-test && cd $_
npm i apollo-server graphql
touch index.js
```

Put the following into `index.js`:

<details>
<summary>index.js</summary>

```js
const {
  ApolloServer,
  ApolloError,
  makeExecutableSchema,
  mergeSchemas,
  gql
} = require('apollo-server')

const schema = makeExecutableSchema({
  typeDefs: gql`
    type Query {
      available: Boolean!
    }
  `,
  resolvers: {
    Query: {
      available() {
        throw new ApolloError('some error', 'MY_CUSTOM_ERROR_CODE')
      }
    }
  }
})

const apolloServer = new ApolloServer({ schema })
apolloServer.listen(8000)

const apolloServerBadErrors = new ApolloServer({
  schema: mergeSchemas({ schemas: [schema] })
})
apolloServerBadErrors.listen(8001)
```
</details>

Then run `NODE_ENV=production node index` (production to suppress stack trace from output).

After that, run the following curl commands and you'll get the respective results:

---

```sh
# From "good" server
curl -X POST http://localhost:8000/graphql \
  -H 'Content-Type:application/json' \
  -H 'Accept:application/json' \
  -d '{"query":"query{available}"}' 
```

<details>
<summary>response</summary>

```json
{
  "data": null,
  "errors": [
    {
      "message": "some error",
      "locations": [{ "line": 1, "column": 7 }],
      "path": ["available"],
      "extensions": { "code": "MY_CUSTOM_ERROR_CODE" }
    }
  ]
}
```
</details>

---

```sh
# From "bad" server
curl -X POST http://localhost:8001/graphql \
  -H 'Content-Type:application/json' \
  -H 'Accept:application/json' \
  -d '{"query":"query{available}"}' 
```

<details>
<summary>response</summary>

```json
{
  "data": null,
  "errors": [
    {
      "message": "some error",
      "locations": [{ "line": 1, "column": 7 }],
      "path": ["available"],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errors": [
            { "message": "some error", "locations": [], "path": ["available"] }
          ]
        }
      }
    }
  ]
}
```
</details>

---

Perhaps this is as designed, but it would be awesome if there was a way to propagate error codes up through the mergeSchemas "firewall".

**Comment by ph55** [comment] 2018-12-27 12:40
I've opened bug in `graphql-tools`, not sure on whom side the fix.
https://github.com/apollographql/graphql-tools/issues/1037

**Comment by 8arcturus** [comment] 2019-01-09 01:09
Resolved for me after importing "extractExtensionDefinitions". https://github.com/apollographql/graphql-tools/issues/1037#issuecomment-452520704

**Comment by robertontiu** [comment] 2019-02-18 13:29
Is there a fix for this? We are providing some more information besides `code` under `extensions` but everything seems to be lost now that we are using `mergeSchemas`.

**Comment by abernix** [comment] 2019-02-20 16:26
@robertontiu I don't believe there's fix for this yet.  Would it be something you'd be interested in looking into?  I suspect (though I'm not certain; debugging would be required), the problem lies in the `graphql-tools` repository, possibly within one of the three different prongs of the conditional which starts off within the `schemas.forEach` loop here:

https://github.com/apollographql/graphql-tools/blob/641d7058fdf4b7af08a92a770c0b9a4f0febea29/src/stitching/mergeSchemas.ts#L100-L101

There are different forms of schemas that `graphql-tools` accepts, each with subtle intentional nuances.  One of those might be off?

**Comment by hwillson** [comment] 2019-03-07 18:20
Quick note - the original reproduction listed here no longer fails when using a modern day version of `apollo-server` (it was likely fixed by https://github.com/apollographql/graphql-tools/pull/637), but this problem still persists when the error is thrown a bit differently. Here's a new reproduction that shows the problem: https://github.com/hwillson/graphql-tools-stitching-errors

I'll work on addressing this in `graphql-tools`, and will post back here when the fix is ready.

**Comment by jbaxleyiii** [comment] 2019-07-08 21:56
This is fixed in newer versions

**Closed by jbaxleyiii** 2019-07-08 21:56 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage

**Comment by glasser** [comment] 2021-02-09 17:50
As mentioned on #4807, mergeSchemas is part of graphql-tools; the old version "conveniently" re-exported from Apollo Server is not maintained.
