### ISSUE TITLE
`apollo-server`'s stop() hangs when running in jest jsdom browser-emulation mode due to lack of timer.unref

### ISSUE THREAD

**Issue by nogashimoni** [apollographql/apollo-server#4933] opened 2021-02-16 14:22 UTC
- I write tests uning Jest + react testing library + jsdom 15. In one of the tests I use ApolloServer - I start it beforeAll and stop it after all.
When I used apollo-server version 2.19.0 everything worked as expected. When upgrading to  apollo-server version 2.21.0,
server.stop() hangs forever. I try using stopGracePeriodMillis and that doesn't work as well.

- [ apollo-server version 2.21.0 ] The package name and version of Apollo showing the problem.
- [ apollo-server version 2.19.0 ] The last version of Apollo where the problem did _not_ occur.
- [ server.stop() should work and stop the server ] The expected behavior.
- [ instead It's stuck and never reaches the following code ] The actual behavior.
- A **simple**, runnable reproduction!

```
import React from 'react';
import { gql } from '@apollo/client';
import { ApolloServer } from 'apollo-server';

// Just a random schema
const typeDefs = gql`  
  type Query {
    books: [Book]!
  }
  type Book {
    title: String
    author: Author
  }
  type Author {
    name: String
    books: [Book]
  }
`;

let mockServer;

beforeAll(async () => {
  mockServer = new ApolloServer({typeDefs});
  try {
    const { url } = await mockServer.listen({
      port: 0
    });
    console.log(`🚀 Server ready at ${url}`);
    return url;
  } catch (error) {
    console.error('Error running server', error);
    throw error;
  }
});

afterAll(async () => {
  await mockServer?.stop();
  console.log('stopped server'); // This line is never reached
});

describe('VesselName', () => {
  it('Does nothing', async () => {
  });
});
```

My guess is that this [change](https://github.com/apollographql/apollo-server/pull/4908) broke the stop functionality, maybe because the code runs from jsdom browser + jest, and stoppable might have [issues](https://github.com/hunterloftis/stoppable/issues/12) with it.

Update:
I think my guess is correct, I found this in the jsdom browser console:
```
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
    TypeError: setTimeout(...).unref is not a function
        at Immediate.<anonymous> (/Users/nogashimoni/Documents/projects/javascript/marint-ui/node_modules/stoppable/lib/stoppable.js:43:39)
        at processImmediate (internal/timers.js:461:21)
```

Thank you!

**Comment by nogashimoni** [comment] 2021-02-17 09:47
When I run the code **not** from jest, everything works fine and the server stops, so I assume it's related to the fact that I run this from Jest + react testing library, and that the code runs from jsdom .

(This works perfectly fine:
```
const React = require('react')
const { gql }  = require( '@apollo/client')
const { ApolloServer } = require('apollo-server');

// Just a random schema
const typeDefs = gql`  
  type Query {
    books: [Book]!
  }
  type Book {
    title: String
    author: Author
  }
  type Author {
    name: String
    books: [Book]
  }
`;

async function demo() {
  mockServer = new ApolloServer({typeDefs});
  try {
    const { url } = await mockServer.listen({
      port: 0
    });
    console.log(`🚀 Server ready at ${url}`);
  } catch (error) {
    console.error('Error running server', error);
    throw error;
  }
  await mockServer?.stop();
  console.log('stopped server'); // This line is reached when not running from Jest
}

demo();
```
)

**Comment by nogashimoni** [comment] 2021-02-17 10:36
Update: this is solved when using a newer jsdom when running jest.

jest-environment-jsdom-fourteen - stop doesn't work 
jest-environment-jsdom-fifteen - stop works! 

So I think you can close this issue.

**Comment by nogashimoni** [comment] 2021-02-17 20:10
Update - it seems like the code can't run from jsdom. 
The solution for me now is to add a polyfill for setTimeout(...).unref, like so:

```
  const setTimeoutProto = window.setTimeout().__proto__;
  if (!setTimeoutProto.unref) {
    setTimeoutProto.unref = function () {};
  }
  ```
  
  It's not a good solution, more like a patch, but it works for me and good enough for now.

**Comment by glasser** [comment] 2021-02-23 19:54
Hi, I appreciate the test file but since it sounds like this issue is very specific to the particular way you run jest with jsdom, is it possible to give a bit more context on how to run it?  eg maybe as a git repo I can clone, or something like codesandbox.io?

If the issue is unref, then one workaround would be to pass `stopGracePeriodMillis: Infinity` to `new ApolloServer`. This means that the new stoppable functionality will still kill *idle* HTTP connections but just won't kill ones that are actively running an HTTP request.  For a test, this actually seems like a reasonable approach since your tests probably won't end with active HTTP requests (and if they do, Jest's timeouts will kick in?).

I'm definitely also open to forking `stoppable` (either into `@apollographql/stoppable` or just copying the single file into this repo). I think we could replace the use of `unref` by calling clearTimeout from the `server.close` callback.

**Comment by glasser** [comment] 2021-02-23 20:03
Let's see if upstream takes https://github.com/hunterloftis/stoppable/pull/33
In the meantime, let me know if `stopGracePeriodMillis: Infinity` is a reasonable workaround.

**Comment by valentingavran** [comment] 2021-03-27 11:56
I have the same problem and it is still not fixed in version `2.22.1`.

In each jest test file I start the Apollo server in the beforeAll method and then I try to stop it in the afterAll method with `await server.stop()`.

Would be grateful if there are any other suggestions for solving this problem

**Comment by valentingavran** [comment] 2021-03-27 15:30
I have found a solution to this problem that I think is also much nicer. Instead of starting the server, I pass my server object to the `createTestClient` method of the `apollo-server-testing` library. Then I get a query and mutation method that I can use to test my resolvers.

You can read about the whole thing in the documentation here: https://www.apollographql.com/docs/apollo-server/testing/testing/

**Closed** 2021-07-26 19:53 UTC

**Comment by glasser** [comment] 2021-08-02 21:53
(In AS3.1, we inlined the `stoppable` package and made a bunch of improvements including fixing this issue.)
