### ISSUE TITLE
'graphqlError.extensions' is possibly 'undefined' in enrichError()

### ISSUE THREAD

**Issue by Yifeng-Sigma** [apollographql/apollo-server#7757] opened 2023-10-13 05:21 UTC
### Issue Description

https://github.com/apollographql/apollo-server/blob/252cb380bf84efb1688e5d8e4a64af42e467c787/packages/server/src/errorNormalize.ts#L64

'graphqlError.extensions' is possibly 'undefined'.

run into `Cannot read properties of undefined` error. 

### Link to Reproduction

The error can be seen compile time.
<img width="729" alt="image" src="https://github.com/apollographql/apollo-server/assets/86254270/08b12960-e20b-4fac-a6c0-c3638eccac95">

full error that apollo server returned:

<img width="1563" alt="image" src="https://github.com/apollographql/apollo-server/assets/86254270/1914ef94-bcd3-44c4-8539-7b2d403e0a6c">

**Comment by glasser** [comment] 2023-10-13 16:28
This isn't a full reproduction, because it relies on guessing what versions of dependencies you are using. I am specifically suspicious that you are using a version of `graphql` older than v16.6.0, which is the minimum version of `graphql` required for Apollo Server v4.  This field has been non-undefined in `graphql` [since v16.0.0](https://github.com/graphql/graphql-js/commit/b1ce2c3567fc34f351fe20cc73d098bfdd474ebc).

I'm closing this because it does not have a way for me to reproduce the problem you are seeing without creativity. If you are in fact using a supported version of `graphql`, please post a full reproduction (a series of instructions that probably start with `git clone` or a link to something like codesandbox.io) that allows us to see the error myself without having to make any guesses, and we'll reopen and investigate.

**Closed by glasser** 2023-10-13 16:28 UTC
