### ISSUE TITLE
TestClient doesn't receive Request object

### ISSUE THREAD

**Issue by lnmedrano** [apollographql/apollo-server#3158] opened 2019-08-14 14:44 UTC
Hello!
## Use case
My API receives an authorization token in a header in the request (an `ExpressRequest`). When writing tests I'm creating a test-client with an Apollo Server. 
The problem is that, since no Express -or any other- server is created, the `executeOperation` method from ApolloServer is only receiving the `GraphqlRequest`. The issue has been discussed here: https://github.com/apollographql/apollo-server/issues/2277  and here: https://github.com/apollographql/apollo-server/pull/2478.
I think it would be very useful to have the request available on the tests.

## Workarounds
There are some workarounds here in other issues (like setting the context inside of tests - https://github.com/apollographql/apollo-server/issues/2277 - , or getting the headers from the `GraphqlRequest` - https://github.com/apollographql/apollo-server/pull/2478 -)  but none of them solves the problem. Maybe, if the request is needed in tests, it is better to create an Apollo server with an Express -or any other- server, instead of using a `testClient`, but I think it would be better to have this option available in the `testClient`, so that is possible to do something like
```
createTestClient(
  new ApolloServer({
    schema,
    context: ({req}) => {
      doSomethingWithTheRequest(req);
      }
  })
);
```

Some possible solutions:
- Create a server in every test and pass the query object to the `executeOperation` method. This should be user's responsibility.
- Mock a request object in `executeOperation` with the information of the `GraphqlRequest`, but this mocked request should be different for each server.
- Make 'context' protected and implement a new class `ApolloServerBaseTesting` with a `setContext` method.

I would like to know if this is intentional or if is there a possibility to improve it. In that case what do you think it would be a good solution?

apollo-server version: 2.4.8

**Comment by abernix** [comment] 2019-08-26 19:25
I think you're right, but I think this still would be a duplicate of https://github.com/apollographql/apollo-server/issues/2277.  Please provide this input on that issue, rather than opening a new one!

**Comment by abernix** [comment] 2019-08-26 20:03
I see you have left feedback there.  I'll close this one, as I believe the other issue will suffice for tracking this.

**Closed by abernix** 2019-08-26 20:03 UTC
