### ISSUE TITLE
Graph Manager broken with apollo-server-lambda and serverless-offline

### ISSUE THREAD

**Issue by nathanchapman** [apollographql/apollo-server#3416] opened 2019-10-16 15:32 UTC
Package: `@apollo/gateway`
Version: tested every version since `v0.8.0` and all fail
Last known working version: `none`

Package: `apollo-server-lambda`
Version: tested every version since `v2.8.0` and all fail
Last known working version: `none`

When running `apollo-server-lambda` locally with [serverless-offline](https://github.com/dherault/serverless-offline) and using the [Graph Manager](https://www.apollographql.com/docs/graph-manager/federation/#managed-configuration), sometimes the first request to the server is successful. All subsequent requests fail with: `INTERNAL_SERVER_ERROR` `Invalid options provided to ApolloServer: Expected undefined to be a GraphQL schema.`, which will often lead to a crash.

When switching back to a locally configured `serviceList` things work fine.
Deploying the gateway to AWS Lambda also appears to work fine.

Similar issue, but not exactly the same: #3190

I'll have a repo demonstrating the reproduction soon (Bring Your Own ENGINE_API_KEY)

**Comment by debovenn** [comment] 2019-10-22 08:48
We are facing the same issue

**Comment by nathanchapman** [comment] 2019-12-18 19:55
Sorry for the delay! Here's the reproduction: https://github.com/nathanchapman/apollo-server-issue-3416

**Comment by nathanchapman** [comment] 2020-01-10 20:23
Edit: This appears to not only occur for managed graphs with serverless-offline, but both managed and unmanaged graphs when deployed to AWS Lambda 😞

**Comment by mikelyonsridgeline** [comment] 2020-01-16 00:06
we're running into this too. any remedy?

**Comment by abernix** [comment] 2020-05-05 07:34
This should be fixed in `@apollo/gateway@0.14.1` (it was actually fixed in `0.14.0`, but there's an important patch update for that release).

Using the reproduction above I was able to quickly verify that the problem was exhibited on versions prior to `0.14.0` and fixed using the `latest` versions of the `dependencies` listed in the reproduction, so thank you very much for providing the reproduction!

(In other words, I ran `npm install graphql@latest @apollo/federation@latest @apollo/gateway@latest apollo-server@latest apollo-server-lambda@latest`)

**Closed by abernix** 2020-05-05 07:34 UTC
Labels: :beetle: bug, :rose: has-reproduction, 👩‍🚀 federation, 🖇️ lambda
