### ISSUE TITLE
Investigate ESM support

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-server#6243] opened 2022-03-21 21:40 UTC
Apollo Server and friends are compiled for CJS. It would be nice to build for ESM as well.

Reference: https://community.apollographql.com/t/responsecacheplugin-is-not-a-function/2796/2

**Comment by glasser** [comment] 2022-03-22 23:37
https://github.com/benduran/package-bundler might be nice — a new tool inspired by how `@apollo/client` works.

**Comment by glasser** [comment] 2022-06-03 01:16
Note that as part of this we would probably want a separate entry point for `standalone` so we don't have to import express/cors/body-parser if we don't use it.

**Comment by alfaproject** [comment] 2022-06-04 14:10
FYI: this seems like a duplicate of https://github.com/apollographql/apollo-server/issues/5627
Should we close that one?

**Comment by glasser** [comment] 2022-06-06 20:05
(It would also be nice if we could drop `src/plugin/index.ts` while still keeping its advantages.)

@alfaproject technically #5627 is "do a thing" and #6243 is "consider doing a thing as part of the AS4 work" though they are certainly related.

**Comment by glasser** [comment] 2022-06-15 22:36
I think I have this working at https://github.com/apollographql/apollo-server/pull/6580

**Comment by glasser** [comment] 2022-06-21 17:49
This is finished with #6580. #6586 is a follow-up.

**Closed by glasser** 2022-06-21 17:49 UTC
