### ISSUE TITLE
Subscription resolver fail for nested fields since 3.0.0

### ISSUE THREAD

**Issue by geosigno** [apollographql/apollo-server#5565] opened 2021-08-02 10:25 UTC
Since I upgraded to Apollo Server 3, the subscription fail for any nested fields.

For examples, I got this subscription: 

```
subscription {
  live(id: "aaa") {
    id
    startDate
    startTime
    replay {
        id
    }
  }
}
```

The problem is with the `replay` field. If I remove it, this is working correctly. It's the same with any nested fields. I get the below error:

`TypeError: Cannot read property 'live' of undefined\n    at Object.replay (/Users/aaa/Desktop/projects/zsrc/model/Live/index.ts:44:16)\n    at field.resolve`

My resolver (model/Live/index.ts)
```
  replay: (node: any, args: any, ctx: Context) =>
    ctx.prisma.live.findUnique({ where: { id: node.id } }).replay(),
```
When printing the resolver in the console, I got my replay model filled.

And in the playground, I got the data I needed (for the example the new startTime, but nested in to the error results.

```
{
  "errors": [
    {
      "stack": "TypeError: Cannot read property 'live' of undefined\n    at Object.replay (/Users/aaasrc/model/Live/index.ts:44:16)\n    at field.resolve (/Users/aaanode_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:100:18)\n    at resolveField (/Users/aaanode_modules/graphql/execution/execute.js:464:18)\n    at executeFields (/Users/aaanode_modules/graphql/execution/execute.js:292:18)\n    at collectAndExecuteSubfields (/Users/aaanode_modules/graphql/execution/execute.js:748:10)\n    at completeObjectValue (/Users/aaanode_modules/graphql/execution/execute.js:738:10)\n    at completeValue (/Users/aaanode_modules/graphql/execution/execute.js:590:12)\n    at resolveField (/Users/aaanode_modules/graphql/execution/execute.js:472:19)\n    at executeFields (/Users/aaanode_modules/graphql/execution/execute.js:292:18)\n    at executeOperation (/Users/aaanode_modules/graphql/execution/execute.js:236:122)",
      "message": "Cannot read property 'live' of undefined",
      "name": "GraphQLError",
      "locations": [
        {
          "line": 17,
          "column": 5
        }
      ],
      "path": [
        "live",
        "replay"
      ],
      "nodes": [
        {
          "kind": "Field",
          "name": {
            "kind": "Name",
            "value": "replay",
            "loc": {
              "start": 285,
              "end": 291
            }
          },
          "arguments": [],
          "directives": [],
          "selectionSet": {
            "kind": "SelectionSet",
            "selections": [
              {
                "kind": "Field",
                "name": {
                  "kind": "Name",
                  "value": "id",
                  "loc": {
                    "start": 300,
                    "end": 302
                  }
                },
                "arguments": [],
                "directives": [],
                "loc": {
                  "start": 300,
                  "end": 302
                }
              }
            ],
            "loc": {
              "start": 292,
              "end": 308
            }
          },
          "loc": {
            "start": 285,
            "end": 308
          }
        }
      ],
      "source": {
        "body": "subscription {\n  live(id: \"ckruauae114641a8v775fitj4m\") {\n    id\n    startDate\n    startTime\n    shouldShowShareButton\n    shouldShowSummary\n    shouldShowChapter\n    shouldShowDiscussion\n    status\n    pageTheme\n    accentColor\n    title\n    description\n    liveUrl\n    hasReplay\n    replay {\n      id\n    }\n  }\n}\n",
        "name": "GraphQL request",
        "locationOffset": {
          "line": 1,
          "column": 1
        }
      },
      "positions": [
        285
      ],
      "originalError": {
        "stack": "TypeError: Cannot read property 'live' of undefined\n    at Object.replay (/Users/aaasrc/model/Live/index.ts:44:16)\n    at field.resolve (/Users/aaanode_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:100:18)\n    at resolveField (/Users/aaanode_modules/graphql/execution/execute.js:464:18)\n    at executeFields (/Users/aaanode_modules/graphql/execution/execute.js:292:18)\n    at collectAndExecuteSubfields (/Users/aaanode_modules/graphql/execution/execute.js:748:10)\n    at completeObjectValue (/Users/aaanode_modules/graphql/execution/execute.js:738:10)\n    at completeValue (/Users/aaanode_modules/graphql/execution/execute.js:590:12)\n    at resolveField (/Users/aaanode_modules/graphql/execution/execute.js:472:19)\n    at executeFields (/Users/aaanode_modules/graphql/execution/execute.js:292:18)\n    at executeOperation (/Users/aaanode_modules/graphql/execution/execute.js:236:122)",
        "message": "Cannot read property 'live' of undefined"
      }
    }
  ],
  "data": {
    "live": {
      "id": "ckruauae114641a8v775fitj4m",
      "startDate": "2021-08-02T07:16:39.575Z",
      "startTime": "08:00",
      "replay": null
    }
  }
}
```

Version 3.1.1

**Comment by trevor-scheer** [comment] 2021-08-02 17:27
Hey @geosigno, at first glance this appears to be an issue with the operation context and not necessarily the query depth. Can you share the configuration of your `ApolloServer` and `SubscriptionServer`?

I did update some docs recently relating exactly to this (they were incorrect until the end of last week).
https://www.apollographql.com/docs/apollo-server/data/subscriptions/#operation-context

If it seems like you have everything correct, are you able to share a reproduction?

**Comment by glasser** [comment] 2021-08-03 00:11
I'm going to close it for now since it's lacking a complete reproduction, but we're happy to re-open if it does! (I agree with @trevor-scheer. It looks like the `ctx` in your subscription server does not have `prisma` on it, probably because you have to configure it when you set up SubscriptionServer as the new docs explain.)

**Closed by glasser** 2021-08-03 00:11 UTC
