### ISSUE TITLE
[2.0 docs] Document custom scalars Apollo Server 2.0 supports

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/apollo-server#1145] opened 2018-06-05 23:10 UTC
Apollo Server 2.0 supports JSON out of the box as a custom scalar. [We should specify this in the docs](https://github.com/apollographql/graphql-tools/pull/808), along with any other custom scalars we're supporting natively.

**Comment by evans** [comment] 2018-06-06 22:28
Apollo Server doesn't implement the JSON scalar out of the box. Instead, it implements `Upload`. There must be some other issue going on here.

@rgbkrk Let's dig into the problem. If you have a simple implementation, I'd love to add it as a test case. The other option is to create a glitch example by remixing [this one](https://glitch.com/edit/#!/apollo-launchpad)

**Comment by unicodeveloper** [comment] 2018-06-07 06:19
@evans @peggyrayzis What's the status on this? If Apollo Server 2.0 doesn't implement JSON scalar out of the box, then what's this [PR](https://github.com/apollographql/graphql-tools/pull/808) about?

**Comment by rgbkrk** [comment] 2018-06-07 15:31
Steps to reproduce (happy to make a repo later when I've got a chance):

* `npm install --save apollo-server@beta graphql graphql-type-json`
* Follow the example in https://www.apollographql.com/docs/apollo-server/v2/features/scalars-enums.html#Using-a-package

...which leads me to finding out the real error here:

```js
> require('graphql-type-json')
JSON
> require('graphql-type-json').default
undefined
```

The docs are using the `default` import, when there isn't one on `graphql-type-json`. At least, the way babel has been for some time (?) is that the commonjs module export is not the same as the es6 `default` export.

All that being said though, I didn't have to set up a JSON resolver for my very beginner efforts with GraphQL. I went ahead and made public the little exploration @peggyrayzis helped me with here: https://github.com/nteract/graphql-schema-exploration

```bash
git clone https://github.com/nteract/graphql-schema-exploration.git
cd graphql-schema-exploration
npm i
npm run start
```

In the graphql playground / server that comes up, run:

```graphql
{
  cell(cellId: "cell-123") {
    metadata
  }
}
```

Which should return the arbitrary JSON payload contained within the metadata:

```json
{
  "data": {
    "cell": {
      "metadata": {
        "a": 1
      }
    }
  }
}
```

**Comment by evans** [comment] 2018-06-07 17:29
@rgbkrk oh geez, we should definitely change those imports into require statements in the documentation that you linked to. Thank you for pointing it out 🎉

**Comment by evans** [comment] 2018-06-07 18:44
Closing since #1150 is merged in. If you'd like to add your example repo to the docs as a clonable glitch, similar to [here in the docs](https://github.com/apollographql/apollo-server/blame/version-2/docs/source/getting-started.md#L182), it would be **much** appreciated.

**Closed by evans** 2018-06-07 18:44 UTC
Labels: docs
