### ISSUE TITLE
buildFederatedSchema only accepts one type definition

### ISSUE THREAD

**Issue by drager** [apollographql/apollo-server#3602] opened 2019-12-12 15:11 UTC
Hi, using `buildFederatedSchema` with multiple `typeDefs` are not possible? When using `apollo-server` I can pass an `Array` of `DocumentNode` for the parameter `typeDefs` as seen here: https://www.apollographql.com/docs/apollo-server/api/apollo-server/#parameters however when I use `buildFederatedSchema` it no longer takes an array and only one type def as seen here: https://www.apollographql.com/docs/apollo-server/api/apollo-federation/#buildfederatedschema

Shouldn't these be the same?

How would you construct the following with `buildFederatedSchema`:

```typescript
const server = new ApolloServer({
  typeDefs: [
    createRateLimitTypeDef('burstRateLimit'),
    createRateLimitTypeDef('sustainedRateLimit'),
    typeDefs,
  ],
  resolvers,
  schemaDirectives: {
    burstRateLimit: createRateLimitDirective(),
    sustainedRateLimit: createRateLimitDirective(),
  },
})
```

Not possible to pass an array to `typeDefs`:

```typescript
const schema = buildFederatedSchema([
  {
    typeDefs: gql(typeDefs),
    resolvers,
  },
])
```

**Comment by micksi** [comment] 2019-12-29 21:46
I have the same issue you as but looking into the code it should support a list of document nodes. But I haven't made it work yet.

```javascript
type LegacySchemaModule = {
  typeDefs: DocumentNode | DocumentNode[];
  resolvers?: GraphQLResolverMap<any>;
};

export function buildFederatedSchema(
  modulesOrSDL:
    | (GraphQLSchemaModule | DocumentNode)[]
    | DocumentNode
    | LegacySchemaModule,
): GraphQLSchema {
...
```

**Comment by micksi** [comment] 2019-12-30 13:34
Not sure if this will help you!

I have the same issue as you as mentioned before but I realized I was exporting a function from my typeDefs files, which looked kinda like this
```javascript
const Dashboard = gql`
  type Dashboard {
    sektioner: [Sektion]
  }
`;
...
export const typedef = () => [Dashboard, Visning, Logintype];
```
Then it was just a matter of flattening them out in the typeDefs array which is given to the federationBuilder

```javascript

const typeDefs: any = [
  SchemaDefinition,
  ...dashboard.typedef()
]
...

export const schema: any = buildFederatedSchema({
  typeDefs,
  resolvers
});
```
This approach worked for me can't say it will work for you and btw I believe the graphql package you should use has to be or greater than 14.2.2

**Comment by trevor-scheer** [comment] 2020-01-09 21:48
Hi there, can either of you please provide a reproduction where an array of modules _doesn't_ work? This is a use case that we fully support and for as long as I've known, it's in working order.

i.e.
```ts
buildFederatedSchema([{ typeDefs, resolvers }])
```

I'm going to close this, but will gladly reopen with a runnable reproduction. Thanks!

**Closed by trevor-scheer** 2020-01-09 21:48 UTC

**Comment by micksi** [comment] 2020-01-10 09:29
@trevor-scheer the issue is that the exported typedefs are wrapped in a function like this

```javascript
export const typedef = () => [Dashboard, Visning, Logintype];
```
exporting just the a list of the typedefs might also have worked but I didn't check that.

I have tried to clarify how the old approach worked in the following
```javascript
const typeDefs: any = [
  SchemaDefinition,
  () => [Dashboard, Logintype],
  () => [User, Company]
]

// throws an error when trying to build the federatedSchema
export const schema: any = buildFederatedSchema({
  typeDefs,
  resolvers
});
```

**Comment by NFabrizio** [comment] 2020-05-20 15:27
@drager I had the same issue, and the solution that worked for me was the following.
```
const schema = buildFederatedSchema({
  typeDefs: gql(typeDefs),
  resolvers
})
```
For me when passing typeDefs and resolvers that are themselves arrays, I had to pass buildFederatedSchema an object instead of an array.

**Comment by khacnha** [comment] 2020-09-28 03:19
I got this error, it always returns null. Unable to connect to resolvers.

Does anyone have a better solution to this problem.

`
typeDefs.js
module.exports = [
    customScalarResolver,
    pageResolvers,
    faqResolvers,
];


resolvers .js
module.exports = [
  linkSchema,
  pageSchema,
   faqSchema,
];


buildFederatedSchema([{ typeDefs, resolvers }])
`
