### ISSUE TITLE
Middy - Unhandled Promise Rejection

### ISSUE THREAD

**Issue by acaxon** [apollographql/apollo-server#5986] opened 2022-01-05 20:38 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a simple lambda function with Apollo Server and middy:

```js
import { ApolloServer, gql } from 'apollo-server-lambda'
import { buildFederatedSchema } from '@apollo/federation'
import middy from '@middy/core'
import { resolvers } from '../graphql/resolvers'
import { graphqlFileToStr } from '../graphql/schema'

const typeDefs = gql(graphqlFileToStr)

const server = new ApolloServer({
  schema: buildFederatedSchema({
    typeDefs,
    resolvers,
  })
})

const graphqlHandler = server.createHandler()
const handler = middy(graphqlHandler)

export { handler as apolloServer }
```

2. Now put a middy plugin - **httpJsonBodyParser**, for example:

```js
import { ApolloServer, gql } from 'apollo-server-lambda'
import { buildFederatedSchema } from '@apollo/federation'
import middy from '@middy/core'
import httpJsonBodyParser from '@middy/http-json-body-parser'
import { resolvers } from '../graphql/resolvers'
import { graphqlFileToStr } from '../graphql/schema'

const typeDefs = gql(graphqlFileToStr)

const server = new ApolloServer({
  schema: buildFederatedSchema({
    typeDefs,
    resolvers,
  })
})

const graphqlHandler = server.createHandler()
const handler = middy(graphqlHandler)
  .use([
    httpJsonBodyParser(),
  ])

export { handler as apolloServer }
```
What happens?
-------------
The first code works great, but the second return this:

```json
{
  "message": "Internal server error"
}
```

What were I expecting to happen?
----------------------------------
The second code to work as well.

Any logs, error output, etc?
----------------------------

The first code works great, but the second one break with the following log in CloudWatch:

```json
2022-01-05T20:08:21.631Z	238b903b-bcfa-40c4-bd10-bcad05ece2c7	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
        "code": "ERR_INVALID_ARG_TYPE",
        "stack": [
            "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
            "    at Function.from (buffer.js:330:9)",
            "    at y (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14583:17)",
            "    at m (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14602:12)",
            "    at Object.y [as getRequest] (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14252:60)",
            "    at r (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:15309:37)",
            "    at /var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14089:9",
            "    at new Promise (<anonymous>)",
            "    at A (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14076:12)",
            "    at N (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14115:12)",
            "    at /var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:31844:27"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.emit (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:96865:21)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

What versions of software are you using?
----------------------------------------
**apollo-server-core**: 3.6.1
**apollo-server-lambda**: 3.6.1
**Node JS**: 14.15.0
**Middy**: 2.5.3
**AWS SDK**: @^2.1033.0, aws-sdk@^2.1036.0, aws-sdk@^2.7.0 (yarn.lock)

### This bug report should include:

- [x] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [x] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [x] The expected behavior.
- [x] The actual behavior.
- [x] A **simple**, runnable reproduction!

**Comment by glasser** [comment] 2022-01-05 21:29
Is this something you can only reproduce by actually deploying to Lambda, or is it possible to reproduce locally? Can you make it possible for me to reproduce this with absolutely no creativity required (eg, a repo I can clone or codesandbox.io sandbox and a precise set of commands to run)?

(I haven't seen Middy before but it does look nice. Apollo Server 3's Lambda integration allows you to extend it via Express by converting between Express and Lambda using `@vendia/serverless-express`, but perhaps an Apollo Server 4 Lambda integration should just encourage the use of Middy.)

**Comment by glasser** [comment] 2022-01-05 21:40
I also admit I'm a bit confused about what you're trying to do here.  apollo-server-lambda parses the body as JSON for you by default.  It thus expects to receive the body as a string.  It will be confused if you parse it yourself first. So my only surprise here is that this works at all the first time.

Because (in AS3) apollo-server-lambda is implemented as a layer on top of apollo-server-express, if you want to adjust something about the JSON parsing you do it by passing `server.createHandler({expressGetMiddlewareOptions: {bodyParserConfig}})` This can either be an object that gets passed to the `json` function from the `body-parser` package, or `false` to disable that parsing (in which case you should do the parsing yourself, but inside the express app, not at the Lambda layer, since the latter will presumably confuse `@vendia/serverless-express`.

(This is all a bit complex and we will soon be sharing our goals for an Apollo Server 4 which has a lot less magic built in and is easier to understand.)

Since I don't think this is expected to work, I'm closing the issue, but let me know if I'm missing something.

**Closed by glasser** 2022-01-05 21:40 UTC

**Comment by acaxon** [comment] 2022-01-05 22:04
First of all, thank you for the quick response, @glasser.

I put **http-json-body-parser** just like an example, but I'm really trying to use **http-error-handler** so I can centralize error handling in the middleware. Would you suggest another approach to centralize it?

Sorry about not including all you need to reproduce the error.

**Comment by glasser** [comment] 2022-01-05 22:29
That makes more sense! If you can share a full reproduction with that middleware then I'd be happy to look into it.

**Comment by acaxon** [comment] 2022-01-05 22:30
**I found the error !!!**

The problem was exactly **http-json-body-parser** plugin. I didn't know Apollo Server already parses the body and when I used just _http-error-handler_ plugin, it just worked.

I think when _http-json-body-parser_ tried to do its job, the arguments it receives wasn't a string (because Apollo Server had "transformed" it in an object.

Anyway, **thanks a lot** for your **time**, @glasser.
