### ISSUE TITLE
Mutation receives args object with a null prototype

### ISSUE THREAD

**Issue by lookfirst** [apollographql/apollo-server#3149] opened 2019-08-12 03:41 UTC
### This bug report should include:

- [X] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [X] The package name and version of Apollo showing the problem.
- [O] If applicable, the last version of Apollo where the problem did _not_ occur.
- [X] The expected behavior.
- [X] The actual behavior.
- [X] A **simple**, runnable reproduction!

## Related SO

https://stackoverflow.com/questions/53983315/is-there-a-way-to-get-rid-of-object-null-prototype-in-graphql

## Actual behavior

This has been discussed on SO, but the solution is less than ideal. Serializing things through json is silly overhead. If anything it is confusing and undefined/undocumented behavior. I'm filing this as a bug since a mutation should get an object passed in with a prototype. A query receives an `args` object with a prototype. This behavior should at least be made consistent and ideally an object with a prototype.

## Example code:

```js
	Mutation: {
		create: async (_, args, context, info) => {
			console.log(args.thing);
		},
	},
```

## Output:

```
[Object: null prototype] {
    id: '00112233445566'
}
```

## Expected behavior

```
{
    id: '00112233445566'
}
```

## Current workaround

```js
console.log(JSON.parse(JSON.stringify(args.thing)))
```

**Comment by lookfirst** [comment] 2019-08-12 03:59
https://spectrum.chat/apollo/apollo-server/having-trouble-calling-a-query-within-a-mutation-resolver~d54a9093-f0fd-44a5-9008-85f0611a19d3

**Comment by lookfirst** [comment] 2019-08-12 04:00
https://www.prisma.io/forum/t/error-object-null-prototype-appears-before-each-node-returned-in-queries-from-nodejs/5780

**Comment by trevor-scheer** [comment] 2019-08-14 00:18
Hey @lookfirst, thanks for reporting an issue. If I understood correctly, this problem is experienced by non-AS users as well? This led me to believe it may be one of the underlying libraries instead (graphql-tools or graphql-js, most likely).

I put together a minimal reproduction to confirm my suspicion and found it to be true:
https://gist.github.com/trevor-scheer/e7f4022b5ce81ade7b79a206d16e9fd4

I was also surprised to find that the args for a _query_ were also an object with a null prototype:
```
{ data: [Object: null prototype] { create: 'Blah' } }
{ data: [Object: null prototype] { get: 'Blah' } }
```
which is inconsistent with what you said unless I misunderstood:
> A query receives an args object with a prototype. This behavior should at least be made consistent

I confirmed the behavior _is_ consistent in both my gist and an ApolloServer-fied version of my gist.

I'm going to close this issue, since it's not ApolloServer's doing, but an underlying library. Please feel free to reference this issue elsewhere if you choose to confirm where this is specifically coming from.

Related: I'm unsure why this is an issue for a consumer. Is it problematic for logging purposes, or is this actually having an impact on the expected inputs? You should be able to access everything on the `args` object as expected, but please correct me if I'm overlooking something!

**Closed by trevor-scheer** 2019-08-14 00:18 UTC

**Comment by lookfirst** [comment] 2019-08-14 06:03
Interesting. Thanks for reproducing outside of Apollo. It will help me dig deeper.

I did not notice this on the query because I was only defining Foo(id: ID!) and not a full object.

Passing these objects into firebase/firestore for mutation causes failure because  `obj.hasOwnProperty` is missing.

**Comment by lookfirst** [comment] 2019-08-14 06:25
Related: https://github.com/graphql/express-graphql/issues/177

**Comment by lookfirst** [comment] 2019-08-23 02:28
Google fixed this in firestore! https://github.com/googleapis/nodejs-firestore/pull/736

**Comment by trevor-scheer** [comment] 2019-08-23 16:16
@lookfirst Hey, nice work - and thanks for the update. Glad it all worked out 😄

**Comment by strange-cat-fe** [comment] 2021-06-09 13:35
You can just distructure an object with [Object: null prototype]

**Comment by paulomcnally** [comment] 2021-06-11 08:07
any solution for this?

**Comment by lookfirst** [comment] 2021-06-11 14:43
> any solution for this?

https://github.com/apollographql/apollo-server/issues/3149#issuecomment-524147999

**Comment by quinten1333** [comment] 2022-05-04 16:36
I made a simple library to fix this. The library is faster than going to json and back because it works in place. Link: https://www.npmjs.com/package/normalize-object-inheritance

**Comment by glasser** [comment] 2022-05-05 22:15
FWIW, I'm pretty sure this is a feature. It means that you can have args with names like `toString` and `constructor` and such without them being treated specially.

**Comment by iambumblehead** [comment] 2022-11-28 20:13
graphql should return plain data that can be used safely with other programs. For example, nodejs' native assert will fail when comparing graphql's `[Object: null prototype]` object with normal javascript objects used by other software,
```javascript
import assert from 'node:assert/strict';
import gqlreq from './gqlreq.js';

const gqlres = await gqlreq();

console.log(gqlres);
// [Object: null prototype] {
//   user: [Object: null prototype] {
//     id: 'ywj--Y3SxiXk4TEa04Wz5'
//   }
// }

assert.deepEqual(gqlres, {
  user: {
    id: 'ywj--Y3SxiXk4TEa04Wz5'
  }
}); // ERR_ASSERTION, Expected values to be strictly deep-equal
```

**Comment by glasser** [comment] 2022-11-28 20:24
FWIW this choice is made inside `graphql-js`, not `apollo-server`.

It's discussed at length in this PR: https://github.com/graphql/graphql-js/pull/504#issuecomment-1179264925

As I commented there a few months ago, the biggest strangeness is that `graphql-js` makes an inconsistent choice between whether a prototype is applied between whether an object is literally part of the GraphQL language document (in which case there is no prototype) or whether it comes from the `variables` JSON chunk (in which case there is a prototype).

The issue with fields that have names like `toString` is a real one and in an ideal world `graphql-js` would use Maps instead of prototype-less objects here, but using a prototyped object doesn't seem like a great solution due to the conflict issue.

**Comment by iambumblehead** [comment] 2022-11-28 20:36
> FWIW this choice is made inside graphql-js, not apollo-server.

Acknowledged.

Here's little work-around that deep-recurses the graphql object to return a normal object that can be used with other tools like node's assert. If your objects aren't too deep, this might be OK for unit-tests
```javascript
const ungqlval = (value, type = typeof value, f = null) => {
  if (value === f || /string|number|boolean/.test(type))
    f = value;
  else if (Array.isArray(value) || type === 'object')
    f = ungql(value);

  return f;
};

const ungql = data => Object.keys(data).reduce((prev, k) => {
  prev[k] = ungqlval(data[k]);

  return prev;
}, Array.isArray(data) ? [] : {});
```
