### ISSUE TITLE
Bun integration on subscription (Query and Mutation Works, but not Subscription)

### ISSUE THREAD

**Issue by HuakunShen** [apollographql/apollo-server#7776] opened 2023-11-02 18:49 UTC
I was using bun to run apollo server and nestjs, it worked fine, both Query and Mutation works normally, but when I start working on subscription it always fails to connect (I was using the apollo playground). 

No error was shown, after debugging for a few hours I realized that it's bun runtime that causes the problem. 

I followed this tutorial https://www.apollographql.com/docs/apollo-server/data/subscriptions#basic-runnable-example

Subscription works fine when using nodejs or `ts-node-esm`, but fails as long as I switch to bun.

## Reproduction

- https://github.com/apollographql/docs-examples/blob/main/apollo-server/v4/subscriptions-graphql-ws/src/index.ts

```bash
bun install
bun src/index.ts
```

Bun is a really good tool. It allows me to import typescript from other packages without compiling to JS. I can't really switch to nodejs for the project.

I used WebSocket with bun, it works.
There is no error message, so I don't know what's going on. Apollo Server is probably using some API bun doesn't implement.

**Comment by HuakunShen** [comment] 2023-11-05 03:59
Here is an issue I made in bun repo.

https://github.com/oven-sh/bun/issues/6905

**Comment by trevor-scheer** [comment] 2023-11-08 18:22
I would be happy for this project to support Bun, but I don't have the time to take on this work. I will gladly help with and review a PR which resolves this if you're interested in trying to fix it.

I've outlined my desired approach in another issue:
https://github.com/apollographql/apollo-server/issues/7733#issuecomment-1741343439

I'm going to close this as a duplicate of #7733 and specifically mention subscriptions there as well. Which subscription library were you using? That part is likely a separate issue for a separate project.

**Closed by trevor-scheer** 2023-11-08 18:22 UTC
