### ISSUE TITLE
new Apolloserver(args) fails typescript validation

### ISSUE THREAD

**Issue by Shpackk** [apollographql/apollo-server#7296] opened 2023-01-11 11:06 UTC
### Issue Description

Passing arguments of 
```
{
typedefs,
resolvers,
}
```

to a new instance of ApolloServer class, results in an error. < Expected 0 arguments, but got 1 >

Project dependencies: 
 ```
 "devDependencies": {
    "@types/node": "^18.11.18",
    "nodemon": "^2.0.20",
    "typescript": "^4.9.4"
  },
  "dependencies": {
    "@apollo/server": "^4.3.0",
    "graphql": "^16.6.0",
    "ts-node": "^10.9.1"
  }
```
Node - 18.12.1
Npm - 8.19.2

Reloading of typescript-server, VScode project, VScode itself, of Vscode window, does not help.
Also 'npm rebuild' doesn't work as well.

### Link to Reproduction

.

### Reproduction Steps

Install apollo-server, and try to create a new instance of ApolloServer with arguments of typedefs or (and) resolvers.

```
import { ApolloServer } from '@apollo/server';
import { startStandaloneServer } from '@apollo/server/standalone';


const books = [
  {
    title: 'The Awakening',
    author: 'Kate Chopin',
  },
  {
    title: 'City of Glass',
    author: 'Paul Auster',
  },
];

const typeDefs = `#graphql
  type Book {
    title: String
    author: String
  }

  type Query {
    books: [Book]
  }
`;


const resolvers = {
  Query: {
    books: () => books,
  }
}

const server = new ApolloServer({
  typeDefs,
  resolvers,
}) // ERROR
const {} = await startStandaloneServer(server)
```

TypeScript Config.

```
{
"compilerOptions": { 
  "target": "ES2020",
    "lib": ["ES2020"], 
  "module": "esnext",
    "rootDir": "./",
    "moduleResolution": "node",  
"outDir": "./build/" ,
  "esModuleInterop": true,
 "strict": true,
"noImplicitAny": true,
  "strictFunctionTypes": true ,
"skipLibCheck": true ,
}
}
```

**Comment by Shpackk** [comment] 2023-01-11 11:27
Upd. something is wrong with types here
<img width="715" alt="Screenshot 2023-01-11 at 13 27 25" src="https://user-images.githubusercontent.com/76433892/211794870-6743f697-64f5-44ac-9364-b29637803c80.png">

**Comment by RemyMachado** [comment] 2023-01-11 16:22
You have to tell `ApolloServer` which context type you are using.

For instance:

```typescript
type MyContextType = {
  bearerUser?: User
}

new ApolloServer<MyContextType>(...)
```

**Comment by Shpackk** [comment] 2023-01-11 16:39
I tried adding a context, but it produces the same error <Expected 0 arguments but got 1> (but with a context)

**Comment by RemyMachado** [comment] 2023-01-11 17:00
Sorry I read your error log wrong. I thought it was asking for `1` argument.

___ 

Since you seem to use a version of TypeScript newer than 4.7, it shouldn't cause an error (even if your IDE says otherwise). Can you verify in your `yarn.lock` or `package-lock.json` that you really are using a newer version?
For instance:
![image](https://user-images.githubusercontent.com/30229752/211868671-b2132fef-9cad-4db7-a88a-392643d4fd52.png)

Also, can you log the full TS error stracktrace so we can try to help you better please? The error might be referring to another class.

About `<in out>`, from the official documentation:
![image](https://user-images.githubusercontent.com/30229752/211868019-b86df826-0bf8-4953-939a-6fe5d5a41a30.png)

**Comment by trevor-scheer** [comment] 2023-01-11 17:15
This seems like an editor issue. What do you see when you click the little `{ }` shown here?
<img width="166" alt="image" src="https://user-images.githubusercontent.com/29644393/211871585-e793b768-0510-4c24-8eec-13b40a0460b4.png">

I followed your steps to reproduce and got no errors when I run `npx tsc` (which runs the typescript compiler, I consider that to be a better source of truth for TypeScript errors vs. the editor).

When you share a reproduction, something I can `git clone` is much preferred so I know we're working with exactly the same thing + it saves me time.

**Comment by trevor-scheer** [comment] 2023-01-11 17:16
Also it's fine not to specify `<TContext>` since it defaults to `BaseContext` and you're not providing a `context` fn to `startStandaloneServer`.

**Comment by trevor-scheer** [comment] 2023-01-13 19:08
Going to close this since I can't reproduce, but I'm happy to open if a full-fledged reproduction that I can clone and run with zero creativity or implementation on my end is provided.

**Closed by trevor-scheer** 2023-01-13 19:08 UTC

**Comment by trevor-scheer** [comment] 2023-02-20 03:43
@branaust as I mentioned before closing the issue, I can't reproduce this. If you can provide me a reproduction I can investigate further. Without one I can't be any more helpful than I have already been.
