### ISSUE TITLE
ApolloServerPluginUsageReporting does not allow to pass http agent

### ISSUE THREAD

**Issue by vany0114** [apollographql/apollo-server#7813] opened 2024-01-04 13:35 UTC
### Issue Description

Hello,

I'm using Apollo Federation in an Azure environment, specifically deployed as an Azure Function. I've noticed that the `ApolloServerPluginUsageReporting` is causing a lot of `connect ETIMEDOUT` as it seems it is exhausting the available Websockets/TCP connections when making this request to: `HTTP: POST usage-reporting.api.apollographql.com/api/ingress/traces`, I guess most likely because it is not reusing the HTTP contention, so I had to disable the reporting as I could not find a way to pass an HTTP agent to the plunging to keep alive the connection to avoid the issue mentioned above.

Is there a workaround or you guys can please point me to the right direction?

### Link to Reproduction

N/A

### Reproduction Steps

Versions used:
```
"@apollo/gateway": "^2.5.1",
"@apollo/server": "^4.9.0",
"@apollo/server-plugin-landing-page-graphql-playground": "^4.0.1",
"@apollo/server-plugin-response-cache": "^4.1.3",
"@apollo/subgraph": "^2.5.1",
```

**Comment by glasser** [comment] 2024-01-04 18:49
Duplicate of #7811

**Closed by glasser** 2024-01-04 18:49 UTC
