### ISSUE TITLE
can't access the graphql playground

### ISSUE THREAD

**Issue by judicaelandria** [apollographql/apollo-server#4582] opened 2020-09-22 18:17 UTC
I install and reinstall apollo-server-express but it always shows me that he could find the config in the browser console,
for the network, it shows a"GET"
here is some screenshot, I searched for a solution everywhere but none of them worked

![error](https://user-images.githubusercontent.com/46365844/93921257-fdf5ac80-fd18-11ea-9398-500088473d93.PNG)
![code 2](https://user-images.githubusercontent.com/46365844/93921276-0221ca00-fd19-11ea-8c5d-ccc080daa199.PNG)

**Comment by iamchathu** [comment] 2020-09-23 12:00
I'm also having the issue with latest version. Seems CSP (Content Security Policy) is blocking the middleware.js 

I get graphql playground page hold up with the animation.

**Comment by judicaelandria** [comment] 2020-09-23 18:34
did you try thy older version? did it work?

**Comment by trevor-scheer** [comment] 2020-09-24 19:47
Hey @judicaelandria, I can't reproduce this error with a minimal `ApolloServer` configuration (using `express`). Can either you or @iamchathu please provide a runnable reproduction so I can debug this? Thanks!

**Comment by judicaelandria** [comment] 2020-09-25 10:49
Hey,
still getting the error, even if I use the older version
but what do you mean by reproduction?

**Comment by judicaelandria** [comment] 2020-09-25 10:50
should I send my code to github? so you can debug it
because I don't think the error comes from my code :(,

**Comment by judicaelandria** [comment] 2020-09-28 06:15
@trevor-scheer , mine is working now, I think I just needed to have an internet connection when running it
so I'll close this now!
thanks!

**Comment by judicaelandria** [comment] 2020-09-28 18:23
I'll reopen this because, when I don't have an internet connection, the playground doesn't work. it only works when I can connect to the internet, otherwise, it should work even if I don't have an internet connection, right?

**Comment by trevor-scheer** [comment] 2020-09-30 15:13
@judicaelandria thanks for the additional info! This is actually expected behavior, so I'm going to close this issue. You'll notice when Playground loads (in the network tab of your inspector), it sends a number of requests to a CDN for everything Playground needs to run - this includes JS, styles, and maybe some other assets. This is a decision made by the creators of Playground, which we've only continued to do in our fork. We don't intend to make any changes to this.

To answer your previous question:

>but what do you mean by reproduction?

A reproduction is exactly what you've presumed. It's code that you share which allows me or another developer to see the bug. It's best to provide something as simple as possible (minimal reproduction) in order to eliminate distractions and other potential causes of the bug you are demonstrating. It's best if the code you share is easily runnable to save the other person time and additional headache of getting it running.

In general (across all of GitHub / open source), your issues will be very well received if they come with a great explanation of the problem, a reproduction, and any instructions needed to demonstrate the bug.

**Closed by trevor-scheer** 2020-09-30 15:13 UTC
Labels: :wilted_flower: needs-reproduction
