### ISSUE TITLE
should not be new validateSchema called in runQuery?

### ISSUE THREAD

**Issue by jardakotesovec** [apollographql/apollo-server#936] opened 2018-04-03 06:53 UTC
- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

in graphql-js 0.12 schema validation was [taken out](https://github.com/graphql/graphql-js/releases/tag/v0.12.0) from constructor and moved to `validateSchema`. Therefore it's used [explicitly](https://github.com/graphql/graphql-js/commit/34a53cb18866527714f67a4490b1dc8fb8b06463#diff-e896d5930c71857fc9566b22defba666R172) in wrapping function from 0.12.0.  Did not find that `runQuery` would be adjusted for this change, so its now basically skipping this `validationSchema` step. Is that intention or oversight?

**Comment by abernix** [comment] 2019-07-02 13:16
Thanks for reporting this originally and sorry it's taken so long to triage this.

I'll close this since most of the request pipeline has been overhauled in Apollo Server as https://github.com/apollographql/apollo-server/pull/1795 and we haven't seen any recurring reports of this, but if you're still experiencing problems with this, please do open a new issue with a runnable reproduction (per the instructions when opening a new issue).

Thanks!

**Closed by abernix** 2019-07-02 13:16 UTC
Labels: :rose: has-reproduction
