### ISSUE TITLE
ApolloServer is not a constructor - 2

### ISSUE THREAD

**Issue by sandorTuranszky** [apollographql/apollo-server#2246] opened 2019-01-30 13:32 UTC
I know this issue was discussed in #1296 but the error persists and installing `apollo-server-express@rc` does not help. Is it going to be resolved in the nearest future?

**Comment by gaborszekely** [comment] 2019-02-09 19:46
Same here. I tried all the hacks, including downloading the correct Core-Js package and installing apollo-server-express@rc and nothing has fixed is so far. Any tips?

**Comment by jsegaran** [comment] 2019-07-08 20:26
Hi. Thanks for reporting this issue!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already. If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

**Closed** 2019-07-08 20:26 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
