### ISSUE TITLE
When using @defer, loadingState doesn't contain array type field with null value

### ISSUE THREAD

**Issue by felipe-gdr** [apollographql/apollo-server#1736] opened 2018-09-26 22:14 UTC
So it's not possible to check if the array has been loaded and actually has a null value or if it is still being loaded.

It's easy to reproduce this in the `defer-demo`. Just remove `comments` from [any of the story objects](https://github.com/apollographql/defer-demo/blob/master/server/newsFeedSchema.js#L52)

Example
```
const story1 = {
  id: 1,
  title: 'Breaking news: Apollo Project lands first human on the moon',
  text: () => delay('Some text', 5000),
  comments: [], // empty arrays work fine
};
const story2 = {
  id: 2,
  title: 'China's super-sized space plans may involve help from Russia',
  text: () => delay('Some text', 5000),
  // comments is undefined, so loadingState won't tell us when it has finished loading it. The comments component will remain forever in the loading state.
};
```

**Comment by jsegaran** [comment] 2019-07-08 20:52
Thanks for reporting this issue originally!

I'm going to close this issue since it hasn't received a lot of traction and could have been resolved already.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Closed by jsegaran** 2019-07-08 20:52 UTC
Labels: 🚧👷‍♀️👷‍♂️🚧 in triage
