### ISSUE TITLE
Batched queries result in undefined context

### ISSUE THREAD

**Issue by chrissm79** [apollographql/apollo-server#461] opened 2017-07-13 19:00 UTC
Not sure when this started but when I send a batched query it results in an `undefined` context. Using Apollo Client, if I use `createNetworkInterface` my queries run just fine, but when switching to `createBatchingNetworkInterface`, my server errors out with `cannot call authorized on undefined`.

I'm using `graphql-server-express`

**Comment by freiksenet** [comment] 2017-07-17 10:49
Hi!

Thank you for the report. I wonder if you have a bigger repro case for this? I've tried running multiple queries and it seems to be working properly on my side.

Thanks!

**Comment by chrissm79** [comment] 2017-07-18 15:29
Well, the query itself runs just fine but the context is undefined which is something I rely on to hold the current user. Attached some screenshots below, you can see that the only difference between the requests is wrapping the second in array brackets. It makes its way to the resolver but the context isn't set so it throws an error.

<img width="1079" alt="screen shot 2017-07-18 at 9 25 41 am" src="https://user-images.githubusercontent.com/1976169/28325586-6ecc6204-6b9b-11e7-994f-5b9cdaaaf0a3.png">
<img width="1080" alt="screen shot 2017-07-18 at 9 26 06 am" src="https://user-images.githubusercontent.com/1976169/28325587-6ee727ba-6b9b-11e7-86b0-1505a469b79d.png">

**Comment by chrissm79** [comment] 2017-07-18 20:41
Jumping in and out of this project today but I might have found the issue. My context is a class (similar to [this project](https://github.com/w3tecch/express-graphql-typescript-boilerplate/blob/629daa226d73da6abdc2cfe8f62f805745a4679c/src/routes/GraphQLRoutes.ts#L34-L38)). If I use a plain object instead, it seems to work I just haven't had time to fully test.

**Comment by chrissm79** [comment] 2017-07-19 19:43
Confirmed that it is indeed due to the context being a class and not a POJO. If this is expected behavior just let me know and I'll close the issue. Otherwise, I can rename the issue to something more relevant and if time prevails I'll submit a PR to allow for the context to be set to a class (maybe by requiring a factory function that's called on each request?). Thanks!

**Comment by freiksenet** [comment] 2017-07-20 10:09
Hi!

Yeah, the context is copied by doing `Object.assign({}, context)` so that a new version of context is used in each batch (in case it's mutated). It does break for class-like contexts. 

So there are two options on how to proceed here. We could create a context via context function every time we create a batch job, but this might be inefficient in case context creation is somehow expensive. However, this will be a more semantically correct way to do this, because in normal scenario we do create a context for each function. Alternatively we can mandate that context should be a POJO.

Pinging more people to chip in. @helfer @stubailo

**Comment by helfer** [comment] 2017-07-20 17:00
Another alternative would be to explicitly say that the context should not be mutated, which would let us skip the `assign` step. Although we should probably check why it was introduced in the first place before we do that.

**Comment by ericclemmons** [comment] 2017-07-21 20:11
I'm using a class for Context, and ran into similar issues. 

I had no idea that was the culprit. 

I agree that we should look into why the POJO assumption exists.

**Comment by freiksenet** [comment] 2017-07-24 12:50
I've been thinking about this over the weekend. I think we should definitely remove the copying, because  it doesn't really solve the problem, just makes it seem not there for trivial stuff.

I'll write out basic assumptions and ideas about this.

We naturally want batched queries to be executed *exactly* like the non-batched query, in a way that the results should be the same. The only thing that will guarantee that happening is actually creating context (and thus the whole GraphQLOptions type) from scratch for every request in a batched request. Copying doesn't really remove the problem of mutation in context as a) mutation might change nested objects b) state might be kept in a stateful object inside the context (eg I've had things like "stats" inside context, which had imperative API and which resolvers called).

However, there might be performance penalties to creating so many contexts. One might want to share, eg, database connection or some other expensive context object. Having said that, I'm not sure this concern is more important than correctness of execution. In addition, one can do such performance optimizations by separating expensive parts of context from context creation (eg by having some database client abstraction that maintains connection).

Therefore, my proposal is - modify the logic, so that in batched queries context (GraphQLOptions) is created separately for each query. 

CC @helfer

**Comment by csampson** [comment] 2017-10-12 22:17
I ran into this same issue with batching, where _only_ my context object's own properties were defined.

**Comment by bennyhobart** [comment] 2017-11-28 23:03
@freiksenet Reusing context between these operations gives a huge performance boost when using something like data loaders... I'd prefer if you allowed both "reuse" or "creation" for every operation in a batch request

**Comment by bennyhobart** [comment] 2017-12-03 23:03
The more I think about it the more I think this should be removed, as it's only a shallow clone we aren't even able to guarantee the context isn't unique for each request, it requires a builder function. 

happy to push forward with this but need a clear signal from you guys that this work isn't in vain

**Comment by abernix** [comment] 2019-02-19 14:00
Does anyone know if this issue still exists in the latest version of Apollo Server?

If this is still a problem, can someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) build a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

@chrissm79 If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back on the above.  Thanks!

**Comment by JacksonKearl** [comment] 2019-07-02 23:22
Haven't heard back, so going to go ahead and close this. If anyone else experiences this we can definitely take another look!

**Closed by JacksonKearl** 2019-07-02 23:22 UTC
