### ISSUE TITLE
onHealthCheck is not called 

### ISSUE THREAD

**Issue by gastonovic** [apollographql/apollo-server#2468] opened 2019-03-18 10:40 UTC
I followed the documentation on this link to add onHealthCheck method
https://www.apollographql.com/docs/apollo-server/whats-new.html#Health-checks
But when calling the endpoint `.well-known/apollo/server-health` the method is not called
```
const server = new ApolloServer({
  onHealthCheck: () => { console.log('health check'); },
  schema,
});
```

**Comment by aarongundel** [comment] 2019-03-21 05:07
@gastonovic looks like this is related to https://github.com/apollographql/apollo-server/issues/1449 - you can work around it if you use apollo-server-express

**Comment by gastonovic** [comment] 2019-03-21 11:02
@aarongundel Thank you for your response.
yes you're right, it's related to [https://github.com/apollographql/apollo-server/issues/1449](url) . I commented there but no one answered.
 In fact I just wanted to know if there's any plans to fix this issue

**Comment by abernix** [comment] 2019-04-10 14:35
Closing as a duplicate of #1449.  PRs welcome!

**Closed by abernix** 2019-04-10 14:35 UTC
