### ISSUE TITLE
Inconsistent application of scalar parsing in ApolloServer compared to graphqljs

### ISSUE THREAD

**Issue by dyst5422** [apollographql/apollo-server#4509] opened 2020-08-25 16:12 UTC
ApolloServer from apollo-server-express@2.16.1
graphql@15.3.0 (also displayed with 14.5.8 and I assume many other versions)

Here is the code snippet
```typescript
import { makeExecutableSchema } from '@graphql-tools/schema';
import { ApolloServer } from 'apollo-server-express';
import {graphql, GraphQLScalarType} from "graphql";
import { createTestClient } from 'apollo-server-testing';

const DateTime = new GraphQLScalarType({
  name: 'DateTime',
  parseValue: value => new Date(value),
  parseLiteral: valueNode => {
    if (valueNode.kind === 'StringValue') {
      return new Date(valueNode.value)
    }
  },
  serialize: value => value.toISOString(),
})


const typeDefs = `
  scalar DateTime
  type Query {
    test(
      time: DateTime = "2021-02-20T00:00:00Z"
    ): DateTime!
  }
`;

const resolvers = {
  Query: {
    test: (_: any, args: any) => {
      console.log(args.time instanceof Date); // Expect this to be true
      return args.time;
    },
  },
  DateTime,
};


// TEST 1
const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
});

graphql(schema, '{ test }').then(console.log)
/*
 Works as expected, returning the time stamp

 logging:

 true
 { data: [Object: null prototype] { test: '2021-02-20T00:00:00.000Z' } }

*/


// TEST 2
const server = new ApolloServer({
  typeDefs,
  resolvers,
});

const { query } = createTestClient(server as any);

query({
  query: `{ test }`,
}).then(console.log)
/*
 Errors out because it does not parse the literal
 logging:

 false
{
  http: { headers: Headers { [Symbol(map)]: [Object: null prototype] {} } },
  errors: [
    [GraphQLError [Object]: value.toISOString is not a function] {
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
  data: null,
  extensions: undefined
}
*/
```

https://codesandbox.io/s/crazy-lederberg-0fnfh?file=/index.js

Note that this error DOES NOT occur when passing the executable schema to ApolloServer directly as in 
```typescript
const server = new ApolloServer({schema});
```

**Comment by glasser** [comment] 2022-10-21 05:39
This looks like a duplicate of #2716.

**Closed by glasser** 2022-10-21 05:39 UTC
