### ISSUE TITLE
Faild upload file with apollo-server-lambda

### ISSUE THREAD

**Issue by GolivetsAndreu** [apollographql/apollo-server#5093] opened 2021-04-07 12:47 UTC
I get "Error: Missing Content-Type" when I tried upload file. I send event.headers['Content-Type'] and it throw error, but if I send event.headers['content-type'] all is working. For now I resolve it by checking for "content-type" headers before call apollo handler and set it if haven`t.

**Comment by glasser** [comment] 2021-04-07 19:44
Hmm, I think current versions of the code do look in `content-type`. I also don't see the error "Missing Content-Type" anywhere in the code.

We are also in the process of removing the built-in integration with (an outdated version of) `graphql-upload` for Apollo Server 3; instead, we encourage folks who want uploads to use that package directly. Because there's a workaround for this issue (and there isn't a detailed enough reproduction for me to understand where this error comes from) and it won't be part of AS3, I'm going to close this issue.

**Closed by glasser** 2021-04-07 19:44 UTC
